### ISSUE TITLE
DiscoveryConfiguration timeout property missing

### ISSUE THREAD

**Issue by nprail** [stripe/stripe-terminal-ios#102]
## Summary
The `DiscoveryConfiguration` object has a `timeout` property that is documented on it, however, from what I can tell, there is no way to specify that parameter. 

## Code to reproduce
This throws a compile error `Extra argument 'timeout' in call`.
```swift
let config = DiscoveryConfiguration(
    deviceType: deviceType,
    discoveryMethod: discoveryMethod,
    locationId: locationId,
    simulated: simulated,
    timeout: timeout
)
```

And this doesn't seem to actually do anything. 
```swift
let config = DiscoveryConfiguration(
    deviceType: deviceType,
    discoveryMethod: discoveryMethod,
    locationId: locationId,
    simulated: simulated
)
config.timeout = timeout;
```

## iOS version
N/A

## Installation method
Cocoapod

## SDK version
1.4.0

**Comment by bric-stripe** [comment]
👋  the `config.timeout =` is the way you should be setting the timeout. What are your values for simulated and discoveryMethod where you see this not working? Proximity and simulated readers don't currently honor the timeout value

> Note that setting a timeout is not currently supported when using SCPDiscoveryMethodBluetoothProximity, or any simulated discovery. If you set a timeout when using these configurations, the timeout will be ignored.

from https://stripe.dev/stripe-terminal-ios/1.4.0/Classes/SCPDiscoveryConfiguration.html#/c:objc(cs)SCPDiscoveryConfiguration(py)timeout

(I'm _pretty_ sure the Internet discovery method, for P400 also doesn't make use of the timeout param and our docs are missing that...so unless I'm missing it, I'm pretty sure those docs should actually state it's only used during BluetoothScan with a non-simulated reader)

**Comment by nprail** [comment]
Ah, I read that wrong. I thought it said Proximity is the only one that supports timeout :) 

Thanks!
