### ISSUE TITLE
Crash when disconnecting Bluetooth while collect payment

### ISSUE THREAD

**Issue by uncured** [stripe/stripe-terminal-ios#109]
## Summary
After encountering the https://github.com/stripe/stripe-terminal-ios/issues/108 and resolving it with the update to the `2.1.0` SDK version we found the regression in BBPOS adapter model.
Scenario:
- Connect to Bluetooth EMV device
- Start collecting the payment
- While the transaction is in `Progress` state - disable the phone's Bluetooth from the iOS Control Center
- Application crashes with a tracelog:
```
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x1b2694df0 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1b25b4948 pthread_kill + 228
2  libsystem_c.dylib              0x1b2543ba4 abort + 104
3  StripeTerminal                 0x104717004 __36-[SCPBbposAdapterV2 confirmResource]_block_invoke_2 + 2096
4  libdispatch.dylib              0x1b254e134 _dispatch_call_block_and_release + 32
5  libdispatch.dylib              0x1b254f5ac _dispatch_client_callout + 20
6  libdispatch.dylib              0x1b255b7d4 _dispatch_main_queue_callback_4CF + 832
7  CoreFoundation                 0x1b28288d4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
8  CoreFoundation                 0x1b282358c __CFRunLoopRun + 1692
9  CoreFoundation                 0x1b2822bc8 CFRunLoopRunSpecific + 480
10 GraphicsServices               0x1bcc0b5cc GSEventRunModal + 164
11 UIKitCore                      0x1b69d5744 UIApplicationMain + 1936
12 <Redacted>                     0x102fe736c main + 11 (AppDelegate.swift:11)
13 libdyld.dylib                  0x1b269f384 start + 4
```
UPD: Weird enough the issue happens also when you perform the scenario with WisePad3 EMV device, but the crash log still points to `SCPBbposAdapterV2` method...

## Code to reproduce
Nothing specific, just start the collect payment scenario and when "In Progress" disable Bluetooth on the device

## iOS version
`13.7.0`

## Installation method
`Cocoapods`

## SDK version
`2.1.0`

## Other information
None

**Comment by bric-stripe** [comment]
🤦 sorry, came back here to report 2.1.1 is available and saw I had an unsent comment of "we're planning to publish a 2.1.1 release with a fix for this, hopefully released Monday before 11pm UTC.". anyway, it's available now.
