### ISSUE TITLE
BBPOS Chipper 2X BT Firmware SZZZ_Generic_v46 broke chip insertion

### ISSUE THREAD

**Issue by rscherf** [stripe/stripe-terminal-ios#117]
## Summary
After successfully connected a BBPOS Chipper 2X BT and after beginning to collect the payment, no available `ReaderInputOptions` are accepted. I continually receive the `Try Another Reader Method` until it eventually times out.

## iOS version
14.8, iPhone 12 Mini

## Installation method
Cocapods

## SDK version
SDK: 2.2.0
Firmware: SZZZ_Generic_v46

## Other information
```

❗️ 200 : StripeTerminalHelper.swift : connect(to:completion:) :: Optional(<SCPReader: 0x2837144d0; deviceSoftwareVersion = 1.00.03.34-SZZZ_Generic_v46-300001; deviceType = bbpos_chipper2x; label = (null); serialNumber = CHB202107002196; stripeId = tmr_EWloywqacWLkyv; hardwareInfo = {
    bID = CHB202107002196;
    batteryLevel = "4.034";
    batteryPercentage = 89;
    bootloaderVersion = "5.00.16.22";
    deviceSettingVersion = "SZZZ_Generic_v46";
    emvKsn = 3000030011830900000C;
    firmwareVersion = "1.00.03.34";
    formatID = 60;
    hardwareVersion = "1.0.5";
    isCharging = 0;
    isSupportedNfc = 1;
    isSupportedSoftwarePinPad = 0;
    isSupportedTrack1 = 1;
    isSupportedTrack2 = 1;
    isSupportedTrack3 = 0;
    isUsbConnected = 0;
    macKsn = 30000400118309000001;
    pinKsn = 30000100118312000004;
    productID = 4348423230;
    sdkVersion = "3.19.0, 1.5.20";
    serialNumber = CHB202107002196;
    terminalSettingVersion = "SZZZ_Generic_v46";
    trackKsn = 3000020011830900000C;
    uid = 3F001D00025056594E333720;
    vendorID = 535A5A5A;
}; batteryLevel = 0.89; location = <SCPLocation: 0x281553800; stripeId = tml_ETQ6kQR4GzIm6X; displayName = knox; address = <SCPAddress: ...>)
ℹ️ 620 : [Terminal: Requested Reader Input] Swipe / Insert / Tap
ℹ️ 645 : [Terminal: Requested Reader Display Message] Try Another Read Method
ℹ️ 620 : [Terminal: Requested Reader Input] Swipe / Insert
```

**Comment by rscherf** [comment]
Interestingly, if the first attempted payment method is tapping, the transaction completes successfully.

**Comment by rscherf** [comment]
Okay, extremely weird and I feel like a crazy person. Literally after writing this, and 2 days of dealing with the issue described above, it's now working as it should again.

**Comment by rscherf** [comment]
While we're also best buddies here, do you have any idea why `ReaderInputOptions` would be returning a `rawValue` of 7, even though none of the options actually resolve to 7?

https://stripe.dev/stripe-terminal-ios/docs/Enums/SCPReaderInputOptions.html

**Comment by bric-stripe** [comment]
yep, it's an `NS_OPTIONS` set [0] so 7 is all the things: `SCPReaderInputOptionSwipeCard|SCPReaderInputOptionInsertCard|SCPReaderInputOptionTapCard`.

`+ SCPTerminal stringFromReaderInputOptions` is available if you just want a matching string or you can `if (options & SCPReaderInputOptionTapCard)` if want to test for a specific one or in swift the much nicer `options.contains(.tapCard)`

[0] which I see now the header docs there don't really make terribly clear
