### ISSUE TITLE
Stripe M2 reader not showing app when using simulated discovery

### ISSUE THREAD

**Issue by ricardohg** [stripe/stripe-terminal-ios#122]
## Summary
Hello, I'm using latest version of Stripe Terminal iOS SDK `2.3.0`, and when discovering readers with` simulated: true` the M2 Reader is not showing up, only the chipper, do we need to do an extra configuration for this?

## iOS version
14

## Installation method
SPM

## SDK version
2.3.0

**Comment by bric-stripe** [comment]
@ricardohg which discovery method are you using? The simulated M2 reader is currently only showing up during discovery method of `.bluetoothScan`.

We'll likely be updating the `.bluetoothProximity` discovery to support the M2 reader in a future release but the current SDKs are only returning chipper's still.

**Comment by ricardohg** [comment]
that was my bad, I was using `.bluetoothProximity` to detect M2 reader, it showed up when using `.bluetoothScan`.
Thank you very much!
