### ISSUE TITLE
Stripe m2 device keeps on connecting and disconnecting frequently in loop.

### ISSUE THREAD

**Issue by AkshadaKad** [stripe/stripe-terminal-ios#126]
Stripe M2 device gets connected and after 10 sec it got disconnected and after sometime it search for same and connects.
And Attaching one screenshot where I am getting bluetooth connection popup for M2 but not getting same for stripe bbpos device.
Read in previous issues do I need to change bluetoothproximity to bluetoothscan for connecting reader M2?

![WhatsApp Image 2021-12-13 at 10 10 47 AM](https://user-images.githubusercontent.com/58502922/145755936-c6bbe87f-de00-4a49-9b32-daa545d196e7.jpeg)
<img width="394" alt="Screenshot 2021-12-13 at 10 38 00 AM" src="https://user-images.githubusercontent.com/58502922/145755956-aea21bf5-88d1-4825-b695-a89a3458beb8.png">
<img width="426" alt="Screenshot 2021-12-13 at 10 38 19 AM" src="https://user-images.githubusercontent.com/58502922/145755969-5f0d8299-5f23-4f31-a5a9-e4f7dce55704.png">
.

**Comment by bric-stripe** [comment]
> do I need to change bluetoothproximity to bluetoothscan for connecting reader M2?
the physical M2 device will work with proximity discovery but requires the bluetooth pairing prompt to be approved before it shows up.

> screenshot where I am getting bluetooth connection popup for M2 but not getting same for stripe bbpos device
this dialog is expected for the Reader M2 for the secure BLE connection. This is a difference from the Chipper 2X device. The prompt will show up once per iOS device being paired with the reader.

> device gets connected and after 10 sec it got disconnected and after sometime it search for same and connects
I searched through our server side logs for the reader serial number in the screenshot and I'm not seeing any unexpected disconnects. If the Bluetooth pairing prompt wasn't accepted it does timeout. Can you confirm you had already approved the pairing? Could you provide some SDK logs from this happening? If you haven't already you can set a logListener and it will log some internal details:

docs: https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(cm)setLogListener:

simple example
```
        Terminal.setLogListener({ logline in
            print(logline)
        })
```

**Comment by AkshadaKad** [comment]
Thanks for reply.
Have one query what exactly is bluetooth pairing prompt?
You mean pop up for bluetooth pairing?

**Comment by AkshadaKad** [comment]
One more query.
In document have mentioned not to connect reader with mobile settings but you replied that I need to pair it using prompt?
![WhatsApp Image 2021-12-13 at 10 26 19 AM](https://user-images.githubusercontent.com/58502922/145928802-a51a5463-9592-4a25-8a32-96802dc394a1.jpeg)

**Comment by jil-stripe** [comment]
The bluetooth pairing prompt is the little popup you showed in your first screenshot - the first time you connect to a Stripe M2 on a device, you'll have to tap "Pair".

<img width="347" alt="Screen Shot 2021-12-14 at 10 22 04 AM" src="https://user-images.githubusercontent.com/39812724/146026915-c125e132-492c-44b2-836a-5db34a86db4e.png">
 
The "mobile device settings" we mention in the docs references the [Bluetooth section of the Settings app](https://support.apple.com/en-us/HT204091), that you'd use to connect to e.g. a bluetooth speaker. If you connect to a reader from Settings.app, it will make it unavailable for discovery later.

**Comment by AkshadaKad** [comment]
Okay but I already tapped on pair but it is still connecting and disconnecting. How to handle timeout of device it cant be on always?

**Comment by AkshadaKad** [comment]
Tested again as suggested by you but still its connecting and reconnecting.

**Comment by bric-stripe** [comment]
from looking at logs from that reader serial number I don't see anything unexpected happening. It looks like healthy discover > connect but then a few seconds later there's an explicit request to `Terminal.shared.disconnectReader` being called so the reader disconnects.

can you check on when you call disconnect? could you provide some sample code that you're using or include logs from the log listener https://github.com/stripe/stripe-terminal-ios/issues/126#issuecomment-992539887

**Comment by AkshadaKad** [comment]
But this is particularly happening for reader m2 not for bbpos.

**Comment by AkshadaKad** [comment]
class ReaderConnectionViewController: UITableViewController, BluetoothReaderDelegate, CancelableViewController {
    var cancelButton: UIBarButtonItem?
    
    func reader(_ reader: Reader, didReportAvailableUpdate update: ReaderSoftwareUpdate) {
        //UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Updating bluetooth")
    }
    
    func reader(_ reader: Reader, didStartInstallingUpdate update: ReaderSoftwareUpdate, cancelable: Cancelable?) {
        UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "started installing")
    }
    
    func reader(_ reader: Reader, didReportReaderSoftwareUpdateProgress progress: Float) {
        UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Updating bluetooth in progress")
    }
    
    func reader(_ reader: Reader, didFinishInstallingUpdate update: ReaderSoftwareUpdate?, error: Error?) {
        UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Updating bluetooth finished")
    }
    
    func reader(_ reader: Reader, didRequestReaderInput inputOptions: ReaderInputOptions = []) {
        UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Updating bluetooth")
    }
    
    func reader(_ reader: Reader, didRequestReaderDisplayMessage displayMessage: ReaderDisplayMessage) {
        UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Updating bluetooth")
    }
    
    internal var cancelable: Cancelable?
    private var updateReaderVC: UpdateReaderViewController?
    private var selectedLocation: Location?
    var onConnectedToReader: (Reader) -> Void = { _ in }
    private enum ViewState {
        /// Have not started discovering Readers yet
        case preDiscovery
        /// Actively discovering readers
        case discovering
        /// Actively connecting to a reader
        case connecting
        /// Done actively discovering readers
        case doneDiscovering
    }
    private var viewState = ViewState.preDiscovery
    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView = UITableView(frame: CGRect.zero, style: .grouped)
        
        GCTerminalDelegate.shared.connectionDelegate = self
        BluetoothReaderDelegateAnnouncer.shared.addListener(self)
        self.becomeFirstResponder()
        setUpNavigationBar()
    }
    
    @objc func setUpNavigationBar() {
        let backButton = UIButton(type: .custom)
        backButton.setImage(UIImage(named: "left (1)"), for: .normal)
        backButton.backgroundColor = UIColor.white
        backButton.layer.cornerRadius = 20
        backButton.frame = CGRect(x: 0, y: 0, width: 40, height: 40)
        backButton.addTarget(self, action: #selector(didTapOnBacks(_:)), for: .touchUpInside)
        let backBarButton = UIBarButtonItem(customView: backButton)
        navigationItem.leftBarButtonItem = backBarButton
    }
    
    @IBAction func didTapOnBacks(_ sender: UIButton) {
        navigationController?.popViewController(animated: true)
    }
    
    // MARK: - TableView
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 3
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        switch section {
        case 0:
            return 1
        case 1:
            // How many rows should we show in the "Connection Actions" section?
            // Depends on how many connection actions are available right now,
            // as determined by the GCTerminalDelegate singleton.
            return GCTerminalDelegate.shared.availableConnectionActions.values.reduce(0) { sum, value in
                return sum + (value ? 1 : 0)
            }
        case 2:
            return GCTerminalDelegate.shared.readers.count
        default:
            fatalError()
        }
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        var cell = UITableViewCell()
        cell.selectionStyle = .none
        switch indexPath.section {
        case 0:
            cell.textLabel?.text = GCTerminalDelegate.shared.readerStatusText
            cell.textLabel?.numberOfLines = 0
        case 1:
            let actions = GCTerminalDelegate.shared.availableConnectionActions.compactMap { (action, isAvailable) in
                return isAvailable ? action : nil
            }
            
            switch actions[indexPath.row] {
            case .disconnectAndSearch:
                cell.textLabel?.text = "Disconnect and search..."
            case .forgetLastSeen:
                cell = UITableViewCell(style: .subtitle, reuseIdentifier: nil)
                cell.textLabel?.text = "Forget last seen reader"
                cell.detailTextLabel?.text = UserDefaults.standard.string(forKey: Defaults.terminalLastReaderConnected)
            }
            cell.accessoryType = .disclosureIndicator
        case 2:
            cell.textLabel?.text = GCTerminalDelegate.shared.readers[indexPath.row].serialNumber
            cell.accessoryType = .disclosureIndicator            
        default:
            fatalError()
        }
        
        return cell
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        switch indexPath.section {
        case 1:
            tableView.deselectRow(at: indexPath, animated: true)
            let actions = GCTerminalDelegate.shared.availableConnectionActions.compactMap { (action, isAvailable) in
                return isAvailable ? action : nil
            }
            
            switch actions[indexPath.row] {
            case .disconnectAndSearch:
                GCTerminalDelegate.shared.updateReaderStatusLabel(withText: "Disconnecting...")
                GCTerminalDelegate.shared.safelyPerformDiscovery()
                UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Chippr disconnect and search")
            case .forgetLastSeen:
                UserDefaults.standard.set(nil, forKey: Defaults.terminalLastReaderConnected)
                UserDefaults.standard.set(false, forKey: Defaults.isReaderDeviceTypeP400)
                UserDefaults.standard.synchronize()
                GCTerminalDelegate.shared.availableConnectionActions[.forgetLastSeen] = false
                UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Chipper connected is forgotten)")
                didChangeConnectionData()
            }
        case 2:
            let reader = GCTerminalDelegate.shared.readers[indexPath.row]
//            let connectCompletion: ReaderCompletionBlock = { connectedReader, error in
//                if let connectedReader = connectedReader {
//                    self.cancelable = nil
//                    if let vc = self.updateReaderVC {
//                        vc.dismiss(animated: true) {
//                            self.onConnectedToReader(connectedReader)
//                            GCTerminalDelegate.shared.connectToReader(reader, error)
//                        }
//                    } else {
//                        self.onConnectedToReader(connectedReader)
//                        GCTerminalDelegate.shared.connectToReader(reader, error)
//                    }
//                    return
//                } else if let error = error as NSError?,
//                    error.code == ErrorCode.connectFailedReaderIsInUse.rawValue {
//
//                } else if let error = error {
//                    let showError = {
//
//                        self.viewState = .discovering
////                        self.updateContent()
//                    }
//
//                    // Dismiss the update VC if needed so the error presents correctly
//                    if let vc = self.updateReaderVC {
//                        vc.dismiss(animated: true) {
//                            showError()
//                        }
//                    } else {
//                        showError()
//                    }
//                }
//                self.setAllowedCancelMethods(.all)
//            }
            
//            Terminal.shared.connectReader(reader) { reader, error in
//                GCTerminalDelegate.shared.connectToReader(reader, error)
//            }

            let locationId = UserDefaults.standard.string(forKey: "StripeLocationID")  ?? reader.locationId
            if let presentLocationId = locationId {
                let connectionConfig = BluetoothConnectionConfiguration(locationId: presentLocationId)
                
                Terminal.shared.connectBluetoothReader(reader, delegate: BluetoothReaderDelegateAnnouncer.shared, connectionConfig: connectionConfig) { reader, error in
                    if let reader = reader {
                        
                        
                        UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Chipper connected to bluetooth \(reader)")
                        GCTerminalDelegate.shared.connectToReader(reader, error)
                        self.onConnectedToReader(reader)
                    } else if let error = error {
                        UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Chipper connected to not bluetooth and \(error)")
                    }
                }
            }
            // We don't want users to be able to mash this cell and call
            // connect more than once, so we clear out the list of readers
            // once the user has selected one.
            GCTerminalDelegate.shared.readers = []
            tableView.reloadAsync()
        default:
            return
        }
    }
    
    override func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        switch section {
        case 0:
            return nil
        case 1:
            // This trickery here is just hiding the title if there aren't any
            // available actions.
            let numberOfAvailableActions = GCTerminalDelegate.shared.availableConnectionActions.values.reduce(0) { sum, value in
                return sum + (value ? 1 : 0)
            }
            return numberOfAvailableActions > 0 ? "Connection Actions" : ""
        case 2:
            return !GCTerminalDelegate.shared.readers.isEmpty ? "Select a Reader" : ""
        default:
            return nil  
        }
    }
    
    override func tableView(_ tableView: UITableView, titleForFooterInSection section: Int) -> String? {
        switch section {
        case 2:
            let instruction = appdelegate.discoveryMethod == .internet ? "" : "Bluetooth Proximity filters search results to return the closest available reader. The reader it finds flashes multicolored lights."
            return !GCTerminalDelegate.shared.readers.isEmpty ? instruction : ""
        default:
            return nil
        }
    }
    
    override var canBecomeFirstResponder: Bool {
        get {
            return true
        }
    }
}

protocol ConnectionViewDelegate: class {
    func didChangeConnectionData()
}

extension ReaderConnectionViewController: ConnectionViewDelegate {
    func didChangeConnectionData() {
        tableView.reloadAsync()
    }
}

**Comment by bric-stripe** [comment]
> But this is particularly happening for reader m2 not for bbpos.

I'm not sure how to explain that difference yet. They should indeed act the same.

I don't see anything that's calling Terminal.shared.disconnectReader in that code. To try to make sense of how a disconnect is being called, in Xcode can you setup a symbolic breakpoint: Breakpoints tab > + > New symbolic breakpoint > Symbol: `-[SCPTerminal disconnectReader:]` and then rerun and then check the backtrace of where disconnectReader was hit?

**Comment by bric-stripe** [comment]
👋 clearing out some stale tickets, please re-open with updated details if anything still needed.
