### ISSUE TITLE
Issue when app is killed and reader not found after that.

### ISSUE THREAD

**Issue by AkshadaKad** [stripe/stripe-terminal-ios#130]
We are using stripe terminal 2.4. If I connect the reader and kill the app and if I again comeback on discovery controller it is not showing list of reader. Reader is not getting discovered after killing the app.

**Comment by bric-stripe** [comment]
Could you provide some more details? 

does this happen with both bluetooth discovery methods? or any different behavior between the 
two? If using proximity, is the reader the same distance from the iOS device after the restart? proximity does require the reader to be pretty close to the iOS device before it will report the reader during discovery.

and please provide logging output from a successful discover > connect and then again after the app cold starts and fails to discover.

The Terminal log listener can be setup with:

```
Terminal.setLogListener({ logline in
    print(logline)
})
```

**Comment by bric-stripe** [comment]
closing out old issues but please re-open or file a new request if anything still needed here.
