### ISSUE TITLE
BTFailToStart when discovering readers

### ISSUE THREAD

**Issue by TheRusskiy** [stripe/stripe-terminal-ios#137]
## Summary
When trying to discover readers I am getting:
`bb_error_message=Invalid_CBManagerState__CBManagerStateUnknown bb_error_type=BBDeviceErrorType_BTFailToStart command_in_progress=discoverReaders event=unexpected_state logpoint_level=warning scope=SCPBbposBluetoothScanAdapter sdk_version=2.5.0`
The reader I am testing with is Chipper 2X BT.
I am able to connect to this reader from Android SDK.

## Code to reproduce
I am actually using a React Native integration with it: https://github.com/theopolisme/react-native-stripe-terminal
But this error seems to be coming from iOS SDK.

## iOS version
15.2.1 - iPad Air 4th

## SDK version
2.5.0 (tried 2.4.0 as well)

## Other information
This error seems to be described in BBPOS documentation.
Does it mean it actually tries to connect to the Chipper but errors out?

<img width="601" alt="Screenshot 2022-02-11 at 21 20 58" src="https://user-images.githubusercontent.com/2538374/153638476-6a828405-f451-4f7a-9997-c4f29eaefdd6.png">

I am not able to open the BBPOS documentation since it requires an account and there's no way to create one.

**Comment by bric-stripe** [comment]
👋 could you send over the error code that the SDK is returning? that specific error message pasted should only be showing up in the logs but the SDK should be providing an NSError in the discovery completion block that may help us make more sense of it.

some questions/other things to check:
1. we've seen this in older version of the BBPOS SDK we use internally when Core Bluetooth was initialized very early in app startup, but that should be fixed in 2.4+ (IIRC it was fixed before 2.0 shipped). But in that situation restarting discovery would then work. question: **Do you always get this error even if you restart discovery after it failed once or wait a few seconds before starting discovery?**
1. did the application prompt for Bluetooth permission as expected? that should happen without doing anything and if the app didn't have the permission the error reported back should be `SCPErrorBluetoothAccessDenied`, code 2321. I don't think this is the problem but worth a double check.
1. I realize this isn't helpful for a cross platform app because this is iOS only, but would you mind trying with the discovery method `.bluetoothProximity`? that changes up how the Core Bluetooth initialization happens within the SDK a bit and I'd be curious if that works when `.bluetoothScan` doesn't

**Comment by TheRusskiy** [comment]
@bric-stripe 
The other error message:
error_code=3200 error_domain=com.stripe-terminal event=failCommandWithError_code logpoint_level=info scope=SCPBbposBluetoothScanAdapter sdk_version=2.5.0

1) I don't think anything is happening when I start it the 2nd time, no errors or readers found

```
Stripe trace identifier: discoverReaders!200152645700001644698045910
app_id=com.abc command=discoverReaders discovery_method=Bluetooth_Scan event=discoverReaders_delegate_completion_start logpoint_level=info scope=SCPTerminal sdk_version=2.5.0 time=1644698045910
app_id=com.abc command_in_progress=discoverReaders event=state_change logpoint_level=info scope=SCPTerminal sdk_version=2.5.0 time=1644698045914
app_id=com.abc event=discoverReaders logpoint_level=info scope=SCPBbposBluetoothScanAdapter sdk_version=2.5.0 time=1644698045916 timeout=0
app_id=com.abc event=discoverReaders logpoint_level=info scope=SCPBbposBluetoothScanAdapter sdk_version=2.5.0 time=1644698045917
app_id=com.abc event=startBTScan_scanTimeout logpoint_level=info scope=DP_BBDeviceController sdk_version=2.5.0 time=1644698045919
app_id=com.abc event=requestToken logpoint_level=info scope=SCPConnectionTokenManager sdk_version=2.5.0 time=1644698046160
```
2. Looking at the app permissions Bluetooth is enabled, also I am able to connect to other devices using Bluetooth - receipt printers
3. Something different does happen:
```
Stripe trace identifier: discoverReaders!83075449600001644700372993
app_id=com.abc command=discoverReaders discovery_method=Bluetooth_Proximity event=discoverReaders_delegate_completion_start logpoint_level=info scope=SCPTerminal sdk_version=2.5.0 time=1644700372993
adapter_class=SCPBbposBluetoothProximityAdapter app_id=com.abc event=set_adapter logpoint_level=info scope=SCPTerminal sdk_version=2.5.0 time=1644700373000
app_id=com.abc command_in_progress=discoverReaders event=state_change logpoint_level=info scope=SCPTerminal sdk_version=2.5.0 time=1644700373003
app_id=com.abc event=discoverReaders logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700373004
app_id=com.abc event=discoverReaders logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700373006
app_id=com.abc discovery_status=SCPDiscoveryStatusNoPeripheral event=setDiscoveryStatus logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700373007
app_id=com.abc cb_manager_state=CBManagerStatePoweredOn event=centralManagerDidUpdateState logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700373016
app_id=com.abc event=startBTScan logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700373017
app_id=com.abc event=connectBTWithUUID logpoint_level=info scope=DP_BBDeviceController sdk_version=2.5.0 time=1644700373365
app_id=com.abc discovery_status=SCPDiscoveryStatusConnectingToPeripheral event=setDiscoveryStatus logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700373365
app_id=com.abc event=getApiVersion logpoint_level=info scope=DP_BBDeviceController sdk_version=2.5.0 time=1644700374435
app_id=com.abc event=onBTConnected logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374440
app_id=com.abc event=requestToken logpoint_level=info scope=SCPConnectionTokenManager sdk_version=2.5.0 time=1644700374443
app_id=com.abc event=addOperation logpoint_level=info operation=SCPBbposControlLEDsOp scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374446
app_id=com.abc event=runNextOperation logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374448
app_id=com.abc event=bbpos_op_started logpoint_level=info operation=SCPBbposControlLEDsOp scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374450
app_id=com.abc discovery_status=SCPDiscoveryStatusRequestingLedFlash event=setDiscoveryStatus logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374453
app_id=com.abc event=start logpoint_level=info scope=SCPBbposControlLEDsOp sdk_version=2.5.0 time=1644700374455
app_id=com.abc event=controlLED logpoint_level=info scope=DP_BBDeviceController sdk_version=2.5.0 time=1644700374457
app_id=com.abc event=onReturnControlLEDResult_errorMessage logpoint_level=info scope=SCPBbposControlLEDsOp sdk_version=2.5.0 time=1644700374588
app_id=com.abc event=handleControlLEDResult_errorMessage logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 success=YES time=1644700374593
app_id=com.abc event=getDeviceInfo logpoint_level=info scope=DP_BBDeviceController sdk_version=2.5.0 time=1644700374597
app_id=com.abc discovery_status=SCPDiscoveryStatusRequestingDeviceInfo event=setDiscoveryStatus logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374600
app_id=com.abc event=finish logpoint_level=info scope=SCPBbposControlLEDsOp sdk_version=2.5.0 time=1644700374603
app_id=com.abc event=bbpos_op_completed logpoint_level=info operation=SCPBbposControlLEDsOp scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374605
app_id=com.abc event=runNextOperation logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374608
app_id=com.abc event=getApiVersion logpoint_level=info scope=DP_BBDeviceController sdk_version=2.5.0 time=1644700374889
app_id=com.abc event=onReturnDeviceInfo logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374929
app_id=com.abc event=bbp_updateWithDeviceInfo logpoint_level=info scope=SCPReader sdk_version=2.5.0 time=1644700374934
app_id=com.abc battery_level=100 event=bbp_updateBatteryWithDeviceInfo logpoint_level=info scope=SCPReader sdk_version=2.5.0 time=1644700374938
app_id=com.abc discovery_status=SCPDiscoveryStatusDiscoveredWithInfo event=setDiscoveryStatus logpoint_level=info scope=SCPBbposBluetoothProximityAdapter sdk_version=2.5.0 time=1644700374941
```
unfortunately, no callback with discovered readers is called, the terminal begins flashing with pink-orange-green.

**Comment by bric-stripe** [comment]
thanks for checking on all that.

The proximity behavior looks correct. The reader flashing is expected and all, so let's try to get that fully working first. The behavior where the logs report all that and the reader flashes but it's not reported as discovered is how the SDK would act if the SDK's request for a connection token never succeeded. 

Can you check that the class you're providing in the `+ SCPTerminal setTokenProvider` is correctly handling the requests for `fetchConnectionToken` and calling the provided completion block with a connection token (or error, if needed): https://stripe.dev/stripe-terminal-ios/docs/Protocols/SCPConnectionTokenProvider.html#/c:objc(pl)SCPConnectionTokenProvider(im)fetchConnectionToken: I'm able to reproduce logs and behavior that look exactly the same as you reported when I don't call the completion block so I'm hopeful that's what's going on. This should hopefully also fix up the 2nd bluetooth scan attempt.

I've created an internal task for us to add error reporting/warnings when the connection token requests go unanswered so to improve debugging here.

**Comment by TheRusskiy** [comment]
@bric-stripe thank you, that confirms my suspicion about `fetchConnectionToken` never getting called, I was able to find the bug in the mentioned repo and submitted a fix:
https://github.com/theopolisme/react-native-stripe-terminal/pull/75
