### ISSUE TITLE
`tipUnits` is incorrect value

### ISSUE THREAD

**Issue by RichAppz** [stripe/stripe-terminal-ios#145]
## Summary
The tipping value is not in the response of the `SCPProcessPaymentCompletionBlock` for WisePad3

## Code to reproduce
Reproducible every time I make a payment `Terminal.shared.processPayment`

## iOS version
15.3.1

## Installation method
Cocoapod

## SDK version
v2.7.0

## Other information

This had a tipping unit of 100 and it is not visible.

<img width="1120" alt="Screenshot 2022-04-05 at 09 48 28" src="https://user-images.githubusercontent.com/2961823/161779222-8cda0949-4ad6-48a6-b0dd-09eca292cee1.png">

**Comment by RichAppz** [comment]
This has been a while now, would you be able to provide an update on this issue.

Thanks

**Comment by bric-stripe** [comment]
@RichAppz sorry this has gone without a response. All the fields in the `metadata` of a PaymentIntent are managed by your integration. So `tipUnits` would need to be filled in by your integration. But I just investigated where this should be in the PI and it isn't yet exposed from the SDK in the `SCPPaymentIntent` proper.

Not the friendliest interface but to unblock for now you should be able to get it from the payment intent's `originalJSON` which has the API response and the tipping info should be in `total_details`:

```
(lldb) po processedIntent?.originalJSON["total_details"]
▿ Optional<Any>
  ▿ some : 2 elements
    ▿ 0 : 2 elements
      - key : amount_tip
      - value : 16
    ▿ 1 : 2 elements
      - key : amount_tax
      - value : 0
```

**Comment by bric-stripe** [comment]
👋 I realize this has been a while but wanted to update that `amountDetails` will be provided on `PaymentIntent` in our late January release.
