### ISSUE TITLE
Error messages are not localised

### ISSUE THREAD

**Issue by steemcb-phorest** [stripe/stripe-terminal-ios#146]
## Summary
The error object returned by the Terminal SDK has a localizedDescription method however these messages are not localised to the user's device language. It's also not mentioned in the documentation what languages are supported (if any). 

## Code to reproduce
Not applicable

## iOS version
Not applicable

## Installation method
Not applicable

## SDK version
2.7.0

**Comment by steemcb-phorest** [comment]
Hi, thanks for replying. Would there be any plan to start localising these? Also does the SDK expose the error codes [defined here](https://stripe.com/docs/error-codes) when a payment fails?

**Comment by bric-stripe** [comment]
sorry for the extremely late response here. No short term plans for localizing the errors.

> Also does the SDK expose the error codes [defined here](https://stripe.com/docs/error-codes) when a payment fails?

yep, the [SCPProcessPaymentError](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPProcessPaymentError.html) will have the `declineCode` and the `requestError` of that will have more details in its `userInfo` dictionary. See the keys [here](https://stripe.dev/stripe-terminal-ios/docs/Errors.html#/c:@SCPErrorKeyStripeAPIDeclineCode).
