### ISSUE TITLE
Payments blocked by other processes.

### ISSUE THREAD

**Issue by RichAppz** [stripe/stripe-terminal-ios#147]
## Summary
In our analytics and some reports from customers, we are getting WisePad3 Terminals that are responding with errors during trying to process another action.

We have not been able to replicate the issue ourselves and would like to understand why this is happening, screenshots below of errors.

<img width="682" alt="Screenshot 2022-04-22 at 14 53 15" src="https://user-images.githubusercontent.com/2961823/164730107-96f52633-9291-45e6-8da8-d29c01f10c2d.png">

<img width="699" alt="Screenshot 2022-04-22 at 15 06 49" src="https://user-images.githubusercontent.com/2961823/164730786-0b98a373-24d7-4ee1-bd5d-e9d3c23caf1e.png">

## Code to reproduce

<img width="931" alt="Screenshot 2022-04-22 at 15 07 52" src="https://user-images.githubusercontent.com/2961823/164731034-a54f3b09-1dca-44f3-a6b4-727d2e61f2b6.png">

## iOS version
Various, most in iOS14/15

## Installation method
CocoaPod

## SDK version
2.7.0

## Other comments
We have tried to replicate it, but it is very hard to get into this situation, between 0.4-0.7% of our transactions are seeing this issue. So it needs looking into and if we can resolve it.

**Comment by RichAppz** [comment]
We can't provide `PaymentIntent` as this is the endpoint that is returning an error unless you are suggesting that it would be returned with the error? Would be good to understand.

A secret from our BE systems can be provided after an app update, is this of any use @billsun-stripe

**Comment by jil-stripe** [comment]
Hi @RichAppz - From the error, it looks like your code is calling `retrievePaymentIntent` while a `processPayment` operation is in progress. How do those two areas of your code interact? In general, you'll need to make sure that the processPayment completion handler is called before you call `retrievePaymentIntent`, since most Terminal SDK operations can only happen one-at-a-time. 

If you send over your app's bundle ID, we can look at our internal logging systems and see if we can glean any more information.

**Comment by billfinn-stripe** [comment]
Thanks, @jil-stripe.

@RichAppz wrote:
> We can't provide `PaymentIntent` as this is the endpoint that is returning an error unless you are suggesting that it would be returned with the error? Would be good to understand.

My reading of the screenshot is that you are creating the payment intent via the backend and then attempting to retrieve it via the SDK. I was hoping you could correlate the payment intent ID of a payment intent created by your backend with an instance where it was failed to be retrieved by the SDK due to a "device busy" error.

However, per @jil-stripe's comment, can you send along your app's bundle ID? That could help us narrow in on the cause of this problem.

**Comment by RichAppz** [comment]
@jil-stripe @RichAppz  The app communicates with a blocking screen when passing the payment to the reader (meaning only one request can be made at a time)

We create the Payment Intent via our backend, that is correct, and then we pass that through your `retrievePaymentIntent` endpoint in the SDK. In the app, it is impossible to send multiple requests to start this flow, which is the interesting part; we can not replicate this error.

The bundled for the app is `com.checkfer.opayterminal`

**Comment by RichAppz** [comment]
We have found the issue I think @billfinn-stripe 

Looking at some analytics in more depth:
<img width="971" alt="Screenshot 2022-05-24 at 10 20 26" src="https://user-images.githubusercontent.com/2961823/169997592-1b84b1dd-53b6-47f7-a3f1-2c6e24b38f23.png">

If you look at the process taken here the `reader_connected` came 3 times in very quick succession 
<img width="491" alt="Screenshot 2022-05-24 at 10 21 48" src="https://user-images.githubusercontent.com/2961823/169997874-4c3fd464-2e63-468f-8f9f-d9c2b63d0c33.png">
<img width="518" alt="Screenshot 2022-05-24 at 10 22 05" src="https://user-images.githubusercontent.com/2961823/169997932-3dab3c07-e227-487d-8dcc-41754e73d119.png">
<img width="485" alt="Screenshot 2022-05-24 at 10 22 20" src="https://user-images.githubusercontent.com/2961823/169997978-c294b855-f5a0-48cc-8433-bf6abbcc4c4f.png">


This has caused multiple transaction starts, thus a new payment intent and trying to send to the reader.

We are deploying a fix from our end to check if we already have a connected reader with the same `serialNumber`.

So I think the fix from your end is to not return the same reader in your delegate multiple times:

<img width="574" alt="Screenshot 2022-05-24 at 10 24 29" src="https://user-images.githubusercontent.com/2961823/169998444-7936418f-0642-4bce-919c-35e5534b5814.png">

**Comment by wdragon** [comment]
Subscribe.

Some of our merchants have experienced similar issues. 

![20220524-214759](https://user-images.githubusercontent.com/762808/170181955-b008cfaa-a78c-49fd-ad0a-4ec74e6bab43.jpeg)

**Comment by RichAppz** [comment]
> hi @RichAppz I'm helping out to try to make sense of what's going on here. Can you clarify how that `terminalHandlerConnectedToReader` is wired up/what calls it in your application code?
> 
> the most reliable place would be in the completion block for `connectBluetoothReader` call. You mention a delegate though, can you clarify which delegate method?
> 
> I found our logs reported for the reader that processed the payment intent you included. I see the connect and two retrieve PI calls (one getting hit with BUSY) but I don't see anything that seems unexpected during the connect. But knowing what is driving the calls to the terminalHandlerConnectedToReader should help. Though if it is only the completion block I'm not sure how to explain it yet. If possible, please include a code snippet of any calls to that method.



Sorry was off sick with COVID! @bric-stripe 

Ignore the delegate comment, we have a Terminal Service handling the connection between your SDK and our app. There is a delegate that is fired based on the completion block that you mentioned.

I am assuming now that whether this completion block is reporting multiple times OR our delegate array has a duplicate in it.

But as I am unable to replicate it's hard to comment any further, but I have also identified a duplicate in our delegate!

Cross fingers this is done, shipping fix to see if this error is removed in our analytics.
