### ISSUE TITLE
Unable to reconnect the reader if moved out of range for say 30sec and then back in range

### ISSUE THREAD

**Issue by hanumanAbacus** [stripe/stripe-terminal-ios#149]
Summary

Unable to reconnect in a scenario,  when reader is moved away where it gets disconnected, wait for say 30sec and come back in range

Code to reproduce

// discovery logic
SCPDiscoveryConfiguration *discoveryConfiguration = [[SCPDiscoveryConfiguration alloc] initWithDiscoveryMethod:SCPDiscoveryMethodBluetoothScan simulated:NO];
[SCPTerminal.shared discoverReaders:discoveryConfiguration
delegate:self
completion:^(NSError * _Nullable error) {}

(void)terminal:(SCPTerminal *)terminal didUpdateDiscoveredReaders:(NSArray<SCPReader *> *)readers { }
// when reader in range, not getting called

(void)terminal:(SCPTerminal *)terminal didReportUnexpectedReaderDisconnect:(nonnull SCPReader *)reader {
iOS version

ios14

Installation method

pod

SDK version

2.8.0

Other information

**Comment by bric-stripe** [comment]
Hi, sorry this went without a response. Please re-open if you're still hitting this and can reproduce this with the latest SDK and firmware. Please include a serial number of a device where you hit this problem and rough timing of when it occurred so we can lookup some logs on our side to try to debug. If this is specifically with a reader M2 I'm using [this issue](https://github.com/stripe/stripe-terminal-ios/issues/120) to track it so please add more details over there.
