### ISSUE TITLE
Terminal constructor fails without NSLocationWhenInUseUsageDescription in Info.plist

### ISSUE THREAD

**Issue by mlatham** [stripe/stripe-terminal-ios#15]
If NSLocationWhenInUseUsageDescription is in an Infoplist.strings file, but not explicitly in Info.plist, the SCPTerminal constructor SIGABRTs. Ideally, the constructor could read from Infoplist.strings, so the message to users is localized.

**Comment by bg-stripe** [comment]
Thanks for reporting this issue! We've added it to our backlog (TERMINAL-2965).

For others running into this issue: 
If your app sets the `NSLocationWhenInUseUsageDescription`, `NSBluetoothPeripheralUsageDescription`, and `NSMicrophoneUsageDescription` keys in an `Infoplist.strings` file, note that you'll need to also set these keys in your `Info.plist` file.

For more information on these keys, see: https://stripe.com/docs/terminal/ios#configure-app

**Comment by danj-stripe** [comment]
Hi @mlatham,

Thanks for reporting this. It seemed like a good suggestion, but after looking into it I don't think we want to make any changes here. The purpose of the `SIGABRT` is to help prevent privacy-related App Store rejections. From [an apple employee in 2016](https://forums.developer.apple.com/thread/62229#185237):

> The usage description must still be defined in Info.plist, even if you have localized versions present in InfoPlist.strings.

The Stripe Terminal SDK doesn't directly use this string, we're just checking that it's there to prevent an unexpected rejection, so don't be concerned that it is using the non-localized version.

Thanks!
