### ISSUE TITLE
processPayment doesn't have declineCode for payment failed due to expired card

### ISSUE THREAD

**Issue by hanumanAbacus** [stripe/stripe-terminal-ios#150]
## Summary
[[SCPTerminal shared] processPayment:intent
                              completion:^(SCPPaymentIntent *processIntent, SCPProcessPaymentError *processError) {
-- processError doesn't have **declineCode** if the payment failed due to expired card

## Code to reproduce
Use expired card

<SCPProcessPaymentError: 0x2851ff4c0; code = 9020; message = The Stripe API request failed.; requestId = req_oecxXXXXXXX; requestError = 0x299f56ca0; stripeApiError = Your card's expiration year is invalid.; paymentIntent = (null): 0x0>

## iOS version
ios14

## Installation method
pod

## SDK version
2.8.0

**Comment by bric-stripe** [comment]
@hanumanAbacus For expired cards the `error.requestError` should have more details. The decline code is only filled in if the error code from the Stripe API is a `card_declined` and that will only happen when the card issuer declines the payment. The Stripe API returns an error for an expired card before the information goes to the issuer. 

The `error.requestError.userInfo` will contain the API response details. In that dictionary the `SCPErrorKeyStripeAPIErrorCode` key can be used to check the [error_code](https://stripe.com/docs/error-codes) can be used to see if it was a decline or other error. In the case of an expired card it should be returning `expired_card`, `invalid_expiry_month`, or `invalid_expiry_year` as the code. Sample requestError user info for an expired card error:

```
**(lldb) po (error.requestError as? NSError)?.userInfo**
▿ Optional<Dictionary<String, Any>>
 ▿ some : 8 elements
 ▿ 0 : 2 elements
 - key : "com.stripe-terminal:StripeAPIErrorType"
 - value : card_error
 ▿ 1 : 2 elements
 - key : "com.stripe-terminal:StripeAPIRequestId"
 - value : req_7uN2AprzYsOdk8
 ▿ 2 : 2 elements
 - key : "NSLocalizedDescription"
 - value : Your card's expiration year is invalid.
 ▿ 3 : 2 elements
 - key : "com.stripe-terminal:HttpStatusCode"
 - value : 402
 ▿ 4 : 2 elements
 - key : "com.stripe-terminal:StripeAPIErrorCode"
 - value : invalid_expiry_year
 ▿ 5 : 2 elements
 - key : "com.stripe-terminal:StripeAPIErrorParameter"
 - value : exp_year
 ▿ 6 : 2 elements
 - key : "com.stripe-terminal:Message"
 - value : Your card's expiration year is invalid.
 ▿ 7 : 2 elements
 - key : "com.stripe-terminal:StripeAPIDocUrl"
 - value : https://stripe.com/docs/error-codes/invalid-expiry-year
```
