### ISSUE TITLE
Unable to connect to BBPOS Chipper 2X BT

### ISSUE THREAD

**Issue by auctifera-josed** [stripe/stripe-terminal-ios#158]
## Summary
Unable to connect reader [BBPOS Chipper 2X BT](https://stripe.com/docs/terminal/payments/setup-reader/bbpos-chipper2xbt), we are able to connect to the [Stripe Reader M2](https://stripe.com/docs/terminal/payments/setup-reader/stripe-m2)

We have the same code base from 1 year ago, we were running the SDK 2.6.0, and clients started reporting problems connecting to card readers, we have updated the SDK to the 2.9.1 version and we still have issues connecting, especially with the Chipper reader.

## Code to reproduce
This is the function we use to connect to the reader

```swift
func connect(to selectedReader: Reader, completion: @escaping (_ reader: Reader?, _ error: Error?) -> ()) {
        if !Stripe.shared.ready {
            return
        }
        
        self.readers = []
        
        let params = ListLocationsParameters(limit: 1, endingBefore: nil, startingAfter: nil)
        
        Terminal.shared.listLocations(parameters: params, completion: { locations, hasMore, error  in
            
            if let firstLocation = locations?.first {
                let configuration = BluetoothConnectionConfiguration(locationId: firstLocation.stripeId)

                Terminal.shared.connectBluetoothReader(selectedReader,
                                                       delegate: self,
                                                       connectionConfig: configuration,
                                                       completion: {(reader, error) in
                    if let reader = reader {
                        AppDelegate.setStripeReaderSerialNumber(reader.serialNumber)
                        self.connectionBackgroundDisplayDelegate?.didConnectToReader(reader)
                    }
                    completion(reader, error)
                })
            } else {
                completion(nil, StripeTerminalError.noLocationFound)
            }
        })
        
        
    }
```

## iOS version
iOS 15.5

## Installation method
Cocoapods

## SDK version
2.9.1

## Other information
The issue started happening all of the sudden, no changes were introduced in our POS app.
[Video of the issue](https://drive.google.com/file/d/1tBy-u8ha2fZIeJYQkEvVoQ9X5qrz4pj5/view)

**Comment by bric-stripe** [comment]
Apologies this went without a response. I'm reviewing our issues and trying to clean these up. Is this still an issue you're hitting? Do you have any steps to reliably reproduce it? If still hitting this can you add: serial number from at least one reader that hit this along with rough time, +/- 1 hour? That will help us pull in some reader logs to try to debug with. Or if you have any logs from the Terminal.setLogListener that would also be great, but not necessary.
