### ISSUE TITLE
SCPBatteryStatus not firing when device is put to charging

### ISSUE THREAD

**Issue by oliviupis** [stripe/stripe-terminal-ios#159]
## Summary
if I'm chargin my device(wisepad 3), status is not sent through [-reader:didReportBatteryLevel:status:isCharging:](https://stripe.dev/stripe-terminal-ios/docs/Protocols/SCPBluetoothReaderDelegate.html#/c:objc(pl)SCPBluetoothReaderDelegate(im)reader:didReportBatteryLevel:status:isCharging:). Only batteryLevel is working as is supposed to work. You'll receive charging status only when batteryLevel is charging

## Code to reproduce
Just get the code example(link in summary) from documentation and add a log to see when the event fire. Then connect to your device, put it to charge and leave it, because device need to charge 1% to receive charging state. After that disconnect device from charge port and wait until you lose 1% from battery.

## iOS version
15.5

## Installation method
Podfile

## SDK version
2.9.0

**Comment by bric-stripe** [comment]
👋 sorry this went without a response for so long. I'm not 100% sure if this is the problem but the battery and is charging states only update once every 10 minutes right now and don't auto-update right away when power is supplied/removed[0]. The battery and charging state will also refresh when your application goes to the background and then comes back to the foreground. I just confirmed with the latest SDK that both of those triggers are updating the `isCharging` state as expected 

[0] yet - that is something we plan to add but doesn't currently happen in the SDK

**Comment by bric-stripe** [comment]
closing this out but please re-open with new info if still seeing an issue here
