### ISSUE TITLE
Connecting to a reader from didUpdateDiscoveredReaders puts the SDK in an unrecoverable state

### ISSUE THREAD

**Issue by scalessec** [stripe/stripe-terminal-ios#16]
We found a scenario that causes the SDK to go into an unrecoverable state and therefore requires our app to be force-quit in order to connect to a reader. 

For context, we're currently only using one reader, so we've been calling `connectReader` once a reader is returned in `didUpdateDiscoveredReaders`. 

To reproduce:

1. Move the device out of proximity from the Chipper 2X (~4ft).
2. Invoke `discoverReaders` on the terminal using `.bluetoothProximity` while the device is out of proximity.
3. Wait 4-5 seconds.
4. Move the device next to the Chipper 2X.

Calling `connectReader` in `didUpdateDiscoveredReaders` will then cause the connection to fail with the following error:

`Failed to connect to reader: Error Domain=com.stripe-terminal Code=302 "An incompatible reader was detected, see the docs for a list of supported devices." UserInfo={NSLocalizedDescription=An incompatible reader was detected, see the docs for a list of supported devices., com.stripe-terminal:Message=An incompatible reader was detected, see the docs for a list of supported devices.}`

Canceling the discovery and then attempting to re-discover will consistently fail with the same error. It's worth noting that `didUpdateDiscoveredReaders` is never invoked again and that subsequent errors occur from the `discoverReaders` completion block. At this point the only way the app can connect to a reader is by force-quitting and restarting (thereby creating a new instance of the terminal). 

Also worth noting that this connection failure happens regardless of if `connectReaders` is called on the first or second invocation of `didUpdateDiscoveredReaders`. This error doesn't appear to occur when the device is within proximity when the initial discovery begins.

Workarounds for the moment appear to be:

1. Wrap the `connectReaders` call in `DispatchQueue.main.async { ... }`.
2. Select the reader from a list, even though there's always only one possible reader.

We will likely go with the recommended approach of selecting the reader from the list, but I still think this issue should be fixed considering we couldn't find an obvious way to recover. Thanks!

**Comment by bg-stripe** [comment]
Thanks for the detailed report @scalessec ! We'll look into this and fix it in an upcoming release.
