### ISSUE TITLE
didReportUnexpectedReaderDisconnect not firing

### ISSUE THREAD

**Issue by oliviupis** [stripe/stripe-terminal-ios#160]
## Summary
When I power off the device for testing purpose I don't get any log from my print. 

## Code to reproduce
First, don't forget to implement TerminalDelegate to your class

`  //  MARK: TerminalDelegate
  
  func terminal(_ terminal: Terminal, didReportUnexpectedReaderDisconnect reader: Reader) {
    print("didReportUnexpectedReaderDisconnect")
  }`

## iOS version
15.5

## Installation method
Podfile

## SDK version
2.9.0

**Comment by mkrager-stripe** [comment]
Hi!
Could you provide some more details to help us debug this? We're not seeing any immediate issues with the unexpected disconnect delegate method firing.
We'd like to know:
- Which reader are you connecting to?
- Can you verify that you have set the TerminalDelegate somewhere in your app? Something like: `Terminal.shared.delegate = yourDelegateObject`
- - Could you also verify that any other methods in your TerminalDelegate are firing as expected?
- Any other code snippets related to the delegate that may be relevant.
Thanks!
