### ISSUE TITLE
Could not execute setReaderDisplay because the SDK is busy with another command: setReaderDisplay.)

### ISSUE THREAD

**Issue by nprail** [stripe/stripe-terminal-ios#161]
## Summary
For a long time, our app has been plagued with the error in the title and similar errors. It seems that most API calls will fail if another API call is still in progress. Sometimes, the SDK also seems to freeze up and stop functioning altogether when this error is encountered. 

For example, we found that if we call `setReaderDisplay` or `clearReaderDisplay` too many times quickly, most of the calls fail and the reader's display stops updating. We ended up working around it by creating a queue of calls for updating the display which mostly solved the issue. But we still hit edge cases from time to time. For example, there is a scenario where we are calling `retrievePaymentIntent` while the end-user can still make changes to the cart, which triggers a call to `setReaderDisplay`. 

Is it expected that we should not be able to call APIs simultaneously? 

## iOS version
15.4

## Installation method
CocoaPods

## SDK version
2.10.0

## Other information
Our app is Capacitor based and we use the [capacitor-stripe-terminal](https://github.com/eventOneHQ/capacitor-stripe-terminal) plugin. On Android, we do not run into any of these issues.

Somewhat related to #133.

**Comment by bric-stripe** [comment]
👋 @nprail 

> Is it expected that we should not be able to call APIs simultaneously?

That's correct. The iOS SDK is expected to fail with Busy if another command is running. You'll need to wait for the previous command's completion to be called before the next command can run. This applies to set/clear reader display/all commands. The completion block is the source of truth for when a command has completed and the SDK is ready for another.

> On Android, we do not run into any of these issues.

Unfortunately this is a difference between the iOS and Android SDKs at the moment that we hope to sync up in future breaking changes.

**Comment by nprail** [comment]
@bric-stripe Okay, thanks. Any idea why the SDK stops functioning after receiving the busy error a few times? It doesn't always break but sometimes it will. 

> Unfortunately this is a difference between the iOS and Android SDKs at the moment that we hope to sync up in future breaking changes.
Would such an update make the iOS SDK able to handle simultaneous requests like the Android SDK can or the other way around? Do you have any timeline for such an update? 

Thanks!

**Comment by bric-stripe** [comment]
👋 closing this issue out as the behavior has changed in the latest major release, 3.0.0. The iOS SDK now acts the same as the Android SDK where the SDK will queue up commands and execute them as the previous one finishes. `SCPErrorBusy` has been removed.
