### ISSUE TITLE
discoverReaders After a network loss

### ISSUE THREAD

**Issue by benhill** [stripe/stripe-terminal-ios#162]
Greetings.

I have noticed some behavior whereby I can no longer discover Bluetooth Readers after a lost internet connection is restored...

1. Load Stripe Terminal App
2. Connect to Reader
3. Drop network connection
4. Restore network connection
5. Attempt to run Terminal.shared.discoverReaders

To reconnect to a reader I need to force close the app and reload. 

I've tested this a bunch of times and it seems to be behavior I can replicate pretty easily.

fyi..  I have implemented reachability, so I am capable of invoking code once the network is restored. I've tried several different options (including running Terminal.shared.disconnectReader) but I can't seem to put my app in a state to connect to available BT readers.

Thanks!

**Comment by bric-stripe** [comment]
hey @benhill - some questions to help us debug (following the provided steps didn't reproduce it right away for me):

* what reader type? (chipper? m2? wisepad 3?)/discovery method (you mention Bluetooth, but Bluetooth Scan or Proximity?)
* what version of the SDK are you running with?
* you mention connecting to a reader but never disconnect (though you mention attempting to run disconnect towards the end)...discoverReaders will fail if the SDK is connected to a reader and would call your completion with an AlreadyConnected error. Connection to the reader shouldn't be network dependent so the SDK should stay connected when the network is dropped and then restored.
* can you provide logs from the SDK? if you don't already have one setup, you'll just need to add a Terminal.shared.logListener block and then print the provided strings to the console or wherever appropriate.

**Comment by bric-stripe** [comment]
👋 closing out stale issues but please re-open with the requested info and we can try to help debug.
