### ISSUE TITLE
XCode 14 not building

### ISSUE THREAD

**Issue by mahmoudElfeel67** [stripe/stripe-terminal-ios#163]
## Summary

XCode 14 beta doesnt compile the app because of stripe using stored properties marked with @available
>>Stored properties cannot be marked potentially unavailable with '@available'

## Code to reproduce

`    @available(iOS 13, macCatalyst 14, *)
    lazy var cardScanningView: CardScanningView? = {
        if !STPCardScanner.cardScanningAvailable() {
            return nil  // Don't initialize the scanner
        }
        let scanningView = CardScanningView()
        scanningView.alpha = 0
        scanningView.isHidden = true
        return scanningView
    }()

    `
    
    there is also 3 instances of using @availble with stored properties

## iOS version
16

## Installation method
cocoapods

## SDK version
2.9.1

**Comment by bric-stripe** [comment]
Hi @mahmoudElfeel67, this is an issue in the main Stripe SDK. There's a thread discussing Xcode 14 issues along with a pre-release branch that looks like it should address this: https://github.com/stripe/stripe-ios/issues/1973#issuecomment-1149024546
