### ISSUE TITLE
Swift Package implementation blocked by Info.plist check

### ISSUE THREAD

**Issue by matthewryan** [stripe/stripe-terminal-ios#166]
## Summary
Hi there Stripe team!

I am in the process of moving a large scale Stripe Terminal implementation into a shared Swift Package for internal use. Adding  `stripe-terminal-ios` as a package dependency was fine, but I've discovered that `Terminal` attempts to check for a populated `NSBluetoothPeripheralUsageDescription` in the Info.plist and throws an `abort()` if it's not present in `discoverReaders()`.

Unfortunately one cannot implement an Info.plist for the package. Any client app using this package would of course add the `NSBluetoothPeripheralUsageDescription` key to its Info.plist.

I understand the intent of forcing this value, but it's currently blocking our implementation. **I cannot run any tests with the (otherwise supremely helpful) simulated readers.**

Any ability to override this check and block (when run on Simulator perhaps?) would be greatly appreciated.

Logs emitted by StripeTerminal:

```
2022-07-29 17:29:19.327491+1000 xctest[30133:5220682] [StripeTerminal] t scope=SCPTerminal event=setDelegate logpoint_level=info app_id=com.apple.dt.xctest.tool is_nil=false sdk_version=2.11.0 time=1659079759327
[StripeTerminal] ⚠️  An integration error was detected in your app. You must add the NSBluetoothPeripheralUsageDescription key to your app's Info.plist in order pass validation when submitting your app to the App Store. See https://stripe.com/docs/terminal/ios#config
```

## iOS version
iOS 15.5

## Installation method
SPM

## SDK version
2.11

**Comment by bric-stripe** [comment]
hi @matthewryan thanks for the report. Played around with this a bit to make sense of it and will try to make sure we get something in to support this in to our August release. Need to discuss with others but currently thinking we could at least add a running in test env runtime check for these and not abort if test env.

**Comment by matthewryan** [comment]
That'd be perfect, thanks @bric-stripe

**Comment by matthewryan** [comment]
Just for a bit more clarity here, the SDK doesn't just check for `NSBluetoothPeripheralUsageDescription` in Info.plist... I worked around this yesterday (in a non-optimal way, so a change would still be appreciated) and it appears that Terminal also checks for `UIBackgroundModes`, and `NSLocationWhenInUseUsageDescription` too.

```
[StripeTerminal] ⚠️  An integration error was detected in your app. You must add the NSBluetoothPeripheralUsageDescription key to your app's Info.plist in order pass validation when submitting your app to the App Store. See https://stripe.com/docs/terminal/ios#config

[StripeTerminal] ⚠️  An integration error was detected in your app. You must add the `bluetooth-central` value to the `UIBackgroundModes` (Required background modes) key in your app's Info.plist in order for your app to run in the background and remain connected to the reader. Note that the `UIBackgroundModes` key is an array and not a single string. See https://stripe.com/docs/terminal/ios#config

[StripeTerminal] ⚠️  An integration error was detected in your app. You must add the NSLocationWhenInUseUsageDescription key to your app's Info.plist. Location access is required to use Stripe Terminal. See https://stripe.com/docs/terminal/ios#config

**Comment by bric-stripe** [comment]
understood, the plan is to apply the same thing to all Info.plist checks in the SDK 👍 and remove the entries from our test host application's Info.plist so we can catch it if there's any regressions in the future.

**Comment by matthewryan** [comment]
Thanks!
