### ISSUE TITLE
M2 Readers undiscoverable after disconnects

### ISSUE THREAD

**Issue by ordinaryman09** [stripe/stripe-terminal-ios#167]
## Summary

I'm having issues with M2 keeps getting disconnected, and sometimes it's not discoverable anymore after the disconnect. Even after closing and reopen the app, it's still not discoverable. 
In some cases, I have to restart the iPad, turn on turn off bluetooth, and/or forget the stripe device from the bluetooth. I tried keeping the connection by keep requesting the battery level, not sure if this helps at all. But the main issue is not being able to reconnect easily when it disconnects. 
Also, I have multiple readers and iPads running at the same time, In some instance, the other iPad are able to see the disconnect device from didUpdateDiscoveredReaders. 

## iOS version

15

## Installation method

 Manual

**Comment by bric-stripe** [comment]
Sorry this without a response. There were a couple related issues for this. https://github.com/stripe/stripe-terminal-ios/issues/120#issuecomment-1310624992 is still open and has some more info but I'm hopeful the latest fw updates have improved/solved this a bit but also for this specific case it may have been the 24 hour reset that the device does that was causing problems? If so, the recently added [auto reconnect option for Bluetooth readers](https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=ios&reader-type=bluetooth#2.-automatically-attempt-reconnection) should help with that.
