### ISSUE TITLE
SDK can't detect reader updates on real devices (BBPOS WisePad 3)

### ISSUE THREAD

**Issue by huynvk** [stripe/stripe-terminal-ios#168]
## Summary
We got an issue with the firmware update for BBPOS WisePad 3. The desired behavior is whenever the app connects with a new device, if the device receives a new firmware update, the SDK will trigger an event and our app will display a screen to indicate the firmware update progress.

We tested with the [simulated reader updates](https://stripe.com/docs/terminal/references/testing#simulated-reader-updates) and it worked well. However, we found the app often won’t show the firmware update screen for real devices (most of the time the app won't show the screen for new devices). 

This problem causes a lot of trouble to our users because they only see the app stuck on the connection screen for a long time (15 minutes). Since the firmware update does not frequently happen on one device, we struggle to reproduce/troubleshoot that problem in our lab. We are not sure whether this problem belongs to the device, the firmware, the SDK, or our code.

**Questions:**
1. Do you know why the SDK can’t detect the firmware update event on the real device?
2. Is there any known differences between the simulated reader and the real device which possibly cause the problem?
3. Is there any way we can trigger firmware updates manually on our real device for testing purposes? 

## iOS version
11.0+ (The app supports iOS from 11.0+, we received many error reports from users using different devices)

## Installation method
CocoaPods

## SDK version
2.8.0

## Other information
N/A

**Comment by bric-stripe** [comment]
@huynvk

> Do you know why the SDK can’t detect the firmware update event on the real device?

The SDK should be announcing these updates the same as when using the simulated reader. One gotcha we've seen some apps run in to is the object that was acting as their BluetoothReaderDelegate wasn't being strongly held and so got released. The Terminal SDK has a weak reference to the delegate so if nothing else is holding on to it it will get released and the announcements will get dropped. Do you have any serial numbers from readers that experienced this problem, we can try to find logs and see if anything stands out? 

> Is there any known differences between the simulated reader and the real device which possibly cause the problem?

No expected differences other than on a real reader it will take a bit longer depending on the update.

> Is there any way we can trigger firmware updates manually on our real device for testing purposes?

No, we don't have a great option here right now. For the WisePad 3 though you should be able to setup test locations in different countries. When registering the device to a new country it will start a required update to install the updated config for that region. This isn't a firmware update but uses the same delegate methods to announce it and perform the update.

**Comment by huynvk** [comment]
@bric-stripe Thanks a lot for your response, we will follow your suggestion to troubleshoot the issue and update to this thread.

> Do you have any serial numbers from readers that experienced this problem, we can try to find logs and see if anything stands out?
Sure thing. Can you help with these SN? `WPC323121010599`, `WPC323028002877`

**Comment by bric-stripe** [comment]
@huynvk anything still needed here? Sorry I hadn't gotten back on those two readers but I just checked now and see WPC323028002877 does seem to have successfully updated to the recent firmware update that went out in the last few weeks. I'm trying to clear out stale issues so I'm going to close this but please re-open with any new info if still running in to issues here.
