### ISSUE TITLE
Non-chip card returning incorrect_number error when swiped on WisePOS E

### ISSUE THREAD

**Issue by rscherf** [stripe/stripe-terminal-ios#169]
## Summary
I have a NZ user, with NZ-based Stripe account using my [iOS] app on an Apple Silicon iMac (I've asked them to confirm if the same issue persists on an iPhone). The issue seems to be that the user is expecting these cards to be swipe only (as they do not have a chip in the card), however upon the `POST` logs for `confirmation_method : automatic`:

```
POST /v1/payment_intents/pi_xxxxxxx/confirm
```

```json
{
  "payment_method_data": {
    "type": "card_present",
    "card_present": {
      "type": "encrypted_track_data",
      "read_method": "magnetic_stripe_track2",
      "swipe_reason": "chip_error",
      "track_2": "*******",
      "track_2_ksn": "********************"
    }
  }
}
```

They are receiving the error when automatic confirmation is happening:

```json
{
  "error": {
    "charge": "ch_xxxxxxxx",
    "code": "incorrect_number",
    "doc_url": "https://stripe.com/docs/error-codes/incorrect-number",
    "message": "Your card number is incorrect.",
    "param": "number",
}
```

The error can be seen for: `req_Tyb2PPKz0UGy2S`, `req_wFbLeriz5Ba1Cn`, `req_JNNXLCgs8bITL2`, etc. I can share the Stripe account id privately, if necessary.

* Device: WisePOS E
* Country: NZ
* Card: TSB Bank (non-chip cards)

## Code to reproduce
My integration is the standard Terminal integration, however there is a mixture of Terminal SDK calls at my own backend calls. Without needing to share dozens of lines of code, these are the steps that are taken:

1. Create PaymentIntent (API backend)
2. Retrieve PaymentIntent (Terminal SDK via `retrievePaymentIntent`)
3. Collect PaymentMethod (Terminal SDK via `collectPaymentMethod`)
4. Process PaymentIntent (Terminal SDK via `processPayment`)
5. Capture PaymentIntent (API backend)

## iOS version
15.6

## Installation method
Cocoapods via Stripe's direct beta `podspec` link

## SDK version
Stripe Terminal: v2.10.0-b1

## Other information
As I mentioned, I will update this Issue if using an iPhone somehow fixes the issue for them, however I'm not too hopeful.

**Comment by bric-stripe** [comment]
@rscherf thanks for the detailed report with request id's and all. I'm filing an internal request to get some help with this one, but wanted to acknowledge it's being looked in to.

> I will update this Issue if using an iPhone somehow fixes the issue for them, however I'm not too hopeful

I agree this shouldn't be an issue with the device running the SDK since the WisePOS E will be running all the payments pieces here.

**Comment by bric-stripe** [comment]
@rscherf someone from a payments team looked in to this and found the card year expiration was unexpected: 2049. And the card number had an unknown BIN. The latter being the reason for the incorrect_number error. Do you know if this is this a card that is known to work with Stripe online payments?

**Comment by rscherf** [comment]
@bric-stripe to be honest, I'm not sure. The initial information I received was that it was a TSB Bank card, which I don't really know anything about, unfortunately. And I wasn't present when the merchant collected the card.

She did pass along a few more bits:

* It seems to be every TSB Eftpos card, regardless of device (iPhone, iPad and Mac). She also said TSB are very "old school" — which I'm not sure what that means. Since they aren't debit cards, perhaps that is why the expiration date was unexpected?

**Comment by bric-stripe** [comment]
ah, Terminal SDK only supports co-branded eftpos in AU/NZ and would be processed as a visa or MC depending on the co-branding. It sounds like this card may not be co-branded so isn't yet supported. Slightly more info here: https://support.stripe.com/questions/stripe-terminal-support-for-pin-debit-transactions

**Comment by rscherf** [comment]
Ok, that makes sense. Unless they are co-branded, they cannot be used with Stripe Terminal SDKs. However, is the expectation that this merchant could still charge those non-chip, non-co-branded cards by manually typing in the card number? Or would that yield similar results, since the BIN is unrecognized and the expiration date is (maybe?) not present on the card?

**Comment by bric-stripe** [comment]
> is the expectation that this merchant could still charge those non-chip, non-co-branded cards by manually typing in the card number?

no, I would expect it to also fail assuming it's a debit card and would then require a pin

**Comment by bric-stripe** [comment]
@rscherf I'm closing out old issues but please re-open this if there was still anything else to follow up on.
