### ISSUE TITLE
Collection of payment method before processing issue

### ISSUE THREAD

**Issue by RichAppz** [stripe/stripe-terminal-ios#173]
## Summary
In the recent SDK release 2.13.0 - There should be visibility of the payment method in the payment intent from the `Terminal.shared.collectPaymentMethod` callback.

This is not working in either staging or production environments.

We have tested ApplePay and standard cards with the same result.

## iOS version
iOS 15.4.1

## Installation method
CocoaPods

## SDK version
2.13.0

## Other information

This is an ApplePay attempt, and you can see that the `paymentMethod` is `null`:
<img width="1933" alt="Screenshot 2022-10-05 at 09 32 58" src="https://user-images.githubusercontent.com/2961823/194018603-2a7895b5-67d6-4289-b343-cc760b7903c4.png">

This is a Corp Physical card:
<img width="1102" alt="Screenshot 2022-10-05 at 09 38 44" src="https://user-images.githubusercontent.com/2961823/194018806-35c2d153-d8ee-454f-86d1-16bf6ee3f279.png">

**Comment by RichAppz** [comment]
Interesting so looks like Xcode is getting confused between files, I have managed to get through to it eventually:

<img width="626" alt="Screenshot 2022-10-10 at 11 43 18" src="https://user-images.githubusercontent.com/2961823/194848809-3a67c2e2-a14d-494a-acf5-ae13c4b7b824.png">

I have it now!

Are you able to tell us if the card is a corporate card? I don't see anything in the model

**Comment by RichAppz** [comment]
Ok we have been doing further investigations and there are a couple of pieces missing that we require:

1. If the card is a corporate card or not, if you have this information
2. If you add a tip to the transaction it doesn't seem to be visible in the intent that is returned after receiving the card

`pi_3LrOoEKHV9I0GxFc1P6KVsm8` this staging transaction has a £1.00 and £10.00 tip but the returned value is still only £1.00

<img width="993" alt="Screenshot 2022-10-10 at 17 37 32" src="https://user-images.githubusercontent.com/2961823/194914229-45a99ae4-9b70-4d3b-8755-3d403ae23ad6.png">

**Comment by bric-stripe** [comment]
👋 reviewing issues and have an update on this one:

>> If you add a tip to the transaction it doesn't seem to be visible in the intent that is returned after receiving the card

> That's correct. This will be addressed in a future SDK update, but no specific timeline yet.

I realize this is a bit away but this should be in our January SDK release scheduled for last week of January.

**Comment by bric-stripe** [comment]
Hi, closing out old issues that we missed closing earlier. `intent.amountTip` is now available when using `updatePaymentIntent`.

> If the card is a corporate card or not, if you have this information

we don't have this available
