### ISSUE TITLE
StripeTerminal.h is missing an import of SCPOfflineDetails.h

### ISSUE THREAD

**Issue by Westacular** [stripe/stripe-terminal-ios#176]
## Summary

StripeTerminal.h doesn't import SCPOfflineDetails.h, and as a result, any targets which import StripeTerminal receive a warning `Umbrella header for module 'StripeTerminal' does not include header 'SCPOfflineDetails.h'`

If that target has "treat warnings as errors" enabled, then the warning is promoted to an error and the build fails.

It appears that when SCPOfflineDetails.h was added as a public header in 2.11.0, it was accidentally not added to StripeTerminal.h as well?

## Steps to reproduce

It's not surprising that this issue wasn't caught because Xcode seems to be _very_ aggressive with module caching and generally hides the warning as a result.

Nonetheless, I found a simple way to reproduce the issue:

- Open the Example project in this repo
- Edit the build settings for the Example target to set `SWIFT_TREAT_WARNINGS_AS_ERRORS` to `Yes`
- In `~/Library/Developer/Xcode/DerivedData`, delete both `ModuleCache.noindex` and the folder for this Example project. **Running "Clean Build Folder" in Xcode is not enough clear a previously-successful state, you must delete these folders.**
- Build the Example app

The build will fail:

<img width="449" alt="Screenshot 2022-10-27 at 18 56 21" src="https://user-images.githubusercontent.com/487498/198413259-a592dc0a-e211-4bbb-a0af-282416baeeab.png">

## Installation method

CocoaPods

## SDK version

2.13.0

Based on the git history, I believe this problem is also present in 2.12.0 and 2.11.0

## Other information

Xcode 14.1 RC 2

**Comment by bric-stripe** [comment]
@Westacular thanks for the report! I'm looking to see if we can get this fixed up for our 2.14.0 release scheduled for next week.
