### ISSUE TITLE
[High] discoverReaders because the SDK is busy with another command: discoverReaders

### ISSUE THREAD

**Issue by ManiRelavant** [stripe/stripe-terminal-ios#177]
Hello there!,

Hope you are doing well, 

When we use the second time discoverReadersAction method the error is showing up below like this 

**Could not execute discoverReaders because the SDK is busy with another command: discoverReaders**

```
- (void)discoverReadersAction {
    SCPDiscoveryConfiguration *config = [[SCPDiscoveryConfiguration alloc] initWithDiscoveryMethod:SCPDiscoveryMethodBluetoothScan
                                                                                         simulated:YES];
    self.discoverCancelable = [[SCPTerminal shared] discoverReaders:config
                                                           delegate:self
                                                         completion:^(NSError *error) {
        if (error != nil) {
            NSLog(@"discoverReaders failed: %@", error);
        } else {
            NSLog(@"discoverReaders succeeded");
        }
    }];
}
```

- Development Language: Objective - C
- SCPSDKVersion: = 2.13.0

Please share the update 

![IMG_727DDADF99A5-1](https://user-images.githubusercontent.com/117079259/198988514-83995f27-6aad-47e4-8e35-97e7cd388890.jpeg)

**Comment by bric-stripe** [comment]
the first discoverReaders call must be completely wrapped up before you can start a second.

The source of truth for when another command can be made sent to Terminal is the first discover's completion block. Until that completion block is called any other commands will error with busy.

**Comment by ManiRelavant** [comment]
How do we know when it will completion done on the discoverReaders

@bric-stripe

**Comment by bric-stripe** [comment]
that will be up to your application code to track. The first discoverReaders call will run until it times out (if you pass a timeout to the discovery configuration) or until canceled with the returned cancelable.

**Comment by ManiRelavant** [comment]
Thank you @bric-stripe
