### ISSUE TITLE
2.14.0 No Longer Compiles on Xcode 13.2

### ISSUE THREAD

**Issue by Mordil** [stripe/stripe-terminal-ios#179]
## Summary
We're building with Xcode 13.2.1 (for various reasons) - which limits us to Swift 5.5

When we resolve this library with `upToNextMajor(from: "2.13.0")` this library pulls in `2.14.0` and during compile we get the following error:

```
failed to build module 'StripeTerminal'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.
```

## Installation method
Swift Package Manager

## SDK version
`upToNextMajor(from: "2.13.0")`

**Comment by bric-stripe** [comment]
Thanks for reporting, and apologies for this unexpected error. The [Tap to Pay on iPhone](https://stripe.com/docs/terminal/payments/setup-reader/tap-on-mobile-ios#get-started) support in SDK 2.14 required we add some swift code and build against the iOS 16 SDK with Xcode 14 for the first time in the SDK which explains this and also why we haven't bumped in to this before 😞 

For now, as you may have already done, you'll need to lock to 2.13.* with `upToNextMinor(from: "2.13.0")`

**Comment by Mordil** [comment]
What was the rationale used to determine if this was a minor release vs. a major release?

**Comment by bric-stripe** [comment]
hey, sorry for delay in response. This caught us a bit by surprise this time as it was our first time including any swift code in the SDK. We'll be more aware of this going forward and ideally we only bump this as part of a breaking change or possibly (still being discussed) after Apple has dropped support for submitting builds with the version of Xcode we're locked to.
