### ISSUE TITLE
The locationld parameter to BluetoothConnectionConfigurationis required but was not provided.

### ISSUE THREAD

**Issue by ManiRelavant** [stripe/stripe-terminal-ios#180]
**Summary** 

The discovered list of readers and picked any one reader and called the below function it's shows error on 

> The locationld parameter to BluetoothConnectionConfigurationis required but was not provided.

The Simulated error was not showing only the problem is when connecting the physical device it showing the error

```
- (void)onSelectedReader:(nonnull SCPReader *)selectedReader  {
        SCPBluetoothConnectionConfiguration *connectionConfig = [[SCPBluetoothConnectionConfiguration alloc] initWithLocationId:selectedReader.locationId];
        self.statusLbl.text = [NSString stringWithFormat:@"Connecting to.. = %@", selectedReader.serialNumber];
        [[SCPTerminal shared] connectBluetoothReader:selectedReader
                                            delegate:self
                                    connectionConfig:connectionConfig
                                          completion:^(SCPReader *reader, NSError *error) {
            if (reader != nil) {
                self.connectedNameLbl.text = [NSString stringWithFormat:@"Connected Device = %@", reader.serialNumber];
            } else {
                self.connectedNameLbl.text = [NSString stringWithFormat:@"Disconnected Device = %@", reader.serialNumber];
                NSLog(@"connectReader failed: %@", error.localizedDescription);
                UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"" message:error.localizedDescription
                                                                        preferredStyle:UIAlertControllerStyleAlert];
                UIAlertAction* ok = [UIAlertAction actionWithTitle: @"Ok" style:UIAlertActionStyleDefault handler:^(UIAlertAction * action) { [self dismissViewControllerAnimated:YES completion:nil];
                }];
                [alert addAction: ok];
                [self presentViewController:alert animated:YES completion:nil];
            }
        }];
}
```

**Installation method**
Pods

**CocoaPods**
pod 'StripeTerminal', '~> 2.0'

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/117079259/199381973-9ea88229-9d69-41eb-9a89-57df4adf9f1c.png)

**Comment by bric-stripe** [comment]
The simulated reader comes with a pre-set `reader.locationId`. When connecting to a reader that hasn't been connected to before you must supply the location id of the location to register the reader to. Once a reader has been connected to once and registered to a location its `reader.locationId` will be set. More info available in the docs for locations here https://stripe.com/docs/terminal/fleet/locations and for connecting here https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=ios&reader-type=bluetooth#connect-reader
