### ISSUE TITLE
Could detect device in list but cant connect

### ISSUE THREAD

**Issue by AkshadaKad** [stripe/stripe-terminal-ios#182]
I am facing a stripe bluetooth device connection issue. I can detect the device in the list but upon selection its not connecting. Is there any version update required or firmware update?
I have stripeterminal 2.8 version.

if let presentLocationId = locationId {

                let connectionConfig = BluetoothConnectionConfiguration(locationId: presentLocationId)

                Terminal.shared.connectBluetoothReader(reader, delegate: BluetoothReaderDelegateAnnouncer.shared, connectionConfig: connectionConfig) { reader, error in

                    if let reader = reader {

                        UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Chipper connected to bluetooth \(presentLocationId)")

                        GCTerminalDelegate.shared.connectToReader(reader, error)

                        self.onConnectedToReader(reader)

                        

                    } else if let error = error {

                        //                        UtilityFile.showAlertOnWindow(withTitle: "Bluetooth", message: "Chipper connected to not bluetooth and \(error)")

                    }

                }

            }

**Comment by bric-stripe** [comment]
Hi @AkshadaKad - there was a recently rolled out firmware update for M2 readers that will install during connectBluetoothReader and will take at least 5 minutes to complete before the connectBluetoothReader completion block will be called. Your BluetoothReaderDelegate should be receiving:

[-reader:didStartInstallingUpdate:cancelable:](https://stripe.dev/stripe-terminal-ios/docs/Protocols/SCPBluetoothReaderDelegate.html#/c:objc(pl)SCPBluetoothReaderDelegate(im)reader:didStartInstallingUpdate:cancelable:)

and then progress with

[-reader:didReportReaderSoftwareUpdateProgress:](https://stripe.dev/stripe-terminal-ios/docs/Protocols/SCPBluetoothReaderDelegate.html#/c:objc(pl)SCPBluetoothReaderDelegate(im)reader:didReportReaderSoftwareUpdateProgress:)

only after the required update installs will the connectBluetoothReader call complete. More info on updates: https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=ios&reader-type=bluetooth#update-reader

**Comment by AkshadaKad** [comment]
Hi @bric-stripe, thanks for reply 
M2 requires update right then what about BBPOS Chipper 2X BT? Does it require any update?

**Comment by bric-stripe** [comment]
yes, all readers have had somewhat recent updates so it's likely if you just received one it needs an update. Latest version info for Chipper's is here https://stripe.com/docs/terminal/readers/bbpos-chipper2xbt and M2 is here https://stripe.com/docs/terminal/readers/stripe-m2

**Comment by bric-stripe** [comment]
closing this out but please re-open with more details if you're finding an issue that wasn't required updates.
