### ISSUE TITLE
SCPAppleBuiltInReader bridge protocol doesn't implement ProximityReader VASRequest / VASReadResult...

### ISSUE THREAD

**Issue by maceip** [stripe/stripe-terminal-ios#183]
## Summary

for the apple built in reader (proximityreader), I would like to support [loyalty cards via VAS](https://developer.apple.com/documentation/proximityreader/accepting-loyalty-passes-from-wallet)

But I don't see any of the classes or methods exposed by ProximityReader in your [bridge protocol](https://github.com/stripe/stripe-terminal-ios/blob/745eb2c996d1e66d363c5214b0894f1f7fb7aafd/Example/StripeTerminal.xcframework/ios-arm64/StripeTerminal.framework/Headers/StripeTerminal-Swift.h#L272): e.g., 

https://developer.apple.com/documentation/proximityreader/vasrequest
https://developer.apple.com/documentation/proximityreader/vasreadresult

Is there any plan or timeline for supporting this?

cc @bric-stripe 

## iOS version
15.4+

## SDK version
[v2.14.0](https://github.com/stripe/stripe-terminal-ios/releases/tag/v2.14.0)

**Comment by davidyang-stripe** [comment]
HI @maceip, the Stripe Terminal SDK does not currently support VAS loyalty cards, this includes Tap to Pay on iPhone.

**Comment by maceip** [comment]
Thanks for the quick response @davidyang-stripe. I realize TTPOI just launched but it might make sense to update the docs referencing Terminal to mention gift/loyalty. With that said, are VAS loyalty cards on the roadmap for stripe-terminal-ios? fwiw, the Adyen pos ios sdk supports this at the moment: 

<img width="242" alt="Screen Shot 2022-11-10 at 8 56 58 PM" src="https://user-images.githubusercontent.com/804368/201237906-20fa8141-1280-4c4c-88e4-604e4cc45d9d.png">

**Comment by davidyang-stripe** [comment]
Hey @maceip, we will look into updating the docs and thanks for the feedback!

**Comment by bric-stripe** [comment]
👋 closing out this issue as a feature request. Closed issues labeled `feature` are periodically reviewed to be considered during our planning process.

**Comment by maceip** [comment]
@davidyang-stripe in the interim is it possible to expose the SecureToken (PaymentCardReader.Token) so I can instantiate PaymentCardReader myself and implement the VAS callbacks?

func prepare(using: PaymentCardReader.Token) async throws -> PaymentCardReaderSession
