### ISSUE TITLE
How to cancel payment?

### ISSUE THREAD

**Issue by AkshadaKad** [stripe/stripe-terminal-ios#186]
How to cancel payment before card tap? Please can you suggest delegate?

**Comment by bric-stripe** [comment]
Hi, please refer to the Terminal docs: https://stripe.com/docs/terminal/payments/collect-payment?terminal-sdk-platform=ios#collect-payment

> You can cancel collecting a payment method using the Cancelable object returned by the iOS SDK.

also please refer to https://support.stripe.com/ for general support - the discord chat may be helpful for questions like this. We'd like to keep the github issues focused on bugs/feature requests with the SDK.
