### ISSUE TITLE
StripeTerminal 2.14 and 2.15 prevent use of `po` in `lldb` on Xcode 14.0

### ISSUE THREAD

**Issue by joshheald** [stripe/stripe-terminal-ios#189]
## Summary

When we use `po` to print anything in `lldb` after updating to 2.14, we get errors like the following:

```
error: expression failed to parse:
error: virtual filesystem overlay file '/Users/bric/stripe/terminal/main/build/iphonesimulator/Build/Intermediates.noindex/ArchiveIntermediates/StripeTerminal/IntermediateBuildFilesPath/StripeTerminal.build/Release-iphonesimulator/StripeTerminal.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/bric/stripe/terminal/main/build/iphonesimulator/Build/Intermediates.noindex/ArchiveIntermediates/StripeTerminal/IntermediateBuildFilesPath/StripeTerminal.build/Release-iphonesimulator/StripeTerminal.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

or 

```
warning: Swift error in scratch context: error: failed to load module '{AppName}'
.
Shared Swift state for {AppName} has developed fatal errors and is being discarded.
REPL definitions and persistent names/types will be lost.

error: expression failed to parse:
unknown error
```

Downgrading to StripeTerminal 2.13 or below resolves the issue, as does using Xcode 14.1 or above.

## Code to reproduce

Using Xcode 14.0 to run the sample app, with no changes other than adding a backend URL as per the README.

1. Put a breakpoint anywhere: I used `AppDelegate.application(_:didFinishLaunchingWithOptions:)`
2. In the lldb pane of Xcode, type `po {variable name}`
3. The error above is shown

## iOS version

15.5, 16.0 
Seen in Xcode 14.0, 14.0.1. Does not occur in Xcode 14.1

## Installation method

Cocoapods

## SDK version

3.14 and 2.15 both have the issue. 2.13 and below do not.

## Other information

The more detailed error above suggests that Xcode is looking for a file from bric’s toolchain:
`error: virtual filesystem overlay file *'/Users/bric/stripe/terminal*/main/build/iphonesimulator/[...]/all-product-headers.yaml' not found`

There’s some [background from another library showing a similar issue](https://steipete.com/posts/couldnt-irgen-expression/) and the difficulty of detecting it... which may be helpful for resolving the problem.

**Comment by bric-stripe** [comment]
@joshheald thanks for the report and sorry for the trouble here. We have a fix for this planned for our Dec release tentatively scheduled for the 12th.
