### ISSUE TITLE
Screen locks during reader update

### ISSUE THREAD

**Issue by scottswezey** [stripe/stripe-terminal-ios#19]
The update interface suggests that you should not leave the update screen while the chipper 2x device is being updated, and that you should keep the device powered on and in range.

While this all makes sense, I found that the screen timed out and my device locked itself while installing the update. Should the app should keep the screen on and prevent automatic device locking during the update period? Would you accept a pull request to keep to prevent idle timeouts while an update is being installed?

**Comment by bg-stripe** [comment]
Ah good catch -- we'd love a PR!

Thanks for the feedback :)
