### ISSUE TITLE
Cannot discovery readers again after shortly after canceling the previous discover call 

### ISSUE THREAD

**Issue by iistyler** [stripe/stripe-terminal-ios#190]
## Summary
After making a request to discovery readers, if you await the cancel of that request, then after that completes, make a new request to search for readers, it will fail with: "Could not execute discoverReaders because the SDK is busy with another command: discoverReaders."

## Code to reproduce
```swift
let cancelable = Terminal.shared.discoverReaders(.init(discoveryMethod: .internet, simulated: false), delegate: self) { error in
    guard let error else { print("No error from first discover reader block"); return }
    print(error.localizedDescription)
}
try await cancelable?.cancel()
let secondCancelable = Terminal.shared.discoverReaders(.init(discoveryMethod: .internet, simulated: false), delegate: self) { error in
    guard let error else { print("No error from second discover reader block"); return }
    print(error.localizedDescription)
}
```
The output of which is:
```
No error from first discover reader block
Could not execute discoverReaders because the SDK is busy with another command: discoverReaders.
```

## iOS version
16.1

## Installation method
Cocoapods

## SDK version
2.14.0

**Comment by bric-stripe** [comment]
Hi, unfortunately the way the SDK is currently working is the cancelable will complete before the first discover fully completes. The source of truth for when the another command can run is when the previous command's completion has been called. This is similar to this reported issue: https://github.com/stripe/stripe-terminal-ios/issues/177#issuecomment-1297100944

I understand the confusion and see the pain provided when trying to use await for the cancelable. I'm going to label this as a `feature-request` so it shows up as we review work during planning but can't commit to any timelines.
