### ISSUE TITLE
The event of M2 Reader  was not triggered: didReportBatteryLevel and isCharging changed

### ISSUE THREAD

**Issue by sohumango** [stripe/stripe-terminal-ios#198]
we are creating swiftui app with M2 reader referencing the example code.
with refreshing app by changing app status  foreground-> backgroud-> foreground
the batteryLevel and isCharging status would changed as expected

without refreshing, the batteryLevel and isCharging status would not changed as expected
I think the reason is the following event was not triggered.
```
    func reader(_ reader: Reader, didReportBatteryLevel batteryLevel: Float, status: BatteryStatus, isCharging: Bool) {
        self.isCharging = isCharging
        self.batteryLevel = batteryLevel
        print("@@@ stripe status changed")
    }
```
with my confirming test, I think the example has the same problem.
could you give us some advices about this problem?

**Comment by bric-stripe** [comment]
Hi, there's a little more info on an older issue [here](https://github.com/stripe/stripe-terminal-ios/issues/159#:~:text=I%27m%20not%20100%25%20sure%20if%20this%20is%20the%20problem%20but%20the%20battery%20and%20is%20charging%20states%20only%20update%20once%20every%2010%20minutes%20right%20now%20and%20don%27t%20auto%2Dupdate%20right%20away%20when%20power%20is%20supplied/removed) that I think you may be running in to:

> I'm not 100% sure if this is the problem but the battery and is charging states only update once every 10 minutes right now and don't auto-update right away when power is supplied/removed

the foreground/background forces a refresh as you're seeing. If the app stays in the foreground it should then be refreshing the battery status and is charging once every 10 minutes right now. Even if you change the charging state it won't be discovered until the device state is polled for now.

**Comment by MeteC** [comment]
> Even if you change the charging state it won't be discovered until the device state is polled for now.

Is there a simple way to trigger a device poll that fires the delegate methods? Or do we need to manually check reader.batteryLevel, reader.batteryStatus, etc etc in a separate logic flow? Thanks!

**Comment by bric-stripe** [comment]
> Is there a simple way to trigger a device poll that fires the delegate methods? 

no, there's no exposed method for triggering a refresh of the battery status check.

> Or do we need to manually check reader.batteryLevel, reader.batteryStatus, etc etc in a separate logic flow

The reader properties only update when the SDK internally checks the reader (once every 10 minutes) so manually checking shouldn't provide any different values. The delegate methods will be called when the 10 minute polling happens *if* there was a change to the level or status. If the values are the same the delegate methods are not called.
