### ISSUE TITLE
Location Services requirements with unit tests

### ISSUE THREAD

**Issue by matthewryan** [stripe/stripe-terminal-ios#201]
Hi there Stripe team, Merry Christmas!

We have a lot of automated tests which check our handling of successful and unsuccessful payments through Stripe using the simulated readers.

Up til now we’ve been able to test these in on a fresh iOS Simulator instance in CI (Xcode Cloud in our case) which does not have Location Services permissions enabled. Recently (likely today — so presumably API related) we’re seeing all these tests fail with otherwise unexpected error messages around Location Services access. Specifically we’re connecting to the simulated WisePad 3 “Bluetooth” readers.  

```
SCPError(rawValue: 2200), intent ID: N/A, step: process, error: <SCPProcessPaymentError: 0x6000016d4140; code = 2200; message = Access to location services is currently disabled. Location access is required to connect to a reader and create payments.; paymentIntent = pi_3MHFssDGO95FH5Z41cCKlbqC: 0x600002d23d80>
```

Attempting to set a “Simulated Location” in the Xcode test plan doesn’t seem to have an effect.

I logged a similar issue a while ago around this sort of problem (in a more forceful case) #166 which you were able to resolve. Given we don’t have the ability to approve Location Services permissions (or any other permissions) in a cloud CI environment, are you able to please relax the constraint for requiring Location Services when attempting payments using simulated devices/automated tests?

Thanks!

Matt

### iOS version
iOS 16.0
### Installation method
SPM
### SDK version
2.16.1

**Comment by bric-stripe** [comment]
> Recently (likely today — so presumably API related) we’re seeing all these tests fail with otherwise unexpected error messages around Location Services access 

Weird - I don't yet understand why this would have just started happening. The `SCPErrorLocationServicesDisabled`, error code 2200, is a client side error returned when there's an explicit denial of location services from Core Location.

If the host application doesn't have a "Privacy - Location When In Use Usage Description" my understanding is the `[CLLocationManager authorizationStatus]` will be `kCLAuthorizationStatusNotDetermined`. In that state the SDK will call `requestWhenInUseAuthorization` but that should be a nop in this situation. So after 5s the SDK should time out and allow `processPayment` to proceed. If you're seeing error 2200 CoreLocation  must be returning `kCLAuthorizationStatusDenied` or `kCLAuthorizationStatusRestricted` (or I'm missing something).

If you reset the simulator are you able to reproduce this locally? If so can you check the `[CLLocationManager authorizationStatus]`?

**Comment by matthewryan** [comment]
@bric-stripe you're absolutely correct. Somehow the simulator in question had its Location Services permissions actioned as `.denied` which was blocking this. I've added extra environmental assertions around this case to prevent this state again.

Thanks for the speedy response and explanation. 🙇
