### ISSUE TITLE
In Apple Builtin Reader while doing tap to pay on iPhone instead of save card to show the amount

### ISSUE THREAD

**Issue by ManiRelavant** [stripe/stripe-terminal-ios#203]
Hey there!

We implemented the tap to pay while we using the methods for createSetupIntent intend and collectSetupIntentPaymentMethod 
the iPhone present the card present reader screen showing 
The problem is it shows the save card, but we need to show amount instead of save card.

**Using methods** 

```
SCPSetupIntentParameters *params = [[SCPSetupIntentParameters alloc] initWithCustomer:customerID];
    [[SCPTerminal shared] createSetupIntent:params completion:^(SCPSetupIntent *createResult, NSError *createError) {
        if (createError) {
            [self.activityIndicator hideAnimated:true];
            [self showErrorAlertController: createError.localizedDescription];
        } else {
            [self collectSetupIntent:createResult];
        }
    }];

    [[SCPTerminal shared] collectSetupIntentPaymentMethod:createIntentParam customerConsentCollected:TRUE completion:^(SCPSetupIntent * _Nullable intent, NSError * _Nullable error) {
        if (error) {
            [self didDisconnect];
            [[SCPTerminal shared] cancelSetupIntent:createIntentParam completion:^(SCPSetupIntent * _Nullable intent, NSError * _Nullable cancelError) {
                [self.activityIndicator hideAnimated:true];
                [self showErrorAlertController:@"Cancelled your payment"];
            }];
        }else {
            [self didDisconnect];
            [self confimSetupIntent:intent];
        }
    }];
```
**Actual Output**

![0b671c3f-c3bc-46e4-8213-46513ef53140](https://user-images.githubusercontent.com/117079259/210940957-b54a3c1e-1f9a-4122-b8b1-38a9c1116c89.JPG)

**Expected Output**

![b590fe23-93c0-472d-9402-3c8643d489c0](https://user-images.githubusercontent.com/117079259/210941001-935d6078-5320-4ae2-88e1-da7538b461f9.JPG)

Please share the findings if any updates
Thanks

**Comment by bric-stripe** [comment]
Hi, this is acting as expected. 

> The problem is it shows the save card, but we need to show amount instead of save card.

SetupIntent's don't have an amount associated with them as its for collecting payment information intended to be associated with a customer and used later to collect payments, so the reader doesn't know any amount to show. See https://stripe.com/docs/api/setup_intents

If you're attempting to collect an initial payment and then be able to use that payment method for future payments as well you may be able to use [`setup_future_usage`](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-setup_future_usage) on a PaymentIntent.

**Comment by bric-stripe** [comment]
closing this out but feel free to re-open if the previous comment doesn't address things.
