### ISSUE TITLE
Prevent the customer to add same credit card

### ISSUE THREAD

**Issue by ManiRelavant** [stripe/stripe-terminal-ios#204]
Hello there

We used the stripe terminal SDK we need to fingerprint for the compare and prevent the store a same credit cards

here we are used the createSetupIntent method 
```
SCPSetupIntentParameters *params = [[SCPSetupIntentParameters alloc] initWithCustomer:customerID];    
    [[SCPTerminal shared] createSetupIntent:params completion:^(SCPSetupIntent *createResult, NSError *createError) {
        if (createError) {
            [self.activityIndicator hideAnimated:true];
            [self showErrorAlertController: createError.localizedDescription];
        } else {
            [self collectSetupIntent:createResult];
        }
    }];
```
How we can send extra information (ex: meta data) from SCPSetupIntentParameters?

SDK response not receiving the fingerprint, we will get below the response

```
{
    "client_secret" = "seti_***";
    created = 5467839289;
    customer = "cus_******";
    id = "seti_*****";
    livemode = 0;
    metadata =     {
    };
    object = "setup_intent";
    "payment_method_options" =     {
    };
    "payment_method_types" =     (
        "card_present"
    );
    status = "requires_payment_method";
    usage = "off_session";
}
```
Team can you advise how it's possible to get the fingerprint from the stripe terminal sdk?

Thank you!

**Comment by bric-stripe** [comment]
> How we can send extra information (ex: meta data) from SCPSetupIntentParameters?

The `SCPSetupIntentParameters` is mutable, so you can have:

```
SCPSetupIntentParameters *params = [[SCPSetupIntentParameters alloc] initWithCustomer:customerID];
params.metadata = @{
    @"astring": @"avalue",
};
```

> how it's possible to get the fingerprint from the stripe terminal sdk?

right now this isn't possible with just the SDK and SetupIntents but I'll bring this up with the team as we recently improved this for PaymentIntent's with the ability to get at the payment method details after `collectPaymentMethod...`: Docs https://stripe.com/docs/terminal/payments/collect-payment?terminal-sdk-platform=ios#collect-inspect-payment-method

But for SetupIntent's you'd only have access to the fingerprint after `processSetupIntent`. So after `processSetupIntent` the SetupIntent's paymentMethod will be filled in with the payment method id and if you GET that payment method via the API it would have the fingerprint in `card_present.fingerprint`.

**Comment by ManiRelavant** [comment]
Thank you @bric-stripe
