### ISSUE TITLE
Error code 1920

### ISSUE THREAD

**Issue by sger** [stripe/stripe-terminal-ios#211]
## Summary

Hello,

I'm trying to create a demo with tap to pay but I'm getting the following error my implementation contains the following code:

```swift
  let params = PaymentIntentParameters(amount: 1000, currency: "usd", paymentMethodTypes: ["card_present"], captureMethod: .manual)
        Terminal.shared.createPaymentIntent(params) { createResult, createError in
            if let error = createError {
                print("createPaymentIntent failed: \(error)")
            } else if let paymentIntent = createResult {
                print("createPaymentIntent succeeded \(paymentIntent)")
                Terminal.shared.collectPaymentMethod(paymentIntent) { intent, error in
                    print(error)
                }
            }
        }
```

collectPaymentMethod returns the following error and the intent is the following: 

```
createPaymentIntent succeeded <SCPPaymentIntent: 0x282a76620; amount = 1000; amount_details = <SCPAmountDetails: 0x281b18480; tip = <SCPTip: 0x281b18540; amount = (null)>>; amount_tip = (null); currency = usd; created = 2023-03-20 15:06:21 +0000; charges = (
); metadata = {
}; offline_details = (null); payment_method = (null); statement_descriptor = (null); statement_descriptor_suffix = (null); status = requires_payment_method; stripeId = pi_3MnkHx4u9xLFUgEK0GigYChW>
```

Can you please provide some info about the error code 1920:

```
[StripeTerminal] e scope=SCPTerminal event=collectPaymentMethod logpoint_level=info account=acct_1047yv4u9xLFUgEK app_id=com.demo.ios error=A_required_parameter_was_invalid_or_missing error_code=1920 error_domain=com.stripe-terminal exception=INTEGRATION_ERROR.SCPErrorInvalidRequiredParameter last_request_id=req_ANW2CtidTaqusa reader=tmr_FBUqJAmmsE4aSm sdk_version=2.18.0 time=1679324782137 total_time_ms=134
```

**Comment by bric-stripe** [comment]
Hi, for Tap to Pay this is likely from using an `onBehalfOf` in the `LocalMobileConnectionConfiguration` but not also setting that same value in the `PaymentIntentParameter` `onBehalfOf`. Are you using `onBehalfOf` when connecting? If so the same account needs to be specified for the PaymentIntent as well. This error will be improved in a future release to help clarify this.

**Comment by sger** [comment]
Hello, 

it work by sending nil

**Comment by bric-stripe** [comment]
oh, that's unexpected that it would require it to be explicitly nil'd since that should be the default for both the ConnectionConfiguration and the PaymentIntentParameters. Are you not using onBehalfOf in the LocalMobileConnectionConfiguration when connecting to the reader?

**Comment by marcin-mucha** [comment]
@bric-stripe Hi, I just ran into the same problem and setting `onBehalfOf ` helped, but I hardcoded it with the account id I got from the https://api.stripe.com/v1/payment_intents/pi_3NPlPfECzMAZB5JJ1bCu1AOz endpoint just to check if it works. Where can I get the right account id from at the point of connection to the local reader?

**Comment by bric-stripe** [comment]
> Where can I get the right account id from at the point of connection to the local reader

if you're using on behalf of for the payments for destination charges you need to provide the account id to use from your backend to the client when connecting. So you'll need to know the account your connecting to the reader for before connecting.

**Comment by Benno007** [comment]
> if you're using on behalf of for the payments for destination charges you need to provide the account id to use from your backend to the client when connecting.

Is there a specific reason/documentation why the terminal connection's onBehalfOf needs to match the payment intent's onBehalfOf?

I understand that setting the payment intent onBehalfOf enables the use of destination charges to send the payment to that venue, settles in that venues currency etc.

But what is the benefit of having the reader connection string require onbehalfof? Is it just some requirement of the API, or does it give additional benefits?

**Comment by bric-stripe** [comment]
> Is there a specific reason/documentation why the terminal connection's onBehalfOf needs to match the payment intent's onBehalfOf?

@Benno007 this is because of the terms of service acceptance only happens at connect time and must be accepted by each end merchant account. So the SDK needs that during connect to be able to support that.

closing this issue as I don't believe there's an unresolved problem here but feel free to re-open if I missed something.
