### ISSUE TITLE
Terminal SDK error: 

### ISSUE THREAD

**Issue by jianming** [stripe/stripe-terminal-ios#214]
When the user pays, it will error "Try different payment method".  The user's card is valid and works with other payment processors like Clover or Square. The user tried inserting or tap, but always get this error. 

The issue is random, sometimes it happens to some users.

And we will see these stripe log

<img width="770" alt="Screenshot 2023-04-01 at 11 05 26 PM" src="https://user-images.githubusercontent.com/238326/229334881-1e6a2e70-d779-40d8-ba25-ec6b7d123193.png">

## iOS version
16.1

## Installation method
Pod

## SDK version
2.17.1

Can you share what might be causing this error from the Stripe log?

**Comment by bric-stripe** [comment]
that error from the dashboard indicates that the `collectPaymentMethod` and `processPayment` have already been run for that PaymentIntent and the PaymentIntent is in the requires_capture state and should only happen if a second processPayment call was made for the PaymentIntent id. Can you provide the PaymentIntent id of one that hit this? If so I can look through request logs on the Stripe side to try to help debug.

**Comment by jianming** [comment]
We got these issues reported from one store in the field. And it might not be necessary be related to this log. So the issue is 
1. when user inserts or tap their card the first time, it will fail and show this message. And there is no Stripe server error at all.
2. user's card is fine because the store can manually accept their payment using clover with the same card.
3. when user cancel the order from our machine and next user tried to order, it works fine.
4. it happens from time to time.

Any idea what might be the cause? Hardware issue?

**Comment by bric-stripe** [comment]
> when user inserts or tap their card the first time, it will fail and show this message. And there is no Stripe server error at all.

ack. OK, that sounds like the SDK is returning the "Try different payment method" error during `collectPaymentMethod`, which makes sense.

> Any idea what might be the cause? Hardware issue?

we'd need to get some more logs. Any chance you could log a PaymentIntent ID that this happens to and report that? Or the account ID and a rough time (+/- 5m) when it hit the error could also work for us to narrow down some logging on our side.

**Comment by bric-stripe** [comment]
cleaning up old issues. Please re-open if still running in to an issue here with the SDK including the requested info.
