### ISSUE TITLE
ReconnectionDelegate not found in DelegateAnnouncer class

### ISSUE THREAD

**Issue by Roniy08** [stripe/stripe-terminal-ios#217]
## Summary
'LocalMobileReaderDelegateAnnouncer' cannot be constructed because it has no accessible initializers
Error shows after installing pods

## Code to reproduce
install   pod 'StripeTerminal', '2.0' to reproduce this issue
## iOS version

ios 16.0

## Installation method

cocoapod install 
## Other information

github example working with no any issue the real issue is when we use their files in different project that does not work as we expect
<img width="1173" alt="Screenshot 2023-04-27 at 3 49 36 PM" src="https://user-images.githubusercontent.com/111509471/234834274-957d615d-9edc-4b2d-a11b-3a777147abdc.png">

**Comment by bric-stripe** [comment]
what version did `pod install` report that it was installing? (or what version does Podfile.lock report as locked?). Does `pod update` install a newer version?

If your Podfile mentions `pod 'StripeTerminal', '2.0'` it will install the original 2.0.0 which won't have those newer delegates.

Switch to `pod 'StripeTerminal', '~> 2.0'` and run `pod update` to install the latest version of the 2.x SDK.

**Comment by Roniy08** [comment]
@bric-stripe thanks, this solution worked and i was using specific **pod 'StripeTerminal', '2.0'** so i changed to given suggestion, and now no any error appears
