### ISSUE TITLE
Create location is not working in example

### ISSUE THREAD

**Issue by Roniy08** [stripe/stripe-terminal-ios#219]
## Summary
cannot create location of USD in create location option

## Code to reproduce
start example -> discover Readers -> No location selected  -> create location

## iOS version
iOS 16.2

## Installation method
using pods 

## SDK version
version is 2.19.0

## Other information
cannot create in separate example created from original example.

**Comment by bric-stripe** [comment]
hi, can you provide the error or any more details? This is working for me when using the example app as-is from the repo.

Also this create location path doesn't use anything within the SDK itself so you should be able to debug a little by stepping through the code here: https://github.com/stripe/stripe-terminal-ios/blob/1a232d06/Example/Example/APIClient.swift#L234 which is called from https://github.com/stripe/stripe-terminal-ios/blob/1a232d06/Example/Example/CreateLocationViewController.swift#L150

My guess is there may be a location validation error or an error with the connection token but not sure.

**Comment by Roniy08** [comment]
@bric-stripe  yes, the error is the com.stripe-terminal:Message=Connecting to the reader failed because the app completed fetchConnectionToken with an error.
which is the main thing i stuck on will you give steps to resolve it to get it at least one static address right now to test the reader connection.

**Comment by waqassdsol** [comment]
@Roniy08 did it work ? as i am also stuck on this issue

**Comment by Roniy08** [comment]
@waqassdsol Nope i am searching for an alternate option to solve this issue if possible can you check on ios 16.0 version and Xcode 14.0 version

**Comment by Roniy08** [comment]
@waqassdsol did you find solution for fetchConnectionToken or location_id error ?

**Comment by Roniy08** [comment]
@bric-stripe i did used this code for my side that still shows same error **Error Domain=com.stripe-terminal Code=9050 "Connecting to the reader failed because the app completed fetchConnectionToken with an error." UserInfo={NSLocalizedDescription=Connecting to the reader failed because the app completed fetchConnectionToken with an error.**

does any other changes that I need to pass from app to within this function? i searched every available solution but still this shows same result how can I solve this ASAP

**Comment by Roniy08** [comment]
yes i have used APIClient and i am working on physical reader it is **M2 reader** here is serial number of reader please look into this issue, I am working from India with physical reader and I am using manual one location id of USA and still cannot use this create location id.
Serial number: STRM26146007039
I hope you update soon

**Comment by bric-stripe** [comment]
Hi, confirmed from our logging that the completion block for the connection token provider is being called with a 404: 

> Response status code was unacceptable: 404

please step through the APIClient response lines of code and debug the request between the APIClient and your backend server that its pointing to.

This error should be from the `.validate(200..<300)` in the APIClient which then calls the completion with the error from the network request: https://github.com/stripe/stripe-terminal-ios/blob/1a232d06/Example/Example/APIClient.swift#L46

things to double check:
* is the `baseURLString` correct? 
* does your backend use the same request type as the example? specifically a POST to `/connection_token`?
* check for logs from your backend to help debug...it should be reporting a 404

**Comment by Roniy08** [comment]
@bric-stripe connectReader failed: Error Domain=com.stripe-terminal Code=9020 "No such location: this error shows up after setting the location Id.

**Comment by waqassdsol** [comment]
@Roniy08 if you can setup a stripe backend and can generate a connection token there and by using that API and in particular that fetch token you can get pass this issue.

**Comment by waqassdsol** [comment]
@Roniy08 I did the same, my backend guy provided me with the API and with the help of that i generated a connection token and it worked just fine.

**Comment by Roniy08** [comment]
> @Roniy08 if you can setup a stripe backend and can generate a connection token there and by using that API and in particular that fetch token you can get pass this issue.

i will try that and check it

**Comment by Roniy08** [comment]
@waqassdsol @bric-stripe  I did try the same steps still facing location id, I am working from Asia and I guess the stripe is not supported in my region and it might be the issue of location that we provide at starting of the pair reader to the app, I think that is the problem which takes my current location than provided location id, I am not sure but I am just trying to get the proper error cause.

**Comment by Roniy08** [comment]
resolved by adding stripe id
