### ISSUE TITLE
"Internet connection appears offline" when connecting touchscreen reader

### ISSUE THREAD

**Issue by MeteC** [stripe/stripe-terminal-ios#222]
Hello there, just hoping this is the right channel to come through. 

One of our customers has a repeated issue where they are unable to connect to their WisePOS E reader, with the error message "The Internet connection appears to be offline." coming through in the UI. We forward this on from the Stripe SDK.

Without being able to see any debug logs at this stage, I strongly presume this is the classic NSURLError code -1009, forwarded on from the Stripe SDK. Their WisePOS reader diagnostics screen indicates `DNS resolution = Passed` and `Stripe connectivity = Passed` (so the usual suspects are out), and both the reader and the iOS device are on the same WiFi SSID. 

I've only been able to recreate this issue on my end by literally cutting off network connectivity to the iOS device *after* starting discovery and *before* calling `connectInternetReader()`. So it seems like there's a connection issue on the iOS side, but not one that interferes with the other activity of our app (or, I guess, with `discoverReaders()`)

So I'm sort of coming here from pure stuckness - is this a common issue, are there any other "usual suspect" that we might check in this case? Is there anything that could possibly drive this connectivity error through from the Stripe SDK during the connection flow, that wouldn't likewise cause discovery flow to fail beforehand? 

Thanks for any help!

**Comment by bric-stripe** [comment]
hi, the most common cause for this is the DNS server not resolving local addresses. When the SDK attempts to connect to the reader it communicates with the reader using a hostname that is setup to resolve to the local IP address for the reader. If that DNS request fails the SDK won't be able to connect to the reader. If that's what's going on the easiest fix, if it's only affecting a few devices, is to override the DNS server to cloudflare or google which are known to support local addresses. There's some more info here: https://support.stripe.com/questions/the-stripe-terminal-sdk-is-encountering-dns-errors-when-connecting-to-an-internet-reader

**Comment by MeteC** [comment]
Hey there, thanks a lot! 

We do routinely get our customers to set the DNS server to cloudflare and our support team confirm they have had the customer switch the DNS settings on this one. (Of course, it's possible they just did it wrong, it's hard to know without sitting down with them throughout the whole process. Guess I'll try to ferret more info out of them...)

**Comment by bric-stripe** [comment]
in version [3.1](https://github.com/stripe/stripe-terminal-ios/blob/master/CHANGELOG.md#310-2023-10-10) we removed the reliance on local DNS resolution. That class of connectivity errors for internet readers should no longer be a problem. Please re-open if still running in to issues when using SDK 3.1+.
