### ISSUE TITLE
 Terminal connectReader error in version 2.0.0

### ISSUE THREAD

**Issue by Roniy08** [stripe/stripe-terminal-ios#224]
DiscoveryDelegate inside this extension 

## Summary

error is below 
Value of type 'Terminal' has no member 'connectReader'

## Code to reproduce
       Terminal.shared.connectedReader

## iOS version
16.0 and later

## Installation method
Pods

## SDK version
pod 'StripeTerminal', '~> 2.0'

**Comment by bric-stripe** [comment]
hi, this looks like a build issue that I don't have enough information to help with. I'd recommend double checking the header is correctly imported and confirm in SCPTerminal.h you should see the `connectedReader` readonly property. Are you able to reproduce this using the [Example project](https://github.com/stripe/stripe-terminal-ios/tree/master/Example)?

**Comment by Roniy08** [comment]
> SCPTerminal.h

what about the swift import file which file is needed to import

**Comment by bric-stripe** [comment]
when used with swift via `import StripeTerminal` it import's the umbrella StripeTerminal.h header which imports SCPTerminal.h.

**Comment by Roniy08** [comment]
resolved by de-integrate pods and install pods again version is 2.0.0
