### ISSUE TITLE
Unable to run the example of this SDK

### ISSUE THREAD

**Issue by waqassdsol** [stripe/stripe-terminal-ios#230]
After deploying the backend server on "http://localhost:4567" and then updating the respective URL in the code. When i try to run it, it runs fine but when i try to connect to one of the reader it gives the error stating 
"Connecting to the reader failed because the app completed fetchconnectiontoken with an error"

**Comment by bric-stripe** [comment]
To allow connecting to localhost you'll likely need to add

```

<key>NSAppTransportSecurity</key>
<dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
</dict>
```

to the Info.plist or add an exception for localhost. More info [here](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity?language=objc). Note this will of course only work with the simulator on your machine and shouldn't be included in your real application.
