### ISSUE TITLE
DiscoverReaders doesn't honor timeout when configured for simulated readers

### ISSUE THREAD

**Issue by jasells** [stripe/stripe-terminal-ios#240]
## Summary

DiscoverReaders does not timeout when using Simulated Readers (both bluetooth AND LocalMobile), as described here: #13 

## iOS version

16.2, 16.4 (iOS device sims and iPhone XR)  We normally only use simulated readers on iOS Sim-devices, but I did verify the behavior is the same on real iPhone as well.

## Installation method

Embedded in app-package (.ipa)

## SDK version

v 2.20.0

## Other information

We currently enforce a timeout in application code, which works well enough for us now, but I noticed this while updating our .Net wrapper that supports both Android and iOS.  The Android Terminal SDK does honor this timeout regardless of simulated or real readers.

**Comment by TatsuUkraine** [comment]
https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPDiscoveryConfiguration.html#/c:objc(cs)SCPDiscoveryConfiguration(py)timeout

It seems it's known limitation in iOS SDK
