### ISSUE TITLE
requires_payment_method

### ISSUE THREAD

**Issue by Roniy08** [stripe/stripe-terminal-ios#242]
i am retrieving the payment intent that are created on backend

## Summary
i am retrieving the payment intent that are created on backend and it got received but stuck at **collectionpaymentmethod**
and give this in log 
metadata = {
}; status = requires_payment_method; stripeId = pi_> how can I resolve it if payment intent is valid and why does this payment method error comes up as I confirmed with backend that they had added payment method

## iOS version
16.0

## Installation method
pods

## SDK version
pod 'StripeTerminal', '2.0'

## Other information
I had used  self.collectCancelable = Terminal.shared.collectPaymentMethod(paymentIntent) then calling on Terminal.shared.processPayment(collectPaymentMethodPaymentIntent) on success of collectionpayment method

**Comment by bric-stripe** [comment]
Hi, status of `requires_payment_method` is expected in the post-creation state of a PaymentIntent and not an error. More info [here](https://stripe.com/docs/payments/paymentintents/lifecycle#intent-statuses). Please use the [developer chat](https://stripe.com/go/developer-chat) for integration support issues like this.
