### ISSUE TITLE
Critical app hanging issues are being reported by StripeTerminalSDK.

### ISSUE THREAD

**Issue by IkjotCreates** [stripe/stripe-terminal-ios#243]
## Summary
App has reported multiple hang issues in StripeTerminal SDK.

## Code to reproduce
It might be happening on calling one of these methods - 
1. (void)retrievePaymentIntent:(NSString *)clientSecret
                   completion:(SCPPaymentIntentCompletionBlock)completion
                   NS_SWIFT_NAME(retrievePaymentIntent(clientSecret:completion:))
2. (nullable SCPCancelable *)collectPaymentMethod:(SCPPaymentIntent *)paymentIntent
                                   collectConfig:(nullable SCPCollectConfiguration *)collectConfig
                                      completion:(SCPPaymentIntentCompletionBlock)completion
3. (void)processPayment:(SCPPaymentIntent *)paymentIntent
            completion:(SCPProcessPaymentCompletionBlock)completion NS_SWIFT_NAME(processPayment(_:completion:));

You can find the line of hang in the screenshot attached with this issue.

## iOS version
iOS 16.5 

## Installation method
Cocoa pod install

## SDK version
- StripeTerminal (2.20.0)

## Other information
Will update if I find anything new on this. 

1. 
<img width="1494" alt="Screenshot 2023-06-30 at 13 29 12" src="https://github.com/stripe/stripe-terminal-ios/assets/62429313/d1704b87-c6ab-4f33-ae88-4dd436d73ab0">
2.
<img width="1484" alt="Screenshot 2023-06-30 at 13 29 35" src="https://github.com/stripe/stripe-terminal-ios/assets/62429313/0acf7fe6-2e23-446b-a7ea-182a7b3210c3">
3.
<img width="1483" alt="Screenshot 2023-06-30 at 13 29 45" src="https://github.com/stripe/stripe-terminal-ios/assets/62429313/4d66a069-d704-4ccd-a6f8-49588f09aff1">
4.
<img width="1488" alt="Screenshot 2023-06-30 at 13 30 01" src="https://github.com/stripe/stripe-terminal-ios/assets/62429313/316d5307-3bdc-4946-905b-332ab60a599a">
5.
<img width="1484" alt="Screenshot 2023-06-30 at 13 30 19" src="https://github.com/stripe/stripe-terminal-ios/assets/62429313/afb2ab20-57f4-4ce5-b18e-94ce7584238a">
6.
<img width="1481" alt="Screenshot 2023-06-30 at 13 30 33" src="https://github.com/stripe/stripe-terminal-ios/assets/62429313/a0775273-0182-47c8-b76c-9f07faa80468">
7.
<img width="1485" alt="Screenshot 2023-06-30 at 13 31 07" src="https://github.com/stripe/stripe-terminal-ios/assets/62429313/fc3a7123-8210-4bda-8c4c-2b4bd0abe11a">

**Comment by bric-stripe** [comment]
@IkjotCreates thanks for the detailed report. Please update to >= 2.20.1. This was fixed in a 2.20.1 hotfix.

> Fixes a latent bug where closing and reopening the app several times leads to increased CPU usage.
