### ISSUE TITLE
stop software update process of reader 

### ISSUE THREAD

**Issue by Roniy08** [stripe/stripe-terminal-ios#247]
## Summary
func reader(_ reader: Reader, didStartInstallingUpdate update: ReaderSoftwareUpdate, cancelable: Cancelable?)

## iOS version
16.5.1

## Installation method
pods

## SDK version
2.21.0

## Other information
how can I stop the update process if user don't want to update.

**Comment by bric-stripe** [comment]
Hi @Roniy08 -- please start with emailing [support@stripe.com](mailto:support@stripe.com). If you've found a bug or have a partially working integration, please fill out the issue template to make it easier for us to answer any questions you have.

for this specific question though you can read more in the docs [here](https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=ios&reader-type=bluetooth#update-reader). If the update is starting when you try to connect to the reader that means the version of the software the reader is running mus be required to be installed before it can be used. So canceling the install with the `cancelable` will stop it installing the update but will then fail the connectBluetoothReader command.
