### ISSUE TITLE
Discover apple pay failed using v3.0.0-b7 sdk

### ISSUE THREAD

**Issue by john-chowbus** [stripe/stripe-terminal-ios#251]
## Summary

card reader is not friendly to apple pay and often fail to pay.  Seems discover apple pay card always fails, but visa apple pay card can work.  

can check the video link for detail:  https://www.youtube.com/shorts/1gCDd16nxdY

## iOS version

16+

## Installation method

cocoapods

## SDK version

v3.0.0-b7

## Other information

firmwareVersion: 2.01.00.17-SZZZ_Prod_US_v5-480001

**Comment by bric-stripe** [comment]
Hi, can you confirm this is with a US account and do you have a sample PaymentIntent id to help us investigate?

**Comment by john-chowbus** [comment]
@bric-stripe     `pi_3Nmt0CAPQoqa93xj3qDmXmhK`  or  `pi_3Nmt1yAPQoqa93xj08P90w4q`  ,    there is no  `Terminal.shared.collectPaymentMethod`   callback,   it's wired.

**Comment by john-chowbus** [comment]
hello  @bric-stripe, any update on this,  seems it's weeks.

**Comment by bric-stripe** [comment]
Wanted to follow up and report that although 3.3.0 fixes this issue we're actively working on a 3.3.1 to address a crash connecting to Chippers and M2 readers that are running older configs. We'll post updates in https://github.com/stripe/stripe-terminal-ios/issues/282
