### ISSUE TITLE
Canceling the SDK 

### ISSUE THREAD

**Issue by usaman9040** [stripe/stripe-terminal-ios#253]
## Summary

I have been working on stripe terminal integration with an M2 device.
The thing I found about it is anywhere there are cancellable involved it does not work properly. After every cancellation need to add some second delay in my case is 0.2 and for others, it is between 0.2 to 0.5 seconds. 

- Most probably because of calling callbacks in false order. It triggers a callback before releasing the actual Terminal. SDK needs to rearrange the order of calling the callback and make sure the reader truly canceled that specific command and is available for other users.

## Code to reproduce

cancelable = Terminal.shared.discoverReaders
cancelable = Terminal.shared.collectPaymentMethod

## iOS version

IOS 16

## Installation method

Pod

## SDK version

V3.0.0-b7

**Comment by usaman9040** [comment]
Yes Implementing the the queued here, is solved a lot of issue and take much of developer pain points. As you mentioned queue there are all functions related to this like prioritize one task on other and removing and managing all the tasks are available. 
But If there is some kind of property that indicate that SDK is free or busy that will even help more and share a lot of room for developer to play.

**Comment by bric-stripe** [comment]
Hi, following up here. We implemented the queue in SDK 3.0+ which should help things here. Please re-open though if running in to any problems with that approach.
