### ISSUE TITLE
Unable to discover and connect M2 card reader on 9th, 3rd-generation iPad

### ISSUE THREAD

**Issue by AnshulMindbody** [stripe/stripe-terminal-ios#259]
## Summary
Customer encountered an issue while trying to discover the M2 card reader with a 9th or 3rd-generation iPad using the latest OS. The issue seems specific to the iPad, as we were able to connect using an iPhone without any problems.

## iOS version
16 + 

## SDK version
2.10.0

**Comment by bric-stripe** [comment]
Can you double check the report of a 3rd generation iPad? 3rd generation iPad is very old (2012) and can only run iOS 9 so shouldn't be able to use the Terminal SDK which requires iOS 10+ for <=2.10 and 11+ for 2.14+. But the SDK should be working for 9th generation iPads 👍 

There was at least one fix to installing required updates during connect but no current known issues. I'd recommend updating the SDK to the latest either 2.23.2 or 3.1 to confirm this hasn't already been fixed. If you can provide the serial number and rough timing of when the errors were hit we can try to get more info from the logs with that but I'd recommend updating to the latest SDK to rule that out.

**Comment by AnshulMindbody** [comment]
@bric-stripe, yes, it is confirmed: iPad 9th generation, and the serial number of the M2 reader is **STRM26229006598**

**Comment by bric-stripe** [comment]
9th generation iPad makes sense 👍

I dug through the logs we have from that reader and found an iPad attempting to connect during that time frame and the SDK was returning `SCPErrorBluetoothDisabled`.

It looks like on Oct 8th this was fixed and the iPad was able to connect and collect a payment.

So this looks like an expected error for that situation. I'm going to close this out but re-open if anything else needed and have more info to investigate.
