### ISSUE TITLE
Can't check the connection status of SCPTerminal unless it's already initialized

### ISSUE THREAD

**Issue by jacobrharris** [stripe/stripe-terminal-ios#26]
Our app crashes and gives this error:

> [StripeTerminal] ⚠️  An integration error was detected in your app. You can only set a token provider *before* requesting the shared Terminal instance for the first time. If you are trying to switch accounts in your app, refer to the documentation for the `clearCachedCredentials` method.

We're not trying to switch accounts. We want to re-use the existing `SCPTerminal` connection. The problem is that we have no way of knowing if `SCPTerminal` is already initialized. If we knew that it was already initialized, we wouldn't pass it the token provider.

This is how we start Terminal:
```
- (void)startStripeTerminal {
    self.stripeAPIClient = [[StripeAPIClient alloc] init];
    [SCPTerminal setTokenProvider:self.stripeAPIClient];
    SCPTerminal.shared.delegate = self;
    [self discoverReaders];
}
```
If I call `[self startStripeTerminal]` again, the app crashes with the above message. But I have to call it again because there's no way to check if `SCPTerminal` is already initialized without using `SCPTerminal.shared`, and if it's not initialized, accessing that property causes a crash.

Does that make sense? Am I caught in a chicken-and-the-egg cycle?

**Comment by bg-stripe** [comment]
Hi @jacobrharris ,

We'll try to make the docs here clearer! In your app, you can either:

1. Call `[SCPTerminal setTokenProvider:` earlier, e.g. when your app launches, in your AppDelegate's `didFinishLaunchingWithOptions`.
2. Use `dispatch_once` to make sure `setTokenProvider` is only called once:

```
static dispatch_once_t onceToken;
dispatch_once(&onceToken, ^{
    [SCPTerminal setTokenProvider:self.stripeAPIClient];
});
```

Hope that helps!

Ben

**Comment by jacobrharris** [comment]
That does help. Thanks!

**Comment by jacobrharris** [comment]
@bg-stripe 
Ok, I'm back to thinking that this pattern is problematic. Above, I said we're not trying to switch accounts, but now that's exactly what we need to do. Putting the `+[SCPTerminal setTokenProvider:]` call in the AppDelegate means I can never change the token provider. So I thought about putting the call in our root view controller in `-[UIViewController viewDidAppear:]` and simply calling `[SCPTerminal.shared clearCachedCredentials]` first, but there's the problem again: I can't check to see if I'm already connected before accessing the `.shared` property or the app will crash. I really think there needs to be a way to do this.

**Comment by bg-stripe** [comment]
Hi @jacobrharris ! 

You can't change the `tokenProvider` once you've set it. You should call `Terminal.setTokenProvider` once, and we recommend doing so early on (e.g. in your AppDelegate, when your app launches).

To switch accounts, you'll need to re-configure the same `tokenProvider` reference that you initially passed to the `Terminal` singleton. (e.g., so that it tells your backend to return a different key).

Hope that clears things up! We'll think about how to make the interface and documentation here clearer.

Best,
Ben

**Comment by bg-stripe** [comment]
Another thing to note ([from the docs](https://stripe.github.io/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)clearCachedCredentials))

You should call `clearCachedCredentials` __after__ configuring your `tokenProvider` to return a token for the new account. (Looks like you're calling `clearCachedCredentials` first).



![image](https://user-images.githubusercontent.com/23086960/52439009-6c97df00-2acf-11e9-864f-a9af4ff0743a.png)

**Comment by troypayne** [comment]
@bg-stripe I'm having the same problem. My "StripeAPIClient" requires authentication to access my backend, which occurs after successfully logging in. I also do a check on launch of my application to see if the user is authenticated or not. Authentication is cached. If they aren't, it returns unauthorized. If they are, it returns authorized. As you can imagine, sometimes on launch they'll be unauthorized so the order of operation can get really screwed up without the ability to check if the Terminal.shared is set or not, so that I can properly clear it if it is.

**Comment by troypayne** [comment]
@bg-stripe any update here?

**Comment by bg-stripe** [comment]
@troypayne –  it sounds like you should:

1. Call `setTokenProvider` at launch with your `StripeAPIClient`.
2. Before a user logs in / your API client is authorized, your implementation of `fetchConnectionToken`  can either return an error, or return a dummy connection token.
3. After a user logs in, call `clearCachedCredentials` (this is important if you choose to return a dummy token in 2).

Hope that helps! 

Note that for integration questions like this one, you can always email `support-terminal@stripe.com`, and they'll usually be able to respond much faster.

**Comment by troypayne** [comment]
@bg-stripe this results in a Locations prompt immediately on launch of my app, which is a poor experience. Can this be more contextual and prompt only at the very point it is needed (as suggested by Apple), certainly after there's confirmation of a valid token

**Comment by bg-stripe** [comment]
That's good feedback! We'll think about changing the request location prompt to be more contextual (e.g. when you take your first payment) in the next SDK release.

**Comment by kenny-evitt** [comment]
@bg-stripe Based on some tests, if the initial 'fetch connection token' call fails, trying to access the `shared` terminal singleton will fail (and, at least in my case, cause my app to crash).

(Interestingly, the crash doesn't happen immediately after accessing the singleton. It seems to occur sometime after the fetch-token call fails.)

**Comment by loganthompson** [comment]
> That's good feedback! We'll think about changing the request location prompt to be more contextual (e.g. when you take your first payment) in the next SDK release.

This would be fantastic. The prompt itself is our biggest issue as well, and we would love to see that reconsidered. Thanks!

**Comment by bg-stripe** [comment]
Hey folks! If you've had trouble checking whether a ConnectionToken provider has been set, you can now use the `hasTokenProvider` method, available in rc1. 

https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(cm)hasTokenProvider
