### ISSUE TITLE
Swift version conflict

### ISSUE THREAD

**Issue by ltryee** [stripe/stripe-terminal-ios#263]
```
Failed to build module 'StripeTerminal'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.8.1 (swiftlang-[5.8.0.124](http://5.8.0.124/).5 clang-1[403.0.22.11](http://403.0.22.11/).100)', while this compiler is 'Apple Swift version 5.9 (swiftlang-[5.9.0.128](http://5.9.0.128/).108 clang-1[500.0.40.1](http://500.0.40.1/))'). Please select a toolchain which matches the SDK.
```

## Summary
Swift version conflict

## iOS version
iOS 17.0.1

## Installation method
pod

## SDK version
3.1.0

## Other information
It may be helps to turn on the build setting named `BUILD_LIBRARY_FOR_DISTRIBUTION`

**Comment by bric-stripe** [comment]
I haven't been able to reproduce this myself with 3.1 via cocoapods with a sample project and Xcode 15. It builds and links successfully for both debug and archive builds. Any ideas what you may be doing differently from a stock sample app? Does this reproduce if you clone the repo and attempt to build the Example app? That doesn't use cocoapods but the binary it links against is from the same build output. I'm able to link that project OK with Xcode 15 as well.

I'll double check but the library should be being built with `BUILD_LIBRARY_FOR_DISTRIBUTION` set.

**Comment by ltryee** [comment]
It was our fault. Thanks for replying.
