### ISSUE TITLE
Is the property batteryLevel ever supplied for a reader when it is discovered?

### ISSUE THREAD

**Issue by mikado2005** [stripe/stripe-terminal-ios#265]
## Summary

I never receive any value except nil for batteryLevel in Reader objects passed to terminal(_ terminal: Terminal, didUpdateDiscoveredReaders readers: [Reader]).  I have three models of readers (Chipper, M2, WisePad).  Is this no longer a feature?

**Comment by bric-stripe** [comment]
only the `BluetoothProximity` discovery method provides battery pre-connect. During a Bluetooth scan we don't have that data available to the SDK yet.
