### ISSUE TITLE
Can't archive Terminal to avoid reconnect

### ISSUE THREAD

**Issue by troypayne** [stripe/stripe-terminal-ios#27]
I'm attempting to store the terminal object in NSUserDefaults by archiving and unarchiving, but since it doesn't support the NSCoding protocol, it of course can't be done.

I think this should be supported unless there's another way to keep from having to break a reader connection on a crash

**Comment by troypayne** [comment]
@bg-stripe Re-opening this because I'm getting a lot of complaints from end-users that they have to reconnect often. When app is backgrounded, iOS is killing it probably due to memory pressure for some older iPads. I'm properly preserving state everywhere but can't for this. Possible?

**Comment by danj-stripe** [comment]
Hi @troypayne,

You'll need to re-initialize the SDK and re-discover your reader when recovering from a crash. The bluetooth connection is broken when the app crashes, and the SDK needs to reconnect using the normal code path.

You also should [not archive the Reader](https://stripe.dev/stripe-terminal-ios/docs/Protocols/SCPDiscoveryDelegate.html#/c:objc(pl)SCPDiscoveryDelegate(im)terminal:didUpdateDiscoveredReaders:) objects, but you **can** save the `serialNumber` of the Reader your user is connected to, and auto-connect to the same one when recovering from the crash.

Thanks!
Dan
