### ISSUE TITLE
Stripe Reader M2 not connecting after force disconnecting unless app is restarted

### ISSUE THREAD

**Issue by Malik056** [stripe/stripe-terminal-ios#270]
## Summary
Stripe Reader M2 is not connected again after it is disconnected by turning off the bluetooth of my iPad Air 5th generation (v17.0.3).

## iOS version
Pad Air 5th generation (v17.0.3).

## Installation method
pod 'StripeTerminal', '~> 3.0'

## SDK version
StripeTerminal (3.2.0)

## Other information
The original problem was the reader sometimes goes unresponsive when it is idle i.e. it is connected but still disconnected. it doesn't signal any disconnect callback and still doesn't work when card is swiped. It gives an error like reader is not connected. So, I tried to narrow down and I found out if I disconnect the reader by turning off my bluetooth (and I have build my configuration as `setAutoReconnectOnUnexpectedDisconnect(false).build()`) the reader doesn't connect. The discoverReader method works fine but the connectBluetoothReader method fails with the following error
`Could not connect to the Bluetooth device. Make sure the device is powered on, in range, and not connected to another app or device. If this error continues to occur, you may need to charge the device`

**Comment by bric-stripe** [comment]
Sorry, I missed this. There was a second report of this, https://github.com/stripe/stripe-terminal-ios/issues/276. We're able to reproduce the problem and are working on a fix.
