### ISSUE TITLE
Regression Bluetooth connect reader SDK Version 3.2 from 3.1

### ISSUE THREAD

**Issue by markusramsak** [stripe/stripe-terminal-ios#276]
## Summary
Bluetooth Connection to reader cannot always be established although working in Stripe SDK Version 3.1 - it is broken on 3.2.

## Code to reproduce
1) discover bluetooth reader (= WisePad 3)
2) connect to bluetooth reader
3) turn off bluetooth on smartphone (disconnects bluetooth reader correctly)
4) try to discover bluetooth reader = fails (correctly because bluetooth is turned off)
5) turn on bluetooth on smartphone
6) discover bluetooth reader (again) 
7) NOW: TRY connect to bluetooth reader -> it fails to connect every time now until the App is restarted

## iOS version
17.1

## Installation method
Flutter

## SDK version
3.2

**Comment by bric-stripe** [comment]
thanks for the report. We've been able to reproduce with those steps and are investigating now.

**Comment by bric-stripe** [comment]
We have the fix for this ready. It will be included in a 3.2.1 update which should be released in the next couple weeks.

**Comment by markusramsak** [comment]
I am happy, I could help 👍
