### ISSUE TITLE
Wisepad 3 ignores call to cancelCollectPaymentMethod after pulling the card too early 

### ISSUE THREAD

**Issue by jp7** [stripe/stripe-terminal-ios#279]
## Summary
Calls to cancel the payment are ignored by the device after getting the message `Card removed too early, try again.` 

## Code to reproduce

Using the Stripe Terminal App:

See Video: https://drive.google.com/file/d/1MsbrTeNFcwn08vMWFewOAWdPyIQhP6Xv/view?usp=sharing

Note: My CAD location has tipping enabled and cancelling on the device works as expected

## iOS version
iPad iOS 16.6.1

## Installation method
Ran the example app 

## SDK version
Version on example app - 3.2.1

## Other information
I could not reproduce this issue in our point of sales app which was running SDK beta 9

Logs from example app:

![IMG_0035](https://github.com/stripe/stripe-terminal-ios/assets/3269065/cdbdb264-91f6-4ffb-bda0-860a4ecde690)

**Comment by bric-stripe** [comment]
Hi, thanks for the detailed report and repro steps! We've reproduced and should have a fix for this in our next release scheduled for end of January.
