### ISSUE TITLE
-[SCPTerminal readSource:delegate:completion:] errors and then succeeds

### ISSUE THREAD

**Issue by jacobrharris** [stripe/stripe-terminal-ios#28]
After updating from b5 to b6, `-[SCPTerminal readSource:delegate:completion:]` seems to error at first, and then it succeeds. The calling function does not get called twice. I'm using it like this:

```
- (void)readCardWithoutCharging {
    SCPReadSourceParameters *params = [[SCPReadSourceParameters alloc] init];
    [SCPTerminal.shared readSource:params delegate:self completion:^(SCPCardPresentSource * _Nullable source, NSError * _Nullable error) {
        if (error) {
            NSLog(@"readSource error: %@", error);
        } else {
            NSLog(@"readSource stripeID: %@", source.stripeId);
        }
    }];
}
```

Just wondering if this is a bug in b6 or if I'm doing something wrong here.

I also see that the docs discourage the use of `-[SCPTerminal readSource:delegate:completion:]` in general. I need to be able to send a payment source to our backend. Should I be using `collectPaymentMethod:delegate:completion:` for this, and then simply leave the PaymentIntent unconfirmed?

**Comment by bg-stripe** [comment]
Thanks for reporting this! It definitely sounds like a bug, and we'll be sure to fix it in the next version. 

> I also see that the docs discourage the use of `-[SCPTerminal readSource:delegate:completion:]` in general. I need to be able to send a payment source to our backend. Should I be using `collectPaymentMethod:delegate:completion:` for this, and then simply leave the PaymentIntent unconfirmed?

Are you creating a standard in-person payment, or saving the payment source for reuse online? You should only use `readSource` for the latter use case, as it will be treated as an online transactions, and won't receive all the benefits of in-person card present (like the EMV liability shift).

Hope that answers your question!
Ben

**Comment by pushchris** [comment]
I am also seeing this issue pop up. Every read source gets run twice, would be nice to have a solution!

**Comment by bg-stripe** [comment]
Thanks for flagging this! We'll have a fix in the upcoming release, shipping next week :)

**Comment by danj-stripe** [comment]
This was fixed & shipped in https://github.com/stripe/stripe-terminal-ios/releases/tag/v1.0.0-rc1
