### ISSUE TITLE
Feature Request: Ability to reset an M2 reader to require an update

### ISSUE THREAD

**Issue by jbring17** [stripe/stripe-terminal-ios#288]
## Summary
There is logic in our app that handles updating of readers and it is frustrating that we only get to test it once on a reader and then if we need to test it again we need another reader that needs an update.

## Other information
The ability to reset the reader to require an update. Make the factory reset go back a version or something so that you need to update it. We have used the simulated readers, but those don't always give the real world experience of an actual physical device.

**Comment by matthewryan** [comment]
Hey @jbring17 you should be able to use `SCPSimulatorConfiguration ` and`SCPSimulateReaderUpdate` to manage this.

https://stripe.dev/stripe-terminal-ios/docs/Enums/SCPSimulateReaderUpdate.html

**Comment by xiaoshen-stripe** [comment]
Hi @jbring17 
We built our simulator reader update functionalities for this exact purpose. 
> but those don't always give the real world experience of an actual physical device
Please do let us know what discrepancy you are seeing, and we'll be happy to take a look. 
Closing this for now
