### ISSUE TITLE
This merchant account cannot be used with the built-in card reader as it has been blocked

### ISSUE THREAD

**Issue by AnshulMindbody** [stripe/stripe-terminal-ios#299]
Tap to Pay iOS Connection Error - One of our customers is experiencing an error while connecting: 'This merchant account cannot be used with the built-in card reader as it has been blocked. Contact support for details.' Error code: 3950. Could you assist in unblocking the customer's account?

**Comment by koenpunt** [comment]
FYI: this is an error from Apple; I had this issue with my Apple ID. I e-mailed Apple about this, not getting a reply, but I was unblocked in the 2 days after emailing them.

**Comment by gliu-stripe** [comment]
Hello, are you attempting to use multiple Stripe accounts on the same device? 
Apple restricts devices to using at most 3 unique accounts on a particular device within a rolling 24-hour window ([see our docs](https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=ios&reader-type=tap-to-pay#account-linking-and-apple-terms-and-conditions)). If you attempt to connect to more than 3 in a 24-hour window, connections to subsequent accounts will fail with the error you're encountering, but you should still be able to connect to the initial 3

**Comment by nchaluvadi** [comment]
I am having similar issue too. How to get in touch with apple please?
