### ISSUE TITLE
Does the SDK work in offline mode? (no internet connection)

### ISSUE THREAD

**Issue by georgeSourcetask** [stripe/stripe-terminal-ios#30]
I can't find any relevant information through Stripe Terminal Docs if this is possible or not. I assumed that if I have the option to "Store card for further use" I could just store that and when my internet connection resumes I'll process the payment. 

I'm getting the "The SDK is not connected to the Internet." error almost doing anything through the SDK, even connecting to a reader (assuming I previously fetched a connection token).

My questions are:
- Does the SDK require an active internet connection in order to work?
- If not, how exactly I create a PaymentIntent from a Source?

**Comment by danj-stripe** [comment]
Hi @georgeSourcetask,

The SDK does not work without an active internet connection. We know that offline mode is an important use case for mobile and it's on our roadmap, but it isn't supported today.

Thanks,
Dan
