### ISSUE TITLE
`collectPaymentMethod` crashes randomly

### ISSUE THREAD

**Issue by r2-pro** [stripe/stripe-terminal-ios#308]
## Summary
In May, we have started to observe that `collectPaymentMethod` is producing crashes.
![Screenshot 2024-06-07 at 11 52 41](https://github.com/stripe/stripe-terminal-ios/assets/105044156/178790b3-061e-4c57-82dc-090e8ad0c50f)

## Code to reproduce
Call `- (nullable SCPCancelable *)collectPaymentMethod:(SCPPaymentIntent *)paymentIntent
                                      completion:(SCPPaymentIntentCompletionBlock)completion NS_SWIFT_NAME(collectPaymentMethod(_:completion:));`

The issue is non-deterministic.

## iOS version
Mostly `17.5.1` and `17.4.1` but there are also occurences on `17.3.1`

## Installation method
via Swift Package Manager

## SDK version
`3.5.0`

## Other information
We haven't been changing the card reader integration lately. I wonder if it may be related to card reader firmware update?
We are using only M2 readers.

Any hints how we can get more info for the issue?

**Comment by maxa-stripe** [comment]
@r2-pro Unfortunately I haven't been able to reproduce this crash. Could you share more information on your integration: How do you use `collectPaymentMethod`? What is in your [`SCPCollectConfiguration`](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPCollectConfiguration.html)? Do you happen to have a payment intent ID and/or reader serial number that was affected by this crash?

**Comment by r2-pro** [comment]
We've added more logging to gather data, but for now we stopped receiving crash reports for the issue.
Isn't that related with firmware update schedule?
![Screenshot 2024-06-25 at 11 50 31](https://github.com/stripe/stripe-terminal-ios/assets/105044156/b49d45c7-5f2e-4979-afd4-c3bc4a743e2a)

**Comment by maxa-stripe** [comment]
No, it does not appear that the chart above correlates with recently released software updates. Do you have any further logging to offer @r2-pro? Unfortunately I still haven't been able to reproduce this issue.
