### ISSUE TITLE
Verifone P400 Support

### ISSUE THREAD

**Issue by jbcullis** [stripe/stripe-terminal-ios#31]
** FEATURE REQUEST **
Is it possible to have the iOS SDK also work with the Verifone P400?

**Comment by danj-stripe** [comment]
This is something we're working on, stay tuned!

**Comment by jbcullis** [comment]
@daniel-stripe Excellent!

**Comment by jbcullis** [comment]
One thing that would be nice to resolve is common objects schemas between the two sdk's.
For example, the in JS the prop device_type vs deviceType in iOS and also the lack of a label prop in the iOS sdk.
None of this is major, just niceties for a future update.

**Comment by connerfritz** [comment]
Is there an expected release date for this?

**Comment by devang-wise** [comment]
Any update on this? Or expected release date? 
Do we have any workaround?

**Comment by jbcullis** [comment]
@devang-wise I successfully used a hidden WebView in testing to support both readers from a unified interface but it felt pretty grody so decided to just wait until official support was released through the sdk.

**Comment by bg-stripe** [comment]
@connerfritz @devang-wise @jbcullis 
Please email me! (bg [at] stripe) – we're almost ready to share an early version of this feature, and we'd love to get your early feedback on the beta!  cc @roshan-stripe

**Comment by jil-stripe** [comment]
Support for the Verifone P400 is now available as a public beta in the latest version of the Terminal iOS SDK! Thanks to everyone who requested this.
