### ISSUE TITLE
3.7.0 version cannot be downloaded through XCode Package manager

### ISSUE THREAD

**Issue by ceciliachenguo** [stripe/stripe-terminal-ios#311]
## Summary
3.7.0 version cannot be downloaded through XCode Package manager

## Code to reproduce
No Code.

## iOS version
iOS 15

## Installation method
Swift Package Manager

## SDK version
3.7.0

## Other information
<img width="1141" alt="image" src="https://github.com/stripe/stripe-terminal-ios/assets/121702916/c41161fa-5688-4b30-b6b2-029f688c2607">

**Comment by henryx-stripe** [comment]
Hi @ceciliachenguo, 3.7.0 has not been officially released yet, please continue to use 3.6.0 until it has been released. Thanks!
