### ISSUE TITLE
Terminal.shared.connectBluetoothReader not responding with callback

### ISSUE THREAD

**Issue by gssatya** [stripe/stripe-terminal-ios#313]
## Summary
No callback response with reader info or error from the method **Terminal.shared.connectBluetoothReader**

I am calling the above method in the DiscoveryDelegate method once a reader is successfully discovered. Even though the reader is successfully discovered, I do not get the callback from the connectBluetoothReader method. 

Would be helpful to understand if there is any thread lock on the connectBluetoothReader method. 

## Code to reproduce
<img width="1012" alt="image" src="https://github.com/stripe/stripe-terminal-ios/assets/27970655/e467c360-efd3-4028-94fe-23922b85220d">

## iOS version
**iPad OS 17.5.1**

## Installation method
Cocoapods

## SDK version
Pod version 3.7.0

## Other information
This code was working fine in the production without any issue and stopped working without any changes in the code. Not sure if updating iPad OS version would have caused it.

**Comment by bric-stripe** [comment]
Does this reproduce 100% of the time? Can you share a serial number and rough timing of a reader that's hitting this? Connecting can sometimes take a few minutes if the SDK has to install a required update for the reader. Your delegate would be informed of that. Can you check if that's what's going on? See [update reader docs](https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=ios&reader-type=bluetooth#required-updates).

**Comment by gssatya** [comment]
Yes. You're right. For some reason, the update did not happen in the store. When I connected to my home wifi I could see the logs in the BluetoothReaderDelegate methods to update the software. Post update, it is working fine now. 

Thanks for the info. Appreciate it.
