### ISSUE TITLE
[HELP] A required parameter was invalid or missing. Collecting a PaymentMethod for a Paymentintent 'on_behalf_of' a Connected Account requires providing that Connected Account's ID in 'SCPLocalMobileConnectionConfigu- ration

### ISSUE THREAD

**Issue by Maks273** [stripe/stripe-terminal-ios#314]
I keep getting this error on Terminal.shared.collectPaymentMethod(paymentIntent).
I assume it's API issue. Any suggetions please?
<img width="959" alt="Screenshot 2024-07-18 at 09 43 22" src="https://github.com/user-attachments/assets/ebcece5a-bdda-4b71-9238-ce20e6ceb40d">

**Comment by Maks273** [comment]
Tried the approach from doc https://docs.stripe.com/terminal/features/connect?terminal-sdk-platform=ios#destination-payment-intents but it's not possible to set the values
<img width="1030" alt="Screenshot 2024-07-18 at 10 06 01" src="https://github.com/user-attachments/assets/207674f1-d2c5-4ba6-954f-58e4bbb72014">

**Comment by bric-stripe** [comment]
sorry, that doc has typos 😞 we'll get that fixed up. You just need to set the params on the builder before building. Once built its a read only object. Updated snippet:

```
        let params = try PaymentIntentParametersBuilder(amount: 1000,
                                                    currency: "gbp")
            .setOnBehalfOf("connected account id")
            .setTransferDataDestination("connected account id")
            .setApplicationFeeAmount(200)
            .build()
```

**Comment by bric-stripe** [comment]
the docs snippet has been updated. Re-open if still running in to trouble.
