### ISSUE TITLE
Software caused connection abort since b6 upgrade

### ISSUE THREAD

**Issue by troypayne** [stripe/stripe-terminal-ios#32]
Since upgrading to b6, I've noticed that I receive this error message intermittently "The operation couldn’t be completed. Software caused connection abort", but, on previous version (b5) I do no. Could a change in code from b5 to b6 be directly related to: https://github.com/AFNetworking/AFNetworking/issues/4279

If so, can one of the work-arounds be implemented as it's causing a lot of pain points resulting in a lot of orphan payment intents. For context, I have a hybrid app that has a WKWebView that communicates through a bridge. I connect to the terminal natively, I receive a payment intent secret from the web via bridge and restore it natively, I then process the payment intent natively (collectPaymentMethod then confirmPaymentIntent), then send payment intent id to the web via bridge to capture. I believe during or after successfully processing, this is above error is causing some network hangups causing things happening on the web to fail, such as capturing, resulting to orphans. This context is just meant to help identify the problem and obviously leaves out X factors on why I need to capture on the web. Let's just say for the sake of this ticket, that's not an option, yet.

Thank you!

**Comment by troypayne** [comment]
This issue was found to be completely unrelated to Stripe Terminal SDK. Closing but should be deleted.

**Comment by bg-stripe** [comment]
thanks for following up @troypayne !
