### ISSUE TITLE
3.9.0: connectionStatus and paymentStatus not updated after auto reconnect for mobile readers

### ISSUE THREAD

**Issue by bric-stripe** [stripe/stripe-terminal-ios#325]
## Summary

We've discovered a regression in 3.9 where after auto reconnecting to a mobile reader the SDK will still report the `Terminal.shared.paymentStatus` as `.notReady` and the `Terminal.shared.connectionStatus` as `.connecting`. The reader will continue to work but the connection status and paymentStatus will be out of sync.

We're actively investigating this issue.

## iOS version
all

## Installation method
all

## SDK version
3.9.0

**Comment by vastopa** [comment]
@bric-stripe - is mobile reader referring to just BT readers or also local mobile readers? (ie Tap to Pay on iPhone)
