### ISSUE TITLE
Reader connection error: Missing input parameters - `SignedTermPubKey`

### ISSUE THREAD

**Issue by r2-pro** [stripe/stripe-terminal-ios#326]
## Summary
When we call SDK to connect to a reader via
```
- (void)connectBluetoothReader:(SCPReader *)reader
                      delegate:(id<SCPBluetoothReaderDelegate>)delegate
              connectionConfig:(SCPBluetoothConnectionConfiguration *)connectionConfig
                    completion:(SCPReaderCompletionBlock)completion NS_SWIFT_NAME(connectBluetoothReader(_:delegate:connectionConfig:completion:));
```

we receive error:

<img width="1013" alt="Screenshot 2024-09-04 at 08 59 52" src="https://github.com/user-attachments/assets/757a222c-f7b8-459c-a302-dcaa2a9f5a21">

Observed only on a specific reader with serial number `CHB20-100015604`.

## Code to reproduce
Call the `connect` method.

## iOS version
iPhone 14 Plus:`17.5.1`, `17.6.1`

## Installation method
SPM

## SDK version
3.5.0

## Other information
Reader object:

```
<SCPReader: 0x107b30120; deviceSoftwareVersion = (null); deviceType = bbpos_chipper2x; label = (null); serialNumber = CHB20-100015604; stripeId = (null); hardwareInfo = (null); batteryLevel = (null); location = <redacted>>
```

---

In the similar scenario, on a different reader, we receive different error:
reader serial: `CHB222047012393`
error: 
<img width="1067" alt="Screenshot 2024-09-04 at 09 11 13" src="https://github.com/user-attachments/assets/1a160449-7e48-43f5-8c13-81451140a961">

---

Bonus question:
Is there a way in the console to check events that are happening on a reader, like connection, updates, payment collection, some kind of "All Activity" timeline that we can see on payment intents?

**Comment by r2-pro** [comment]
@bric-stripe, @mindy-stripe any hints/ideas on that one?

**Comment by dmatthews-stripe** [comment]
@r2-pro are you able to reproduce this issue with the latest version of the SDK?

**Comment by r2-pro** [comment]
No. In general it has been observed only for particular (few) users, I wondered if maybe you have more insights in that update process logs.

**Comment by dmatthews-stripe** [comment]
Hi @r2-pro can you please log a ticket with support as this may be a possible device issue?

**Comment by dmatthews-stripe** [comment]
Hi @r2-pro , we are going to close this ticket. You can file a ticket with our support team for assistance.
