### ISSUE TITLE
Tap to Pay Germany Location returns error from SDK

### ISSUE THREAD

**Issue by BradDoddsProjects** [stripe/stripe-terminal-ios#328]
## Summary
I noticed stripe has released Germany in Beta for iPhone.
https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay

When I create a locationID in the Germany (DE) region it returns valid but when I try to connect via location id, I am presented with the error message below.

**Error Message from sdk:**

>  The Tap to Pay reader is not supported in Germany (DE) as determined by the Location this reader is registered to, tml_Fwv9gyh4UXr3r6. For more information about which countries each Terminal reader may be used in, see https://stripe.com/docs/terminal/choosing-reader-and-sdk#availability.

## Code to reproduce
```
 let connectionConfig = try LocalMobileConnectionConfigurationBuilder.init(locationId: locationId).build()
                    Terminal.shared.connectLocalMobileReader(selectedReader, delegate: self, connectionConfig: connectionConfig) { reader, error in
                        if let reader = reader {
                            print("Successfully connected to reader: \(reader)")
                            self.connectionSuccess()
                        } else if let error = error {
                            print("connectLocalMobileReader failed: \(error)")
                            DispatchQueue.main.async {
                                self.connectionFailureAlert(message: error.localizedDescription)
                            }
                        }
                    }
```

## iOS version
17.4 

## Installation method
pod file
pod 'StripeTerminal', '~> 3.0'

## SDK version
3.9.1

## Other information

Im not sure if this has to do with the stripe documents just releasing the "Germany beta" and the latest version 3.9.1 has just not accounted for it yet. Should we anticipate a new update for this or am I missing something?

**Comment by henryx-stripe** [comment]
Hi, thank you for raising this issue. There was a delay, but it should be enabled now, please try connecting again. Thanks!

**Comment by BradDoddsProjects** [comment]
@henryx-stripe Good to go on my end. SDK has recognized the locationID in the Germany (DE) region and connected successfully.
