### ISSUE TITLE
Stripe SDK 3.8.0 - Deadlock and Crash Issues with Thread Handling in StripeTerminal Logging and GC Scheduler

### ISSUE THREAD

**Issue by AnshulMindbody** [stripe/stripe-terminal-ios#329]
Description
We’re encountering few crashes in the Stripe SDK version 3.8.0 when using the StripeTerminal module. The issue appears to be related to thread management, involving lock mechanisms in pthread_mutex_lock and _dispatch_sync_f_slow functions. This bug disrupts our application flow and is challenging to reproduce consistently but frequently occurs under certain conditions.

<img width="779" alt="Screenshot 2024-10-17 at 10 31 08 PM" src="https://github.com/user-attachments/assets/13cbe617-4a8a-4397-9756-91c3baf351bb">
<img width="825" alt="Screenshot 2024-10-17 at 10 31 03 PM" src="https://github.com/user-attachments/assets/4e0382a9-25fe-449d-972f-9ecc8207abec">

**Comment by bric-stripe** [comment]
Hi, this was fixed in 3.8.3: https://github.com/stripe/stripe-terminal-ios/issues/317
