### ISSUE TITLE
Is it possible to downgrade the BBPOS Chipper 2X BT software for testing?

### ISSUE THREAD

**Issue by jacobrharris** [stripe/stripe-terminal-ios#33]
I need to test our BBPOS software update implementation. But it seems that once you update, you can't go back down to a lower version and run the update again. Is that the case?

**Comment by bg-stripe** [comment]
Hi @jacobrharris –

Sorry for the late reply! We don't allow downgrading your readers for testing, but you can test the software update process by connecting to the reader simulator in your app. We also have an update reader workflow in our example that you can refer to. 

Hope that helps!
