### ISSUE TITLE
Tipping feature

### ISSUE THREAD

**Issue by RicardoE105** [stripe/stripe-terminal-ios#34]
Hey guys, any news on supporting tipping when capturing a payment intent?

**Comment by ericvicenti** [comment]
Why can't you just capture a higher amount, based on how much your user wants to tip?

Personally I actually *like* the fact that the Stripe Terminal API focuses on the reader and accepting payments. Square Reader supports tipping but you cannot customize the UI and it really just gets in the way.

Great work, Stripe team! (don't bother to implement tipping!)

**Comment by RicardoE105** [comment]
Hey @ericvicenti I believe people are used to tipping after swiping/scanning the card. Either way, the last version on the example app on test flight includes the tipping features so that they might be releasing the code in there really soon.

**Comment by ericvicenti** [comment]
Oh, nice! Agree that there should be some way to adjust the transaction amount after the swipe/scan.. this is something I had been asking about.

In my use case, I want customers to be able to insert their card once, then we identify them and allow them to re-order their favorite product, and then we'd perform the transaction. So we'd need to change the amount of the payment intent before taking the money.

Hope the new feature works for tipping as well as this case!

**Comment by bg-stripe** [comment]
Hey folks! Sorry for the delayed response – you're correct that we'll be adding a tipping feature in the next release, which will be coming soon (within the next month). Tipping will be collected after presenting a card, but before the payment is processed. Capturing a higher amount isn't currently supported – if you're specifically interested in that use case, we'd be interested in hearing more! Please email `support-terminal@stripe.com` explaining your use case.

**Comment by BeachyAdam** [comment]
@bg-stripe Any update on when this functionality will be released?

**Comment by bg-stripe** [comment]
Hi again! Sorry about the delayed response here.

We don't have immediate plans to support this in the Terminal SDK right now (tipping means a lot of things to different users, and we're thinking about a good long-term solution that will work for all integration types).

However, you can still implement tipping functionality on your end. Anytime before calling `processPayment` in your app, you can [update the amount of the PaymentIntent](https://stripe.com/docs/api/payment_intents/update#update_payment_intent-amount). Note that you must update the PaymentIntent amount via your backend (similar to capturing the PaymentIntent). As an alternative, you can also collect the tip amount before starting your checkout flow, and simply create the PaymentIntent with the full amount including tip.

We're happy to help out if you have any questions about implementing this alternative flow.

Best,
Ben

**Comment by coolbeet** [comment]
any update on this? We are working on a restaurant payment solution and tip has to be added after authorization.

**Comment by ingalls** [comment]
An update on tipping would be amazing. We're a climbing guide service and would love to get a terminal side tipping option. Right now it's really awkward to have to ask the client if & how much they want to tip as our backend UI is not customer facing.

**Comment by chunlea** [comment]
@bg-stripe Could you reopen this issue? As this is not been solved yet.

**Comment by jaylattice** [comment]
@corin-stripe @bg-stripe +1 to this. In the context of Stripe Connect, is the temporary solution to just incorporate the tip into the final payment amount, then specify the tip amount as the `application_fee_amount`? https://stripe.com/docs/api/charges/create#create_charge-application_fee_amount

**Comment by chunlea** [comment]
@jaylattice No, the `application_fee_amount` is the amount you charging your connect account, not changing the customer. It's nothing about tips. 

> The value of `application_fee_amount` should be positive and lower than the **amount of the charge**. The application fee collected will be capped at the amount of the charge.
https://stripe.com/docs/connect/direct-charges#collecting-fees

**Comment by jaylattice** [comment]
@chunlea Thanks for the response! So if we wanted to charge the user $5 on behalf of the connected account (e.g. $5 t-shirt being sold by connected account), but wanted a $2 effective additional tip to our platform, could we not just charge $7 and then take $2 as an application fee from the connected account? The final result being the same -- connected account gets $5 (minus stripe fees), our platform gets $2.

**Comment by chunlea** [comment]
> @chunlea Thanks for the response! So if we wanted to charge the user $5 on behalf of the connected account (e.g. $5 t-shirt being sold by connected account), but wanted a $2 effective additional tip to our platform, could we not just charge $7 and then take $2 as an application fee from the connected account? The final result being the same -- connected account gets $5 (minus stripe fees), our platform gets $2.

According to their doc, you need to create a $7 charge, and set up a $2 `application_fee_amount`, but you should also the tips($2) before you create the charge, which is not what we want as a tips feature. The tips feature we want is to create a charge first, and then add tips to that charge.

**Comment by jaylattice** [comment]
@chunlea Yes, it seems for our use-case simply increasing the charge to include the tip amount and then using that as the `application_fee_amount` should work. For your use-case, wouldn't you be able to create an unconfirmed `PaymentIntent`, then prompt the user for a tip, then update the created payment intent (https://stripe.com/docs/api/payment_intents/update) followed by confirming the payment intent? Would that work for you?

**Comment by jil-stripe** [comment]
Hi all -- thanks for all the continuing excitement around tipping through Stripe Terminal. We’ve been working on something, but we’re not ready to formally announce it just yet. In the meantime, if you'd like to register your interest, please email support-terminal@stripe.com with your Stripe account ID if you know it (it looks like `acct_abc123`); otherwise, sit tight and we’ll have something to announce later.

**Comment by Osuriel** [comment]
Taking a tip or asking for a tip before the customer pays doesn’t make any sense. The whole point of tips/gratuity is that the customer chooses to pay that AFTER the the order has been paid for, as a bonus (yes we know bad servers feel entitled to it but that’s irrelevant) if the service was good. Asking for a tip before the the order hasn’t been paid for is as stupid as paying for something online but you don’t get to see what it is until after it arrives at your house. Anything that requires the tip to be paid upfront is not a solution. Because if its being paid upfront is not a tip.
