### ISSUE TITLE
Add cardholder name to card_present info

### ISSUE THREAD

**Issue by nickmeulen** [stripe/stripe-terminal-ios#35]
***FEATURE REQUEST***
It would be useful to have the cardholder's name add the to the card_present data. This information is available when using other readers such as Magtek.

**Comment by JKazarian** [comment]
Have there been any updates on this?

**Comment by jil-stripe** [comment]
@nickmeulen and @JKazarian (and everyone else who 👍'd the issue) - The latest version of the Terminal iOS SDK, version 1.1.1, adds the [`cardholderName` field](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPCardPresentDetails.html#/c:objc(cs)SCPCardPresentDetails(py)cardholderName) to the `SCPCardPresentDetails` class.

Thanks for writing in with the feature request! Let us know if you have any feedback.

James
