### ISSUE TITLE
Card reader does not accept swipe method when using insert method failed at first time

### ISSUE THREAD

**Issue by trdgkhoa** [stripe/stripe-terminal-ios#36]
I faced with an issue when collect payment on stripe terminal example app. This is these steps to reproduce that:
- Assumed that application already connected with card reader successfully
- Go to: Collect card payment
- Leave default amount value and tap collect payment button
- The log is waiting for collect payment method: **Swipe / Insert / Tap**
- Insert test card into card reader make sure that is using wrong slide => The log should request user "Try another read method" -> **Swipe / Insert**
- From now, i Swipe the test card many times but card reader could not detect that method
- Insert test card as correct way again, then the collect payment is success 

The thing I'm confusing here is the Try another read method request user using **Swipe / Insert** method but actually Swipe method could not use any more. Could we please fix that by provide another request payment method "Insert" only or keep that request message but allow user Swipe test card?

**Comment by danj-stripe** [comment]
Hi @trdgkhoa,

Can you provide some more details about what messages the SDK is sending to your [SCPReaderInputDelegate](https://github.com/stripe/stripe-terminal-ios/blob/master/PublicHeaders/SCPReaderInputDelegate.h) during this flow?

What I think is happening in your 2nd to last step is that when you swipe your test card, you're receiving both:

1. `terminal:didRequestReaderInputPrompt:` with `SCPReaderInputPromptInsertCard`
https://github.com/stripe/stripe-terminal-ios/blob/877acd566f776865c8030943157bd2b21f0dff7e/PublicHeaders/SCPReaderInputDelegate.h#L44-L46

If you're receiving [`SCPReaderInputPromptInsertCard`](https://github.com/stripe/stripe-terminal-ios/blob/877acd566f776865c8030943157bd2b21f0dff7e/PublicHeaders/SCPReaderInputPrompt.h#L24-L27) when swiping, that particular card doesn't allow swiping and it needs to be inserted.

2. `terminal:didBeginWaitingForReaderInput:` with `SCPReaderInputOptionSwipeCard | SCPReaderInputOptionInsertCard`
This method lets you know that the Chipper is still reading swipes. For example: a different card, one that doesn't have an EMV chip, will still work.
https://github.com/stripe/stripe-terminal-ios/blob/877acd566f776865c8030943157bd2b21f0dff7e/PublicHeaders/SCPReaderInputDelegate.h#L29-L32

----

If my guess is wrong, please let me know what messages your delegate *is* receiving, and we can look into it further.

Thanks,
Dan

**Comment by trdgkhoa** [comment]
Hi @danj-stripe, Thanks for the quick responses. Following these implementations defined at here: https://github.com/stripe/stripe-terminal-ios/blob/master/Example/Example/PaymentViewController.swift#L203

- For the fist request payment method, that method returned: **"Swipe / Insert / Tap"** 
- I'm using Insert method but insert wrong slide then getting an instructions **"Try another read method"**
- The second request payment method returned: **"Swipe / Insert"** 
- I'm Using Swipe method many times but nothing happens until I inserted the test card again

In order to present this issue I recorded these steps on this: https://youtu.be/EVdrkD5cHxg, Hopefully it helpful!

Thanks,
Khoa Tran

**Comment by danj-stripe** [comment]
Hi @trdgkhoa,

That video *was* helpful, thank you.

Unfortunately, the Stripe Terminal Test Card you're using does not have a magstripe track, and that's why it's not being read via Swiping. I realize the red "TEST CARD" strip on the back does look like one. The newer test cards have a different design, and it should be more apparent that they do not support swipes.

Dan
