### ISSUE TITLE
Could not process the second transactions when user does not remove test card from reader

### ISSUE THREAD

**Issue by trdgkhoa** [stripe/stripe-terminal-ios#37]
This issue happen when user insert test card into card reader but did not removed the test card after the payment successfully. Continuously, user create second payment then getting stuck at here.

I recorded these steps to reproduce this issue at here: https://youtu.be/0KcCDAK0dNw Pls take a look!

Thanks,
Khoa Tran

**Comment by bg-stripe** [comment]
Hi @trdgkhoa ! Can you try updating your reader to the latest version? I believe this has been improved in the latest available firmware version. Please update your example app to the latest version before the update (as we've made some improvements to the update flow).

Let us know if that improves the behavior!

**Comment by jil-stripe** [comment]
@trdgkhoa —
I'm going to close this issue, because I think we've improved the SDK's behavior around this flow. Please feel free to re-open it (or open a new issue) if you're still having trouble, though!
