### ISSUE TITLE
Ability to disable EMV payments for readSource

### ISSUE THREAD

**Issue by pushchris** [stripe/stripe-terminal-ios#38]
If you are trying to store a users card for later use by using the ```readSource``` method you can only convert the token from a ```card_present``` to ```card``` source if it is not a contactless EMV payment. The difficult part being that with the Chipper 2X it's so sensitive that it will many times pickup the contactless before the chip if you are fiddling to get it in. Would be nice to have a way to disable EMV if you are expecting to store the source so as to avoid this issue in the field.

**Comment by kenny-evitt** [comment]
Relatedly, it'd be nice if the 'reader input (prompt)' message(s) didn't include 'tap' for this scenario so we can just pass that message along to our apps without modification.

**Comment by danj-stripe** [comment]
Thanks for the feedback! We've disabled `Tap` during the `Terminal.readReusableCard` command, and you can find that in our latest release: https://github.com/stripe/stripe-terminal-ios/releases/tag/v1.0.0
