### ISSUE TITLE
BUG: reconnect issue when Bluetooth toggled on/off

### ISSUE THREAD

**Issue by nickmeulen** [stripe/stripe-terminal-ios#42]
Bug: reconnect fails to persist when bluetooth toggled on/off

Workflow to reproduce:

1. Discover Readers
2. Selected Reader and Connect (Connected)
3. Check Connection Status (Connected)

Up to this point all is fine. I have a background process that periodically checks the connection status as a hack solution to keep the device on and connected when not in use due to customer feedback of always having to reconnect after a period of time. Device remains connected when here. 

If the device is put to sleep and the connection closes, I have a modal view which prompts the user to turn the reader on and bring near the device. 

1. Check Connection on Device Wakeup (Not Connected)
2. Show Modal
3. Discover Readers (opens on modal show)
4. Reconnect to Previous Reader (auto connects on finding device using saved serial number: Connected)
5. Repeat background process to keep reader on (Connected)

Here is where the issue arises. 

1. Connect to Device and Initiate background process
2. Turn off bluetooth
3. Check Status (background, Not Connected, Bluetooth Error)
4. Show Modal to prompt user to turn bluetooth on and retry connection via user confirmation
5. Show Reconnection modal as per previous scenario
6. Discover Reader (auto on modal show)
7. Reconnect to Reader (auto connects on finding device using saved serial number: Connected)
8. Repeat background process (Not Connected)

In this step 8 in the background process, the `Terminal.shared.connectedReader` is `nil`. 

I have attempted wrapping the connection in `DispatchQueue.main.async { ... }` but still end up with the same issue. The Terminal instance does not save the connected reader and no disconnect events get fired.

**Comment by danj-stripe** [comment]
Hi @nickmeulen,

Thanks for reporting this. I'm not positive we've fixed the BT disabled -> BT enabled -> re-connect -> `connectedReader == nil` bug, but we have fixed a variety of bugs that might have helped.

Most significantly, I believe we've addressed the bug that would disconnect from the reader in the background, so your background process + reconnect flow shouldn't be used as often. I also fixed a problem with BT permission detection, although I'm not sure you were hitting that specific problem.

Can you let us know if you're still seeing this after updating to [v1.0.0](https://github.com/stripe/stripe-terminal-ios/releases/tag/v1.0.0)?

If you are, some more details would be useful:

* SDK & iOS versions
* DiscoveryMethod used
* any code you can share to reproduce
* logs from the app/SDK when this happens. Use [setLogListener](https://github.com/stripe/stripe-terminal-ios/blob/v1.0.0/PublicHeaders/SCPTerminal.h#L73-L84) and [logLevel](https://github.com/stripe/stripe-terminal-ios/blob/v1.0.0/PublicHeaders/SCPTerminal.h#L112-L114)

Thanks!

**Comment by jil-stripe** [comment]
@nickmeulen —
Going to close this issue, as I think we fixed the bug you were seeing.

If you're still having issues, feel free to re-open this issue or open another one.

Thanks!
