### ISSUE TITLE
"This application does not have the required permissions for this endpoint"

### ISSUE THREAD

**Issue by jacobrharris** [stripe/stripe-terminal-ios#45]
I'm getting this error when trying to use `-[SCPTerminal readReusableCard:delegate:completion:]`:

```
This application does not have the required permissions for this endpoint on account 'acct_abcd1234'. The required permissions are not available for use by Connect applications.
```

This used to work, so it seems like something changed.

**Comment by bg-stripe** [comment]
Thanks for flagging @jacobrharris ! To help us diagnose the issue, could you provide the full error response? (e.g. output from `print(error)`) It'd be super helpful to get your request id (which looks like `req_abc123`)

**Comment by jacobrharris** [comment]
@bg-stripe Here's a more complete error:

```
com.stripe-terminal:StripeAPIRequestId=req_Wp7bRuoxCiItbc, com.stripe-terminal:HttpStatusCode=403, com.stripe-terminal:StripeAPIErrorType=invalid_request_error, com.stripe-terminal:Message=This application does not have the required permissions for this endpoint on account 'acct_abcd1234'. The required permissions are not available for use by Connect applications.
```

**Comment by jd-stripe** [comment]
@jacobrharris Really sorry that you ran into this issue, we have a fix that's going out soon. Could you check back in an hour please?

**Comment by bg-stripe** [comment]
Should be fixed now – let us know if you have any further issues!
