### ISSUE TITLE
Simulator: "Access to location services is currently disabled"

### ISSUE THREAD

**Issue by nprail** [stripe/stripe-terminal-ios#46]
I am getting the following error when running `processPayment` on an iOS simulator.

```
Access to location services is currently disabled. Location access is required to connect to a reader and create payments.
```

I have `NSLocationWhenInUseUsageDescription` in the Info.plist and I gave the app location permission when it asked.

**Comment by danj-stripe** [comment]
Hi @nprail,

When I receive that error in the simulator, I usually have to turn on (or toggle off/on) Location Simulation:

<img width="897" alt="Screen Shot 2019-06-10 at 11 17 12 AM" src="https://user-images.githubusercontent.com/30532866/59216840-68f59100-8b71-11e9-924e-b79015def1d4.png">

Let us know if that doesn't solve your issue.

**Comment by nprail** [comment]
@danj-stripe Yep, that fixed the issue. Thanks!

**Comment by danj-stripe** [comment]
Hi @nprail,

Glad to hear it!  We do have a note, but I think there might be a better place to put it, so thanks for the suggestion.
