### ISSUE TITLE
Xamarin Binding Library

### ISSUE THREAD

**Issue by joshbartley** [stripe/stripe-terminal-ios#47]
Attempting to generate a Xamarin binding library using the PublicHeaders alone auto-generates a binding file that does not build without significant work. With the release of the Android SDK, cross-platform is a use case that we are very much interested in and it would be great if it was a supported option going forward. 

For example, Objective Sharpie generates the following amount of warnings in attempting to create a binding.
107 instances to verify for ConstantsInterfaceAssociation
127 Instanced of MethodToProperty
23 instances of StronglyTypedNSArray
2490 Instances of PlatformInvoke

**Comment by bg-stripe** [comment]
Hi @joshbartley ! Based on #56 and #57 , it sounds like you may have made some progress on this issue?

---

For other users looking at this issue:

I'd love to see users collaborating on plugins for multi-platform frameworks like Xamarin. Until we have official support, it'd be great to start steering users towards these projects from our docs and Readmes. 

We know of two projects like this so far:
- https://github.com/theopolisme/react-native-stripe-terminal
- https://github.com/eventOneHQ/cordova-plugin-stripe-terminal

Please share more if you know of any!
