### ISSUE TITLE
Commands fail when triggered from completion block

### ISSUE THREAD

**Issue by edmond-c** [stripe/stripe-terminal-ios#48]
### Steps 
1. create a payment intent
1. call `collectPaymentMethod(paymentIntent:delegate:completion:)`
1. call `cancel(completion:)` on the returned `Cancelable`
1. inside the completion block, call `cancelPaymentIntent(_:completion:)`

### Expected
- No errors thrown in the `cancelPaymentIntent` completion block
- Payment intent is canceled

### Actual
- `cancelPaymentIntent` completion block is called with error: 
```
Could not execute createRefund because the SDK is busy with another command: collectPaymentMethod
```
- Payment intent is not canceled

## Workaround
Delay calling `cancelPaymentIntent(_:completion:)` (step 4) by 5 seconds

**Comment by danj-stripe** [comment]
Hi @edmond-c,

Yes, currently the cancelation completion block is called first, and that's done before the SDK has finished all the cleanup/teardown from the current command.

What I recommend instead is checking for `SCPErrorCanceled` [doc link](https://github.com/stripe/stripe-terminal-ios/blob/v1.0.0/PublicHeaders/SCPErrors.h#L111-L113) in the `collectPaymentMethod` completion block, and handling appropriately. When we call the `collectPaymentMethod` completion, the SDK is ready for a new command, and you won't run into this issue.

Thanks for the feedback!
