### ISSUE TITLE
integrate_framework.sh: No such file or directory on build

### ISSUE THREAD

**Issue by igostavro** [stripe/stripe-terminal-ios#52]
I have followed the manual instruction steps to the letter and I get the following error when trying to build:

StripeTerminal.framework/integrate_framework.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

Note:

I have to check "Run script only when installing" under the Run Script build page in order to get it to build with no errors. Is this correct?

**Comment by acwright** [comment]
The README is incorrect. It should say:

```
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/StripeTerminal.framework/integrate-framework.sh"
```

`integrate-framework.sh` instead of `integrate_framework.sh`

**Comment by jil-stripe** [comment]
@igostavro and @acwright -
Thanks for flagging and for providing a workaround! We'll check back in when the readme is fixed.
James

**Comment by jil-stripe** [comment]
We've fixed the readme, thanks again for flagging.
