### ISSUE TITLE
Microphone access - is it an absolute must?

### ISSUE THREAD

**Issue by allen-zeng** [stripe/stripe-terminal-ios#54]
Hi!

I understand that the README states:

>Note: Although we do not currently support any audio-jack card readers, you'll still need to add a Microphone Usage Description to your Info.plist to pass App Store validation, as our underlying hardware SDK accesses these APIs. Since the SDK never actually uses microphone access, your users will never see a prompt for the microphone permission.

My question is, is there any possibility to *not* use these APIs? It's strange to have to explain this to people, and potentially to Apple in the future.

If we can, splitting out the part of the library where we do use the microphone into its own framework (subspecs etc.) would be ideal, so clients can opt in if they choose to.

**Comment by bg-stripe** [comment]
Hi @allen-zeng ,

You don't need to explain this to your users, since the SDK never actually uses microphone access (our hardware SDK just includes access to those APIs, for different devices).

We understand this is confusing, and we'll see if we can improve this – thanks for the feedback!

**Comment by cumanzor** [comment]
@bg-stripe you'll still need to add some kind of explanation in case Apple looks at this entries during review. Can be something generic as what is mentioned in the docs.

Also, as of iOS13, the "Privacy - Bluetooth Always Usage Description" (`NSBluetoothAlwaysUsageDescription`) key is also necessary, otherwise the app crashes.

**Comment by jil-stripe** [comment]
@allen-zeng and @cumanzor —
We've [released version 1.0.2](https://github.com/stripe/stripe-terminal-ios/releases/tag/v1.0.2) of the SDK, which removes the need to include `NSMicrophoneUsageDescription` in the app's `Info.plist`. Hope this works for you both.

Also, @cumanzor, thanks for calling out the iOS 13 change! We've updated [our docs](https://stripe.com/docs/terminal/sdk/ios#configure) to reflect that this key is required for iOS 13.
