### ISSUE TITLE
Xamarin binding generated from 1.0.0 ios release is giving a "unrecognized selector sent to class"

### ISSUE THREAD

**Issue by vibol03** [stripe/stripe-terminal-ios#57]
Hi,
Basically, when i was working with the 1.0.0-rc2 sdk, everything was fine.
Now that i have upgraded to the 1.0.0 release and generated a new c# binding from it, i keep getting this error when calling properties in the SCPTerminal class to set the token provider.

> Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: +[SCPTerminal hasTokenProvider]: unrecognized selector sent to class 0x109d089b0
Native stack trace:
	0   CoreFoundation                      0x000000018c97a9a4 <redacted> + 252
	1   libobjc.A.dylib                     0x000000018bb539f8 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018c89c214 <redacted> + 0
	3   CoreFoundation                      0x000000018c9801d4 <redacted> + 1408
	4   CoreFoundation                      0x000000018c981e6c _CF_forwarding_prep_0 + 92
	5   Cirro.iOS                           0x00000001080a775c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 89385908
	6   Cirro.iOS                           0x000000010809bd40 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 89338264
	7   Cirro.iOS                           0x0000000102c85d40 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 1167768
	8   Cirro.iOS                           0x0000000106688ae0 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 61996856
	9   Cirro.iOS                           0x0000000102fd084c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 4619428
	10  Cirro.iOS                           0x000000010667315c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 61908404
	11  Cirro.iOS                           0x00000001066a9d98 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 62132720
	12  Cirro.iOS                           0x0000000102fd013c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 4617620
	13  Cirro.iOS                           0x000000010667c8a4 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 61947132
	14  Cirro.iOS                           0x0000000103418b60 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 9109432
	15  Cirro.iOS                           0x0000000103418984 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 9108956
	16  Cirro.iOS                           0x00000001033f14c4 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 8947996
	17  Cirro.iOS                           0x00000001033ec4ac _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 8927492
	18  Cirro.iOS                           0x0000000105ceefa8 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 51930112

Also please see my [ApiDefinition.cs](https://drive.google.com/open?id=1y-KtC71x_8hZ0NR9oXL8mmxo2h2RJG4v) and [Structs.cs](https://drive.google.com/open?id=1ndGtIKQSR6kGIM8TaTSY0fQF-wCjC5_g) here.
thanks!

**Comment by joshbartley** [comment]
@vibol03 check out #56  as I was using Xamarin and had an issue after I created the bindings. Wanted to give you a notice on that as it might be the next issue you run into.

**Comment by bg-stripe** [comment]
Hi folks! 

Sorry you're both running into these Xamarin issues. @vibol03 @joshbartley would you be open to sharing your Xamarin bindings, and potentially collaborating on a single open-source project? 

I'd love to see users collaborating on plugins for multi-platform frameworks like Xamarin. Until we have official support, it'd be great to start steering users towards these projects from our docs. 

We know of two projects like this so far:
- https://github.com/theopolisme/react-native-stripe-terminal
- https://github.com/eventOneHQ/cordova-plugin-stripe-terminal

Please share more if you know of any!

**Comment by jil-stripe** [comment]
Hi all - this issue seems stale, so we’re going to close it. If you continue to see errors from the SDK, please update to the 1.4.0 or 2.0.0 versions of the SDK and open another issue if the error is still taking place.

Thanks!
