### ISSUE TITLE
Support for Swift Package Manager (SPM)

### ISSUE THREAD

**Issue by jasonzurita** [stripe/stripe-terminal-ios#61]
Now that SPM is a first class citizen in Xcode (Xcode 11), this will be increasingly more important.

**Comment by jil-stripe** [comment]
@jasonzurita — thanks for writing in. The Terminal iOS SDK is closed source, and we haven't seen good support for closed source packages in SPM yet -- there's a [discussion going on about this](https://forums.swift.org/t/spm-support-for-binaries-distribution/25549/45) in the Swift forums.

This is definitely something we'll keep our eyes on, but Terminal doesn't have any SPM plans for now.

**Comment by rlimberger** [comment]
@jil-stripe Since Swift 5.3 has [implemented](https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md) SPM support for closed source packages, do you have any updates on this?

**Comment by jil-stripe** [comment]
@rlimberger and @jasonzurita -
We were excited to hear about the announcement at WWDC! While I don't have any definite updates for you, it's something that we're more actively considering.

I'll reopen the issue and will provide more information when I have it!

**Comment by eneko** [comment]
@jil-stripe any updates or ETA on this?

**Comment by tiltem** [comment]
@jil-stripe Support for SPM can be achieved by distributing the StripeTerminal framework as a XCFramework. Don't think this will require any code changes, just some changes to the way the distributed framework is compiled. Here is an article with some details about the process: https://help.apple.com/xcode/mac/11.4/#/dev544efab96

**Comment by dcilia** [comment]
@jil-stripe Currently we are blocked from building our app with Xcode 12.3 until this is updated to a ```xcframework``` .  Any updates on an ETA y'all can provide?

**Comment by bric-stripe** [comment]
👋 @dcilia we just uploaded a repackaging of the 1.4.0 release as an [xcframework](https://github.com/stripe/stripe-terminal-ios/releases/download/v1.4.0/StripeTerminal.xcframework.zip) and attached it to the [release](https://github.com/stripe/stripe-terminal-ios/releases/tag/v1.4.0). That should unblock Xcode 12.3 usage, but let us know of any issues. We still plan to offer a proper Package.swift for SPM so leaving this issue open for that.

**Comment by garsdle** [comment]
If there is any movement on this it would make a big difference for our project! We've moved away from Cocoapods and this is the last lib we need to change and doing things manually isn't ideal. Is there some sort of ETA on this?

**Comment by bric-stripe** [comment]
We just added a Package.swift pointing to the current 1.4.0 release to a branch, [`spm_beta`](https://github.com/stripe/stripe-terminal-ios/tree/spm_beta), that can be used for folks needing an option now. When adding in Xcode enter that as the branch:

<img width="456" alt="spm" src="https://user-images.githubusercontent.com/62762265/105105946-fac1c180-5a69-11eb-8091-7f6222ad53c4.png">

We still plan to add a proper Package.swift on future releases so we'll continue to leave this issue open so folks subscribed can be notified when we have a future release including proper SPM support.

**Comment by ctarda** [comment]
👋  Hiya @bric-stripe ! We are trying to integrate this SDK into WooCommerce. 

We might have painted ourselves into a corner here, but we would love to be able to pull this dependency as a SPM. It would make our implementation much cleaner. 

Do you think it would be possible to tag the head of the `spm_beta` branch with a beta tag that we could use to pull the dependency?

**Comment by bric-stripe** [comment]
@ctarda we just pushed up a tag, `v1.4.0-spmbeta` which can be referenced with `.exact`:

`.package(name: "StripeTerminal", url: "https://github.com/stripe/stripe-terminal-ios", .exact("1.4.0-spmbeta")),`

I found I had to specify exact otherwise SPM seems to try to check for a non-pre-release 1.4.0 to upgrade to, and since we have that tag it gets upset that there isn't a Package.swift there. But hopefully that unblocks you.

**Comment by ctarda** [comment]
Thanks @bric-stripe 🙇 

This definitely unblocks us, our build is squeaky ✅ now.

Thanks! Onwards!

**Comment by jil-stripe** [comment]
Hi all - We've recently released version 2.0.0 of the Terminal iOS SDK, which includes a proper Package.swift. We’ll be keeping that up to date as we release updates.

To add StripeTerminal to your project, you can now add the following to your `package.swift`:

```swift
.package(name: "StripeTerminal", url: "https://github.com/stripe/stripe-terminal-ios"),
```

**Comment by bat111** [comment]
hi 
i am trying to  create POS app but stripe package manager max version points 0. Does it mean no package manager available this time? Tried quiet much. not able to use it even seems installed.
thanks

**Comment by bat111** [comment]
@jil-stripe
