### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by Hakikat2512** [stripe/stripe-terminal-ios#63]
I am trying to implement Stripe terminal in my project which is compiled in Xcode 11.1.
I have downloaded the example application and getting the following error :
 **Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler**  
on Import static framework

please provide the support for the latest swift version.

**Comment by catriona-stripe** [comment]
If you run setup.sh which is in the Example/ directly this should fix the error you are seeing! Please tell us if you have any more issues.
