### ISSUE TITLE
Example app (and SDK) using Chipper2X requires NSBluetoothAlwaysUsageDescription for iOS 13

### ISSUE THREAD

**Issue by mlatham** [stripe/stripe-terminal-ios#64]
From a fresh pull of the latest Example app on Xcode 11 running iOS 13, if I launch and tap Discover Readers, I get the following log output:

> 2019-11-08 09:48:11.608186-0800 Example[4208:1396193] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSBluetoothAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.

If looks like the SDK doesn't only require the NSLocationWhenInUseUsageDescription key, but also the NSBluetoothAlwaysUsageDescription key for iOS 13 deployments. When I add the NSBluetoothAlwaysUsageDescription key to my Info.plist, everything works fine.

```
<key>NSBluetoothAlwaysUsageDescription</key>
	<string>Bluetooth access is required in order to connect to supported bluetooth card readers.</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>Bluetooth access is required in order to connect to supported bluetooth card readers.</string>
```

Looks like the example and documentation needs updating to reflect this.

**Comment by ericvicenti** [comment]
Agh, thank you @mlatham! I've been trying to figure out why my app mysteriously crashes when scanning for bluetooth card readers on iOS 13.

**Comment by jil-stripe** [comment]
Hi @mlatham and @ericvicenti! We've [fixed this in the latest release](https://github.com/stripe/stripe-terminal-ios/commit/394c587db6b37b7376f30d84adbd09a38bbe46ac#diff-4e2ed937d93d33186d66849d0c40ce41), v1.0.3. Thanks for reporting it and posting the workaround in the meantime!

I'm going to close this issue, but feel free to open another one if you're still having issues.
James
