### ISSUE TITLE
Add support for Mac Catalyst

### ISSUE THREAD

**Issue by acwright** [stripe/stripe-terminal-ios#66]
It appears that this framework will not build for Mac Catalyst. It would be nice if this was possible. I am currently building an iOS application that consumes this framework and it would be nice to port to Mac with Catalyst.  

```
error: Building for Mac Catalyst, but the linked and embedded framework 'StripeTerminal.framework' was built for iOS + iOS Simulator. You may need to restrict the platforms for which this framework should be linked and embedded in the target editor, or replace it with an XCFramework that supports both platforms.
```

Possibly related:

https://github.com/stripe/stripe-ios/pull/1404

Thank you for considering this!

**Comment by jil-stripe** [comment]
@acwright —
Thanks for reaching out. We don't have any updates to share about Catalyst at this time, but we'll consider adding support in the future.

I'm going to close this issue for now, but feel free to reach out with any other bugs or feature requests.

Thanks!
James
