### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler: /stripe-terminal-ios/Example/Carthage/Build/iOS/Static.framework/Modules/Static.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

### ISSUE THREAD

**Issue by jorge-acosta-abstracta** [stripe/stripe-terminal-ios#67]
Xcode Version 11.3 (11C29)
macOS Catalina 10.15.2 (19C57)

Sample application fails to compile after setting the heroku URL in AppDelegate.swift

**Comment by danj-stripe** [comment]
You can run the `./setup.sh` script to rebuild the example application's dependencies, and then it'll work with the latest version of Xcode.
