### ISSUE TITLE
Keep getting "Could not execute discoverReaders because the SDK is busy with another command: discoverReaders."

### ISSUE THREAD

**Issue by yosefsun** [stripe/stripe-terminal-ios#7]
Hi,

From some odd reason we keep getting the following error when initiating the card reader discovery -

> Could not execute discoverReaders because the SDK is busy with another command: discoverReaders.

This issue persists on both the stripe example app and our app.

If we change to the mocked (simulated) card reader, it works fine.

**Comment by yosefsun** [comment]
more info -

iOS version : 11.4.1
Xcode version : 10.0

Attached is reproduction.

![ezgif-4-56a898daf354](https://user-images.githubusercontent.com/5140364/47732313-53fc6b00-dc3c-11e8-8ce1-73c55082dadd.gif)

**Comment by bg-stripe** [comment]
Hey @yosefsun ! 

Sorry to hear about this issue. I'm unable to reproduce this on my end at the moment, but I'd love to get to the bottom of this. Could you:

1. Make sure you haven't modified the example app (other than adding your API key)
2. Reproduce the issue in your app (or the example app) and share the logs printed in the Xcode console

Thanks so much!

Ben

**Comment by yosefsun** [comment]
hi @bg-stripe, I had resolved the issue and created a PR to be merged with master - [](https://github.com/stripe/stripe-terminal-ios/pull/8)

**Comment by bg-stripe** [comment]
great, glad you were able to fix this issue! i'll take a look at the PR :)
