### ISSUE TITLE
Better SDK Parity for iOS & Android

### ISSUE THREAD

**Issue by chris-oswald** [stripe/stripe-terminal-ios#71]
This isn't a bug, but more of a request.  

There were certainly two different teams that worked on the iOS & Android SDKs.  

I would like to see better collaboration between platform teams.  Some Stripe classes expose different properties on the same object between platforms (Look at Payment Intent).  It not like this is a show stopper, it's just annoying there isn't more naming/design consistency where possible.

**Comment by tomas-stripe** [comment]
Hi Chris, thank you for the report. We try to keep our SDKs consistent across platforms so we do appreciate the flag for when they're not.

Can you share a bit more of your use case with us? Are you perhaps working with a cross-platform framework such as React Native?

**Comment by chris-oswald** [comment]
Yes, I'm using a cross-platform framework very similar to React Native.  It's Xamarin, but it's the same concept.  The closer my implementations look, the easier it is for me to maintain, but I obviously understand there will be platform nuances that can't be avoided.

**Comment by tomas-stripe** [comment]
We don't have official support for cross-platform frameworks yet, but we're considering promoting open-source versions in our documentation (such as https://github.com/theopolisme/react-native-stripe-terminal). Would you have any interest in open-sourcing your solution? It would also help us better understand the use case and gather momentum from other users.

**Comment by joshbartley** [comment]
@chris-oswald do you have the android 1.0.8 binding working? I'm getting binding errors with it. For the iOS side sharpie pod init is throwing an error. I remember some of these issues getting the binding library setup but wanted to ask in case you already found the solution for the latest version.

**Comment by chris-oswald** [comment]
@joshbartley I have the latest iOS version 1.0.3 working and I have 1.0.7 working on Android.  I suspect my 1.0.7 bindings would work just looking at the release notes.  I've been using everything in production for about a month without any issues.  

I've actually gotten quite a few compliments from customers that were using Square before.

**Comment by chander-stripe** [comment]
@joshbartley feel free to file an issue with our android folk (me) over at https://github.com/stripe/stripe-terminal-android - I'd love to know which specific error you're getting and help you diagnose!

**Comment by chris-oswald** [comment]
@joshbartley @chander-stripe I have the latest versions (iOS & Android) working on Xamarin.  We plan to publish a repo on github in the next week or two that will at least have the bindings even if we don't have a reference implementation.

**Comment by joshbartley** [comment]
@chris-oswald the bindings would be great. I found out that objective sharpie can't generate the bindings using cocoapods> 1.8.x. Downgrading cocoapods to 1.7.x allowed the iOS bindings to be regenerated. The Android bindings library is giving a class not found error related to kotlin which I am sure is related to how I'm referencing the bindings. It would be great to see how you have generated the bindings project.

**Comment by bric-stripe** [comment]
Hi, I'm closing out stale issues. I realize this is an old one but regarding the original concern we know there are still parity issues between SDKs today both in naming[^1] and in certain behaviors. We will be working through these but no timelines to share.

[^1]: error codes is a big one here
