### ISSUE TITLE
Unable to reconnect reader if `checkForUpdate` is called immediately after disconnection

### ISSUE THREAD

**Issue by samjp** [stripe/stripe-terminal-ios#79]
## Summary

Calling `Terminal.shared.checkForUpdate` immediately after turning off a connected reader causes all subsequent calls to `Terminal.shared.discoverReaders` to fail with `SCPErrorBusy`.

Steps to reproduce on the Stipe Terminal example app:
1. Install and run Stipe Terminal example app on an iOS device
2. Turn the 'Simulated' toggle off
3. Press 'Discover Readers'
4. Connect a physical 'Chipper 2X' reader
5. Once connected, tap the 'Update reader software' cell in the 'Common Workflows' section
6. Turn the reader off
7. Immediately tap 'Check for update' on the 'Update Reader' screen (this must be done before the 'Reader disconnected' alert is presented)
8. Trying to reconnect the reader fails until the app is restarted

## iOS version

iOS 13.4
## Installation method

Cocoapods 
## SDK version

1.0.3
## Other information

I suspect other calls to the `Terminal.shared` will fail for the same reason but have not tested it.

**Comment by aliriaz-stripe** [comment]
Hi @samjp , thanks for flagging and the detailed repro steps!
I can repro on the Example app on v1.1.0, the Terminal team will have a look.
