### ISSUE TITLE
Deprecated API Usage - UIWebView 

### ISSUE THREAD

**Issue by Vnox** [stripe/stripe-terminal-ios#82]
## Summary
There is a UIWebView match in the binary file 
`.../Carthage/Build/iOS/StripeTerminal.framework.dSYM/Contents/Resources/DWARF/StripeTerminal` 

Which Apple is recognizing as 

ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. 

## SDK version
1.1.1

**Comment by jil-stripe** [comment]
Hi @Vnox, thanks for the report. We'll investigate this internally and let you know what we find.

James

**Comment by Vnox** [comment]
@jil-stripe Thank you!

**Comment by jil-stripe** [comment]
@Vnox - we've gone through our source code and our generated binaries, and it looks like we don't link against UIWebView anywhere in the SDK. 

Running

```
$ nm ".../Carthage/Build/iOS/StripeTerminal.framework.dSYM/Contents/Resources/DWARF/StripeTerminal"| grep -i UIWebView
```

should return no results.

It looks like people are running into similar issues with other frameworks -- I think [this issue from Mapbox](https://github.com/mapbox/ios-sdk-examples/issues/373) describes a similar problem. Like Mapbox, we link to UIKit, which seems to trigger false positives in App Review if your app contains _other_ third-party frameworks that _do_ link against UIWebView. Like the Mapbox folks, we ship internal apps using Testflight and haven't run into this warning.

We'll keep an eye out if we see anything suspicious (or if we see these warnings in our internal apps), but I suspect you'll want to check your other dependencies using `nm`.

Thanks,
James

**Comment by Vnox** [comment]
@jil-stripe Thanks for looking into this. I tested again today, definitely a false positive on a local grep. Sorry if this took up your time : )
