### ISSUE TITLE
Unable to connect to the chipper using 1.2.1

### ISSUE THREAD

**Issue by thonydam** [stripe/stripe-terminal-ios#85]
## Summary
Using the latest version of the SDK `1.2.1`, we are unable to connect to the Chipper2X. Calling `connectReader:connectionConfig:completion:` will always lead to an `Unknown error` which seems to be a 500 error coming from Stripe API.

Using the same code with `1.2.0` works as expected.

## Code to reproduce
```Swift
    Terminal.shared.connectReader(reader, connectionConfig: connectionConfig) { connectedReader, error in
      if let error = error {
        //Unknown error, 500 
      }
    }
```

## iOS version
iOS 13.5.0
iPad Pro 3rd Gen

## Dev Env
Xcode 11.5
Swift5 

## Installation method
Cocoapods

## SDK version
1.2.1

**Comment by jil-stripe** [comment]
Hi @thonydam, thanks for the report. We're looking into it and will let you know what we find!

**Comment by aliriaz-stripe** [comment]
Hello @thonydam!

We weren't able to reproduce this on our end. We'd really like to unblock you here, could you verify if this is still happening? (want to verify if this was a transient issue or not)

If it is still happening, please do write in to https://support.stripe.com/contact with the details you provided above and we can dive in further from there! 

What would really help is if you're able to reproduce this in a fresh Xcode project, with for e.g. just 1 view controller that discovers readers and tries to connect and hits this issue. That way, you can share the fresh project with us (and not have to disclose any business logic), allowing us to run it on our end and help you out!
Looking forward to working with you there!

**Comment by thonydam** [comment]
Thank you for getting back to me. After cleaning xCode cache and re-installing the app, the issue went away.
