### ISSUE TITLE
Reader battery level changes

### ISSUE THREAD

**Issue by r-grabowski** [stripe/stripe-terminal-ios#90]
## Summary
Is it possible to follow the reader battery level change in real time?
It seems that there is only static battery level value after connection succeeded.
I also did not find any property whether the battery is charging or not.
Same on Android SDK

**Comment by jil-stripe** [comment]
Hi @r-grabowski - I think someone in the Terminal Android SDK repository [got to you first](https://github.com/stripe/stripe-terminal-android/issues/120#issuecomment-746833085), but it's the same story on iOS: there's no way to do that today, unfortunately, but we're looking into improving this in a future release. Hope that helps.

James
