### ISSUE TITLE
jumping battery level after charging

### ISSUE THREAD

**Issue by r-grabowski** [stripe/stripe-terminal-ios#91]
## Summary
Jumping battery level after short charging

## Steps to reproduce
1. Connect device to app - battery level around 14%
2. Charging reader for 5 min - measured by power meter around 27mAh (~4% battery capacity)
3. Reconnect device with app - battery level around 34%
4. Wait for about 5 seconds
5. Reconnect device with app - battery level around 25%

## iOS version
iOS 14.2

## device
Chipper™ 2X BT

## SDK version
pod 'StripeTerminal', '1.4.0'

**Comment by bric-stripe** [comment]
Thanks for reporting - just acknowledging that we've been able to reproduce and have reported details to BBPOS (Chipper 2X's manufacturer). We'll add additional info here as we have it.

**Comment by bric-stripe** [comment]
Closing out stale issues. Sorry I missed getting back to this one. Unfortunately this is a limitation of the Chipper hardware and firmware and in its current state won't be fixed. The Stripe Reader M2 and WisePad 3 should be reporting more consistent battery levels.
