### ISSUE TITLE
Manual Installation Broken on Xcode 12.3

### ISSUE THREAD

**Issue by garsdle** [stripe/stripe-terminal-ios#92]
## Summary
Manual embedding of the StripeTerminal.framework now causes the error
![Screen Shot 2021-01-11 at 5 28 35 PM](https://user-images.githubusercontent.com/6522133/104257500-72706a80-5432-11eb-8708-f453c8d2e15d.png)

I cannot use Cocoapods but could use SPM. Please advise.

## Code to reproduce
Follow manual installation steps on Xcode 12.3

## Installation method
Manual

## SDK version
1.4

**Comment by bric-stripe** [comment]
👋 @garsdle, we recently uploaded a repackaging of the 1.4.0 release as an [xcframework](https://github.com/stripe/stripe-terminal-ios/releases/download/v1.4.0/StripeTerminal.xcframework.zip) and attached it to the [release](https://github.com/stripe/stripe-terminal-ios/releases/tag/v1.4.0). That should unblock Xcode 12.3 usage, but let us know of any issues.

**Comment by garsdle** [comment]
That worked but for reference I had to move the `integrate-framework.sh` to the common directory.

Thanks for the quick reply.
Cheers!
