### ISSUE TITLE
Support the iOS Mac M1 simulator.

### ISSUE THREAD

**Issue by michaelosity** [stripe/stripe-terminal-ios#94]
## Summary

Support running in the simulator on the new Mac M1s.

On x86 Macs, the simulator is x86 but the new M1s use arm. So you can't link against this library as-is, because you get an on-device build or an x86 simulator build (or both in one package).

I think this might be fixed by supporting SPM too.

**Comment by michaelosity** [comment]
A workaround is to just use the built-in Mac OS based app. It doesn't use the simulator so it isn't perfect, but it works for now.

**Comment by cumanzor** [comment]
Is there any update on this? I'm quite surprised there is still no support for the m1 simulator.

**Comment by kristohear** [comment]
Same here, it's currently only blocker

**Comment by robertsammons** [comment]
Any update on this?

**Comment by jil-stripe** [comment]
@michaelosity, @cumanzor , @kristohear, @robertsammons, and others who might be watching,

We've recently released version 2.0.0 of the Terminal iOS SDK, which includes multi-architecture support, so you can use the iOS simulator on both Intel and M1 Macs.

Thanks!
James
