### ISSUE TITLE
Mobile SDK v2.0.0 support

### ISSUE THREAD

**Issue by cumanzor** [stripe/stripe-terminal-ios#96]
## Summary
We are looking for a point of contact for the v2.0.0 beta, which we haven't been able to get (even via email). Namely, we have to issues we'd like some clarification on:

- The error testing values at https://stripe.com/docs/terminal/testing#physical-test-card are working for the Chipper reader, but not for the Wisepad 3 reader.
- (Wisepad only) When the reader is requesting a pin code, there doesn't seem to be any payment or devices status changes in sdk, so while we can see it asking for a pin code in the device itself, we cannot display a message indicating this in the app itself.

## Code to reproduce
N/A

## iOS version
iOS 11, 12, 13, 14.

## Installation method
Cocoapods. 

## SDK version
2.0.0b9

**Comment by jil-stripe** [comment]
@cumanzor,

Thanks for writing in. We’ve released 2.0.0 into GA, and our support staff should be able to help with integration issues you’re facing. You can get in touch with support by going to https://support.stripe.com/contact or by emailing support-terminal@stripe.com, and you can report SDK bugs here.

Addressing the issues you mentioned:


- The test cents value should work with the WisePad 3 reader in testmode -- our internal testing hasn't shown any issues there. If you're still having issues, you can try using the [SimulatorConfiguration object](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPSimulatorConfiguration.html) on SCPTerminal to test declines with a simulated WisePad 3.
- Calling a delegate method at the start of pin entry is a good feature request — we’ll discuss it and let you know if we implement it in a future version.

James
