### ISSUE TITLE
Terminal won't update

### ISSUE THREAD

**Issue by uncured** [stripe/stripe-terminal-ios#99]
## Summary
One of our clients experience the issue with not being able to connect to the Chipper 2X terminal after updating the app to the version including the SDK 2.0.0.
- Client can discover the nearby readers
- When trying to connect to the Chipper 2X terminal an update is reported and starts
- On the 5%-15% progress the error is reported and update is not going any further: `Could not communicate with the reader. Try resetting or recharging the reader.`
- The reader is charged to 94% and the hard reset was performed on the terminal, but none of that helped.

## Code to reproduce
None, just a regular Terminal.connect() call

## iOS version
iOS 14.6

## Installation method
Cocoapods

## SDK version
2.0.0

## Other information
User scenarios mentioned in the summary

**Comment by bric-stripe** [comment]
One suggestion to try to unblock ASAP would be to insert a paper clip in to hole on the back of the reader by the USB port to reset it and see if that clears an issue (not a great solution, just throwing it out there to see if that unblocks this reader).

Do you have the serial number of the reader? I'm curious to try to check on what the current firmware/configs its running to try to see if there could be an issue there.

**Comment by uncured** [comment]
Thanks for suggestion, Brian.
Resetting the terminal was our first suggestion to the client, and they claim that it didn't help.
One example is `CHB202009020130`

**Comment by bric-stripe** [comment]
@uncured thanks for getting that, after investigating the current installed config and the targets and some logs it unfortunately looks like that reader should be replaced so we can debug further. Does your team have a customer success manager and/or account manager to contact to request a replacement? If not you can get in touch with support by going to https://support.stripe.com/contact or by emailing support-terminal@stripe.com and mention this issue.

**Comment by uncured** [comment]
Thanks a lot, Brian. Our team already had some experience with the terminal replacement process, so I guess it should be clear.
